### ISSUE TITLE
What is a standard URL to reference IETF RFC?

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#1012]
Currently, five styles of referencing IETF RFC found across spdx-spec and spdx-3-model

1. https://tools.ietf.org/html/rfc1321 - Found in [Normative References](https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/normative-references.md). Also used by References section in Bob's Word doc 2024-07-22.
1. http://www.ietf.org/rfc/rfc3986.txt - [packageVerificationCodeExcludedFile](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/packageVerificationCodeExcludedFile.md)
1. https://datatracker.ietf.org/doc/rfc1319/ - [HashAlgorithm](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/HashAlgorithm.md)
1. https://datatracker.ietf.org/doc/html/rfc7693 - [HashAlgorithm](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/HashAlgorithm.md)
1. https://www.rfc-editor.org/rfc/rfc4634 - [HashAlgorithm](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/HashAlgorithm.md)

Additionally, there are other two styles of referencing IETF RFCs:

6. https://www.rfc-editor.org/info/rfc2046 - Used by a [bibtex](https://datatracker.ietf.org/doc/rfc2046/bibtex/) produced from [IETF Datatracker](https://datatracker.ietf.org/doc/rfc2046/) (click on "Formats: bibtex" button).
7. https://doi.org/10.17487/RFC3986 - Digital object identifier (DOI) for RFC, according to [RFC 7669](https://datatracker.ietf.org/doc/html/rfc7669#section-3)

These seven URLs land on different pages, but few of them are actually redirections:

- (4)-style redirects to (1)-style
- (7)-style redirects to (6)-style

In terms of functionality, they are all pretty much the same, as all of them (except (2)) have links to different file formats and other pages of the same RFC.

--

**Which one should we stick with?**

- Having multiple ways to refer to a single resource may require the automatic production of footnotes/bibliography  to aware that all of these are the same. Or we are at risk of producing duplicated references.
- I'm thinking about (6) as it is the one preferred by IETF themselves. But the downside of (6) (and (3)) is that you cannot link directly to subsection; while (1), (4), and (5) can. For example, https://tools.ietf.org/html/rfc7693#section-4 .

**Comment by bact** [comment]
I'm started to try (6) - the one like this: https://www.rfc-editor.org/info/rfc2046 to few docs, see:

- https://github.com/spdx/spdx-3-model/pull/806
- https://github.com/spdx/spdx-3-model/pull/810

**Comment by zvr** [comment]
I propose we use https://datatracker.ietf.org/doc/rfc1/ 
As with most of the alternatives, it has links to different formats, if one has a strong preference for viewing.

Of course, consistency is more important than any specific choice we made.

**Comment by bobmartin3000** [comment]
Agree on this approach to use https://datatracker.ietf.org/doc/rfc1/

**Comment by zvr** [comment]
@bact are we in agreement for `https://datatracker.ietf.org/doc/rfcXXXX/` ?

**Comment by kestewart** [comment]
All the URLs have been standardized in the big PR from Alexios,   but still need a discussion to see if need be resolved.

**Comment by zvr** [comment]
The References chapter has everything correct, but not all instances inside the other files are. Expect two PRs tomorrow (one in spec repo, one in model).

**Comment by bact** [comment]
I prefer `https://www.rfc-editor.org/info/rfcXXX/` (Option 6), only because it is the format used by a [bibtex](https://datatracker.ietf.org/doc/rfc2046/bibtex/) produced from [IETF themselves](https://datatracker.ietf.org/doc/rfc2046/) (click on "bibtex" button).

But as both `https://datatracker.ietf.org/doc/rfcXXX` (Option 3) and `https://www.rfc-editor.org/info/rfcXXX` (Option 6) are sharing the same disadvantage of not being able to link directly to a subsection of a document, choosing any of them is no difference for me in that respect. So no strong objection against Option 3.

Option 6 is the only format that is being used in every files in the spdx-3-model repo -- which should make it easier to be replaced by any other format.

**Comment by bact** [comment]
2 PRs created
- for spdx-spec https://github.com/spdx/spdx-spec/pull/1107
- for spdx-3-model https://github.com/spdx/spdx-3-model/pull/877
