### ISSUE TITLE
Should the SPDX V3 sbom contain a list of elements?

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#1013]
In the [example](https://github.com/spdx/spdx-spec/blob/development/v3.0.1/examples/jsonld/package_sbom.json), the `software_Sbom` contains a `rootElement` but does not include the list `element`.

Should the sbom include the root + all referenced elements (both direct and indirect)?  Just the root?

**Comment by lpanni** [comment]
I think for an example that is intended to be views by humans it is helpful to have a element collection to make relationships clearer. In the current state, one would have to manually go to the root element and then look for its relationships to find all elements.

But for the example use-case, all directly referenced elements should be enough.

**Comment by goneall** [comment]
Discussed on the SPDX tech call 30 July 2024 and consensus was we should have a minimum of 1 element + we should have a minimum of 1 root element for an SBOM.
