### ISSUE TITLE
Spec website: How do we like the URL aliases to work?

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#1018]
As it is difficult to explain for me, so I'm setting up a test website here for illustration.
(The test website is marked with "DRAFT (TEST-WEBSITE)" at the top and the bottom to avoid confusion)

We will use the URL of the test spec website https://bact.github.io/spdx-spec/
in place of
https://spdx.github.io/spdx-spec/ here for the purpose of discussion/demonstration.

Once 3.0.1 released, PR #1015 will made these following redirections:

### 1) Default redirection

If the user doesn't specify a version in the URL, we will bring them to the latest version:

https://bact.github.io/spdx-spec/  --> https://bact.github.io/spdx-spec/v3.0.1/

Do we like to have it like this?
(you can try clicking on these URLs)

https://spdx.github.io/spdx-spec/ currently redirects to https://spdx.github.io/spdx-spec/v3.0/

### 2) Alias

These following URLs will redirect to https://bact.github.io/spdx-spec/v3.0.1/ :

- https://bact.github.io/spdx-spec/latest/
- https://bact.github.io/spdx-spec/v3.0/
- https://bact.github.io/spdx-spec/v3-draft/
- https://bact.github.io/spdx-spec/v3.0-RC1/
- https://bact.github.io/spdx-spec/v3.0-RC2/

(Once we have 3.0.2, all of above will redirect instead to 3.0.2.
Once we have 3.1, "latest" will redirect to 3.1; but "v3.0*" will still redirect to the latest 3.0.x)

Do we like to have those URLs behave like that?

- latest currently redirects to v2.3 - try https://spdx.github.io/spdx-spec/latest/
- v3.0 currently contains v3.0 content
- v3-draft currently redirects to v3.0 - try https://spdx.github.io/spdx-spec/v3-draft/
- v3.0-RC1 never exists
- v3.0-RC2 currently redirects to v3.0 - try https://spdx.github.io/spdx-spec/v3.0-RC2/

### 3) Versions available to choose from the UI

Only **the latest patch versions for each minor version** will be displayed on the dropdown list.

<img width="276" alt="dropdown" src="https://github.com/user-attachments/assets/f709a77c-4376-4da7-ad60-5e8874cbbeb8">

Is this something we imagine?
Or do we also need v3.0 (v3.0.0) in the dropdown as well?

(for v2, we only have v2.3 and v2.2.2)

----

Feel free to suggest something else. Comments will inform changes to PR #1015. Thank you.

Note: Since, from the above settings, "v3.0" will be use as an alias, if we still like to get access to the original v3.0 (v3.0.0) content, we can apply PR #994 to republish v3.0 as v3.0.0.

----

Additional requirements

- #1069

**Comment by kestewart** [comment]
Discussed on the tech call, and asking the steering committee to advise.

**Comment by bact** [comment]
Related issue on redirections

- https://github.com/spdx/spdx-spec/issues/1060 may related with the redirects at https://spdx.org

**Comment by goneall** [comment]
Decision - 3.0 will redirect to the latest.
