### ISSUE TITLE
Add weakness enumeration to SPDX

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#102]
In the SPDX general meeting on 6 Dec 2018, Mark Baushke requested we add the weakness enumeration in the SPDX security data: https://cwe.mitre.org/

**Comment by kestewart** [comment]
Based on discussion in weekly call,  defering this to 3.0 so it aligns better with base + security profile discussions.

**Comment by goneall** [comment]
@jeff-schutt @puerco - is this in the current security profile?  If not, should we add this to a 3.1 milestone?

**Comment by jeff-schutt** [comment]
@goneall CWE is not there today, and it seems like a reasonable recommendation. Many security advisories link the CVE to a CWE. We can investigate further in the security profile.

**Comment by rnjudge** [comment]
Per discussing in the security call today, pushing this to 3.1
