### ISSUE TITLE
Remove clause/section numbering

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-spec#1023]
There should be no numbering on chapter and section headers.

It is automatically added while creating the PDF.

**Comment by bact** [comment]
If we still like to make a reference to a specific section,
an HTML anchor `<a name="..."></a>` is need to be either added manually or generated automatically to each section.

Generating automatically (numbers will not be in source file):
- Pros: Can be consistency easily, less work
- Cons: Not transparent. A human editor who like to make a reference to a section in a chapter needs to generate that chapter first to get an HTML anchor name

Adding manually (numbers will be source file):
- Pro: Transparent. A human editor can just look at the source file and get immediately the HTML anchor name
- Cons: Tedious and prone to error

Note that MkDocs can generate these HTML anchor for us, but it may not work in a number of documents if there's no numbering. MkDocs generates the anchor from the heading name. Some document has multiple headings with the same name (like "Purpose", "Guideline"). But there can be a workaround by renaming those headings to be unique.
