### ISSUE TITLE
Update Appendix I "Request New License" link

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#103]
The SPDX website is being updated to point to the license-list-XML repo's CONTRIBUTING file for all "Request New License" links. This is to ensure consistency for new SPDX participants re: how to request or contribute a new license. This is being tracked in https://github.com/spdx/license-list-XML/issues/680.

Appendix I of the spec still includes a copy of (an older version of) the license list. There's been some discussion of removing it from a later version of the spec. Until then, while it remains in the spec, the "Request New License" link at the top of Appendix I should be updated to point to https://github.com/spdx/license-list-XML/blob/master/CONTRIBUTING.md

**Comment by swinslow** [comment]
I can take this one on, I just don't have the ability to assign this to myself  =)

**Comment by jlovejoy** [comment]
made PR for this here: https://github.com/spdx/spdx-spec/pull/104

**Comment by tsteenbe** [comment]
Fixed in master see https://github.com/spdx/spdx-spec/blob/master/chapters/appendix-I-SPDX-license-list.md
