### ISSUE TITLE
Fix URL in Conformance 

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#1042]
This URL in [Conformance chapter](https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/conformance.md) is not exist
https://github.com/spdx/spdx-spec/blob/master/schemas/spdx-schema.json

**Comment by kestewart** [comment]
@goneall to identify location.

**Comment by goneall** [comment]
Release location is https://spdx.github.io/spdx-spec/v3.0/model/schema.json
