### ISSUE TITLE
Update bin/check-examples.sh to v3.0.1

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#1049]
[bin/check-examples.sh](https://github.com/spdx/spdx-spec/blob/c859ce1c1249de37e3550cd86092517f39fa405d/bin/check-examples.sh) uses `https://spdx.org/rdf/3.0.0/spdx-model.ttl`.

Needs to update to 3.0.1 one, once it is ready.

**Comment by Prasang023** [comment]
Hi @bact @kestewart , I was thinking if this repo is open to contributions from other members also, like me, and if yes, I would really like to start contributing to the project. Can you tell me what public channels do we use to connect apart from mail groups if there is something.

**Comment by bact** [comment]
@Prasang023 please refer to the Contributing guideline at https://github.com/spdx/spdx-3-model/blob/main/Contributing.md
