### ISSUE TITLE
Website navigation should not capitalize

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-spec#1062]
It seems that, when the title is a single word, the navigation produced by `mkdocs` capitalizes the word.

This results to properties that are a single word to get a wrong entry.

**Comment by bact** [comment]
Propose https://github.com/spdx/spec-parser/pull/140 to fix this.

**Comment by zvr** [comment]
The unwanted behavior seems to be hard-wired in `mkdocs`:

https://github.com/mkdocs/mkdocs/blob/f12315d78fcef6b6d68bddfc03443b66e0516f7a/mkdocs/structure/pages.py#L258-L260

So we'll have to do a work-around, like the one Art proposed.

**Comment by bact** [comment]
Too many (unwanted) magic.
