### ISSUE TITLE
Update license-list-XML URLs to a versioned one

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#1070]
<s>Today the branch name in https://github.com/spdx/license-list-XML has changed from `master` to `main`.</s>

There's at least two refs to unversioned ones, in the [SPDX License List matching guidelines](https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/annexes/license-matching-guidelines-and-templates.md)

- https://github.com/spdx/license-list-XML/blob/master/schema/ListedLicense.xsd
- https://github.com/spdx/license-list-XML/blob/master/DOCS/license-fields.md

Note that a link to license-list-XML repo in [licenseXml](https://github.com/spdx/spdx-3-model/blob/main/model/ExpandedLicensing/Properties/licenseXml.md) property in spdx-3-model repo is already a versioned one, as it was updated with https://github.com/spdx/spdx-3-model/pull/819

**Comment by bact** [comment]
@swinslow Does it ok to use v3.24.0 link https://github.com/spdx/license-list-XML/blob/v3.24.0/schema/ListedLicense.xsd in the spec ? Thank you

**Comment by swinslow** [comment]
The branch name change in license-list-XML to main occurred in 2022, see https://github.com/spdx/license-list-XML/issues/1403

I thought the team had already decided in https://github.com/spdx/spdx-3-model/pull/819 to point to a specific branch version of that file?

In that spdx-3-model thread I noted that the license list version is going to change over time, so I'll defer to the tech team on whether they want to point to the main branch or whether they prefer to point to a specific version. As of this moment, 3.24.0 is the most recently released version of the license list. 3.25.0 is likely to be released within the next couple of days, but it hasn't been yet.

**Comment by bact** [comment]
@swinslow The GitHub UI shows me the light blue notification this afternoon that the repo name is changed so I was thought that it just happened. Sorry for my misunderstanding.

I request your review in the PR #1071. Will comments more there, but note that I'm willing to update the PR to accommodate the latest possible release of license-list-XML.

**Comment by bact** [comment]
I see, the GitHub is smart enough to redirect https://github.com/spdx/license-list-XML/blob/master/DOCS/license-fields.md to https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md when I tried to check the former URL. And it also notifies me about it. I wasn't aware that it's a notification about the long past. Sorry again.

![Screenshot 2024-08-13 at 18 43 46](https://github.com/user-attachments/assets/64b1f604-cfd0-46a2-90dd-3473e95dce0b)

I will keep this issue open since we have to update it anyway, whether to `main` or to v3.24.0 or to v3.25.0.
