### ISSUE TITLE
SPDX and RDF Ontology is a 404

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#1078]
In page: https://spdx.github.io/spdx-spec/v3.0.1-draft/references/

SPDX and RDF Ontology, http://spdx.org/rdf/ontology/spdx-3-0-1

gives a 404:
```
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: rdf/ontology/spdx-3-0-1
    RequestId: H05SB50RGG8X068N
    HostId: RcYfUmdDlYRe+/K70WzAa0yj77eFShl21W1RGV51bOTnySWjZa7RbuiuJf8jzxykBpWmkMVlCS8=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html
```

**Comment by zvr** [comment]
Sure, it's not published yet.
It's a chicken-and-egg problem, what gets published first ;-)

**Comment by goneall** [comment]
@zvr - did you want to generate the web pages for the 3.0.1 release or would you like me to?

**Comment by goneall** [comment]
http://spdx.org/rdf/ontology/spdx-3-0-1 now redirects to https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Core/ - which is the same redirect used if you go to https://spdx.github.io/spdx-spec/v3.0.1/model.
