### ISSUE TITLE
"SWHID 	SoftWare Heritage persistent IDentifiers" should be "SoftWare Hash IDentifiers"

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#1080]
In page https://spdx.github.io/spdx-spec/v3.0.1-draft/symbols/

`SWHID 	SoftWare Heritage persistent IDentifiers` should be `SoftWare Hash IDentifiers`.

The meaning has changed to make it more generic.

See https://www.swhid.org/

**Comment by bact** [comment]
Thank you. Please review the fix in #1087
