### ISSUE TITLE
"PURL 	Package Uniform Resource Identifier" should be "Package URL"

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#1083]
In page In page https://spdx.github.io/spdx-spec/v3.0.1-draft/symbols/

`PURL 	Package Uniform Resource Identifier` should be `PURL Package URL`

See https://spdx.github.io/spdx-spec/v3.0.1-draft/annexes/pkg-url-specification

**Comment by bact** [comment]
Thank you. Please review the fix in #1087

**Comment by goneall** [comment]
Thanks @vargenau for all the good catches and thanks @bact for the quick fix.
