### ISSUE TITLE
Annex A has only Overview, no content

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#1084]
https://spdx.github.io/spdx-spec/v3.0.1-draft/annexes/changes-from-previous-iso/

Annex A has only Overview, no content listing the changes.

**Comment by zvr** [comment]
Yes, @vargenau . The idea is to add this content before submitting it to ISO, as it describes the differences between two different versions of the standard.

**Comment by vargenau** [comment]
@zvr 
I understand that.

It should be a subset of https://spdx.github.io/spdx-spec/v3.0/annexes/diffs-from-previous-editions/ 

Why cannot we include it now?

**Comment by vargenau** [comment]
@bact 
https://github.com/spdx/using/blob/main/docs/diffs-from-previous-editions.md describes the difference between **2.3** and 3.0.

If we want to list here the differences between the current ISO standard and the next one, we should consider **2.2.1** and 3.0.1.

**Comment by bact** [comment]
Agree on the version numbers. But the actual content that was copied over to the spdx/using repo is post-3.0.0.

**Comment by goneall** [comment]
We're going to track the Annex A in #999 

Closing this issue - feel free to add any comments to #999
