### ISSUE TITLE
AdditionRef typo in spec document

### ISSUE THREAD

**Issue by brokenjpl** [spdx/spdx-spec#1086]
Attached is the diff for the patch. I didn't have permission to submit a PR.

Typo in the following paragraph:

```
The <addition-expression> can be either a <license-exception-id> from the SPDX License List, or a user defined addition reference in the form ["DocumentRef-"(idstring)":"]"AdditonRef-"(idstring)
```
ref: https://spdx.github.io/spdx-spec/v3.0/annexes/SPDX-license-expressions/

[typo.patch](https://github.com/user-attachments/files/16713705/typo.patch)

**Comment by bact** [comment]
Thank you. Please see the fix in #1087
