### ISSUE TITLE
[SPDX 3.0.1] AbstractClass is prefixed with <http://spdx.invalid./>

### ISSUE THREAD

**Issue by ilans** [spdx/spdx-spec#1089]
In spdx-model.ttl:
@prefix ns7: <http://spdx.invalid./> .
ns7:AbstractClass a owl:Class .
etc...

@zvr Assuming that's invalid :grin:

**Comment by goneall** [comment]
@zvr - If I recall, this is related to a request I made to distinguish abstract classes - do you recall the details?

**Comment by bact** [comment]
This note from shacl2code may related to this issue
https://github.com/jpewdev/shacl2code/?tab=readme-ov-file#abstract-classes

**Comment by zvr** [comment]
It's a valid URL that is guaranteed to not resolve to anything.

This is exactly what is needed for a pseudo-class that is not part of the model but simply conveys some meta-information needed by code generators (not really the RDF part).

**Comment by bact** [comment]
@ilans does it ok to close this? thanks

**Comment by goneall** [comment]
Note: the abstract class was previously solved with adding the property `https://jpewdev.github.io/shacl2code/schema#isAbstract` to abstract classes.

**Comment by bact** [comment]
A PR related to this: https://github.com/spdx/spec-parser/pull/158

**Comment by goneall** [comment]
Fixed with https://github.com/spdx/spec-parser/pull/158#event-15335827740
