### ISSUE TITLE
Changes needed for new branch structure

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#1092]
From the [2024-08-14 tech discussion on spec publishing](https://github.com/spdx/meetings/blob/main/tech/2024/2024-08-14.md#specification-publishing) and the previous discussion on [translations on 2024-06-11](https://github.com/spdx/meetings/blob/main/tech/2024-06-11.md#translations), we agreed to rename the "under development" branch to main.  This will likely break the CI.

We should create a PR for CI updates, then rename the branch before merging.

We also need to document exactly what the changes are.

We also update README and/or CONTRIBUTING file

**Comment by goneall** [comment]
From the tech call on 5 November 2024, below are the specific changes we will make to the branches:

  - Rename the currently under development branch "Development/v3.0.1" to "develop"
  - Change default branch to develop
  - For each branch under Development, create a branch under Support with exactly the same commit history of that Development branch with the name support/X.Y then delete the Development branch - e.g. create a support/2.3 with the same commit history as Development/v2.3 then delete the branch Development/v2.3 - Note this should be the same as renaming Development/v2.3 to support/2.3


@zvr @sbarnum - please review the above comment for accuracy

**Comment by bact** [comment]
With this setup, it will also be possible to publish new changes in "develop" immediately to a "staging" website; while keeping the "production" website to only be published from a tag in "main".

**Comment by goneall** [comment]
Discussed on tech call 12 Nov 2024 - agreed to branch strategy

@bact will create a pull request to update the workflows
@goneall will merge the workflow updates and rename the branches

**Comment by goneall** [comment]
Branches have been renamed per the [above comment](https://github.com/spdx/spdx-spec/issues/1092#issuecomment-2457885443).

Closing issue.
