### ISSUE TITLE
Artifact and SoftwareArtifact are missing from v3.0.1 schema

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#1118]
The v3.0.1 schema is generated by shacl2code 0.0.14 (latest version, released 10 Sep 2024).

Not sure if this is an expected behaviour or not.

--

**v3.0.0 schema - has `Artifact` and `SoftwareArtifact`**
https://spdx.github.io/spdx-spec/v3.0.0/rdf/schema.json
<img width="952" alt="v3.0.0 schema" src="https://github.com/user-attachments/assets/19b3b11a-b07f-4491-80e9-ff9a8572defb">

--

**v3.0.1 schema - does not has either  `Artifact` or `SoftwareArtifact`**
https://spdx.github.io/spdx-spec/v3.0.1/rdf/schema.json
<img width="959" alt="v3.0.1 schema" src="https://github.com/user-attachments/assets/8f083256-2af3-4193-b199-a221b3442a10">

--

This may related to the [failure of example validation](https://github.com/spdx/spdx-spec/actions/runs/10806923739/job/29976664694?pr=1107):

(error message from check-jsonschema)
> Checking ./bin/../examples/jsonld/package_sbom.json
Failure resolving $ref within schema
>
> _WrappedReferencingError: PointerToNowhere: '/$defs/Artifact' does not exist within {
...

**Update:** Re-run and the previous check is already passed; but got a new [different failure instead](https://github.com/spdx/spdx-spec/actions/runs/10806923739/job/29984044905):

(check-jsonschema is ok now)
> Checking ./bin/../examples/jsonld/package_sbom.json
 ok -- validation done
 The following files were checked:
  ./bin/../examples/jsonld/package_sbom.json

(error message from pyshacl)
> Validation Report
Conforms: False
Results (4):
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:class ns2:CreationInfo ; sh:maxCount Literal("1", datatype=xsd:integer) ; sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:BlankNodeOrIRI ; sh:path ns2:creationInfo ]
	Focus Node: ns2:NoneElement
	Result Path: ns2:creationInfo
	Message: Less than 1 values on ns2:NoneElement->ns2:creationInfo
...

**Comment by bact** [comment]
The cause of validation error may be about the cardinality of non-vocabulary named individuals
- see: https://github.com/spdx/spec-parser/issues/153

**Comment by goneall** [comment]
> I believe removing the `Artifact` and `SoftwareArtifact` was intentional. From what I can tell, all abstract classes have been removed.
> 
> The current error is likely unrelated - perhaps we should open a separate issue to track.

I see @bact has already opened a separate issue.

**Comment by bact** [comment]
I will close this one. Thanks Gary.
