### ISSUE TITLE
A 2.x field is referenced in 3.0.1 License List matching guidelines (License Information in File)

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#1125]
In the SPDX License List matching guidelines, there is a text:

> To ensure consistent results by different SPDX document creators when matching license information that will be included in the License Information in File field.

But that *"License Information in File"* field, or *licenseInfoInFiles*, has been removed since 3.0 (see https://github.com/spdx/using/blob/main/docs/diffs-from-previous-editions.md#licenseinfoinfiles )

Any suggestion to revise the text please? Thank you.

(Found during the drafting of v3.0.1-v2.2.1 diffs)

**Comment by zvr** [comment]
I propose changing 

> license information that will be included in the License Information in File field.

to 

> license information that will be included in SPDX data.

@swinslow should probably review the PR
