### ISSUE TITLE
JSON files structure inconsistencies with spec 2.1

### ISSUE THREAD

**Issue by xavierfigueroav** [spdx/spdx-spec#114]
[SPDX Specification 2.1](https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf) states that a SPDX Identifier Reference field is mandatory in Annotations. But [the json example file](https://github.com/spdx/spdx-spec/issues/55#issuecomment-413063219) does not contain it.
This should be solved/discuss or the example never has to be follow as a guide to write proper SPDX documents.

There may be more inconsistencies. I would like they are mentioned here and this conversation gets expanded.

Keep in mind that YAML files follow the same structure and python tools will support JSON and YAML formats soon, so many invalid documents might wander out there.

**Comment by xavierfigueroav** [comment]
Although the following is not against the spec, it is related to the structure.

`documentDescribes` object is currently an array of json objects. These objects have only one of these keys: "File" or "Package". Example:
`documentDescribes: [ { "File": {} }, { "Package": {} } ]`

Since there may be many of those objects, dealing with them from code can be tiring because you have to "ask" whether an item of the array has the key "File" or "Package" to know how to treat it.
I suggest the following approach:

`documentDescribes: { "packages": [ <here package objects> ], "files": [ <here file objects> ] }`

**Comment by goneall** [comment]
@xavierfigueroav Can you split the second comment into a separate issue?  It may involve a different solution and a different discussion thread.  In a way, they are related since we can have documentDescribes could just be an array of SPDX ID's and the SPDX ID's could be looked up later and a similar solution used for the annotations.

I'm adding a tag `new formats` to allow us to group together all the issues related to JSON, YAML and XML formats.

**Comment by xavierfigueroav** [comment]
JSON, YAML and XML example files do not contain namespace field, which is required.

**Comment by goneall** [comment]
Document namespace is present: https://github.com/spdx/spdx-spec/blob/fd555f596c0b31cc13de5834b1f1a53614474132/examples/SPDXJSONExample-v2.0.json#L20

The name, however, is `spdxDocumentNamespace` - it needs to be changed to `documentNameSpace` to be consistent with the spec.

**Comment by goneall** [comment]
Resolved with PR #197
