### ISSUE TITLE
JSON files structure design

### ISSUE THREAD

**Issue by xavierfigueroav** [spdx/spdx-spec#115]
[This file](https://github.com/spdx/spdx-spec/issues/55#issuecomment-413063219) is being used as an example for a json representation of SPDX documents. Reviewing and discussing its structure would help to ensure one of the SPDX key ideas: 
> Human and machine readable formats

Keep in mind that YAML files follow the same structure and python tools will support JSON and YAML formats soon, so this issue becomes more important now.

If you are more interested in ensuring that the json format follows properly the [SPDX Spec. 2.1](https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf), have a look at #114

**Comment by xavierfigueroav** [comment]
`documentDescribes` object is currently an array of json objects. These objects have only one of these keys: "File" or "Package". Example:
`documentDescribes: [ { "File": {} }, { "Package": {} } ]`

Since there may be many of those objects, dealing with them from code can be tiring because you have to "ask" whether an item of the array has the key "File" or "Package" to know how to treat it.
I suggest the following approach:

`documentDescribes: { "packages": [ <here package objects> ], "files": [ <here file objects> ] }`

**Comment by goneall** [comment]
I agree with the proposed approach.  If we take this approach, please [open an issue on the SPDX Tools](https://github.com/spdx/tools/issues/new).

**Comment by goneall** [comment]
Consensus on 15 Oct tech call: `documentDescribes: { "packages": [ <here package objects> ], "files": [ <here file objects> ] }`

Another question is if this is needed for JSON and YAML.  Keep in for now, we can revisit after discussing relationship.

**Comment by goneall** [comment]
Question on if documentDescribes implicitly creates a relationship.  Currently, documentDescribes is not a property of a document. Adding this as a required property would create an incompatibility.  Consensus on tech call 19 Nov was to implicitly create the relationship between the document and the elements it describes.

**Comment by goneall** [comment]
With the resolution of #189 the document describes will only have the ID, so we should not need separate package and file properties.  For example:

`"documentDescribes" : [ "SPDXRef-File", "SPDXRef-Package" ]`

**Comment by goneall** [comment]
Resolved with PR #197
