### ISSUE TITLE
The v3 specification is hard to consume in a integrator point of view

### ISSUE THREAD

**Issue by brlin-tw** [spdx/spdx-spec#1165]
The structure of the v3 specification is radically different from v2, and I found it hard to comprehend when I tried to integrate SPDX into my projects.

For example, refer to the [Clause 10: Other Licensing Information Detected](https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/) page in v2.3.0, the only place I can find a similar information in v3 is [Annex B. SPDX license expressions](https://spdx.github.io/spdx-spec/v3.0.1/annexes/spdx-license-expressions/), which is (IMHO) less human-readable due to the usage of ABNF and less relatable examples(e.g. LicenseRef-Whiskeyware).

The Model portion of the v3 specification seems to be developer/specification implementor-oriented information and, should be placed at the farther end of the specification, or an introductory text on how different kinds of audiences should consume this specification should be placed at the start of the specification(e.g. in the [Introduction](https://spdx.github.io/spdx-spec/v3.0.1/front/introduction/) chapter).

**Comment by zvr** [comment]
FYI:

We kept this repository for developing the actual specification.

We publish more "how-to" type of documents in the repository https://github.com/spdx/using -- where we plan to add more, if need be.

**Comment by brlin-tw** [comment]
@zvr 

Thanks for the information!  Feel free to close this issue if you feel there's nothing need to be done in this repository.
