### ISSUE TITLE
Expand Possible Relationships (section 7.1) between elements to include more use cases.

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#12]
(spec 7.1 needs to be expand - which useful ones are missing & definitions. 

- Yev would like to see inverse of **EXPANDED_FROM_ARCHIVE**,   Archive of.  
- Thomas  would like to add following relationships to better define context of license finding:
   - **EXAMPLE_OF** - Source code included with OSS package for example purposes. 
   - **TEST_TOOL_OF** - To distinguish test frameworks such as jUnit from source dependencies. 
   - **TOOL_OF** or **DEV_TOOL_OF** - To indicate tooling included in OSS package for development or utility purposes which are not used to build a package. Think git commit hooks, FTP upload scripts, etc.
- Clarifying prerequisite description in existing spec (2.2?) is also needed for target system
- Others to comment… provide input.

**Comment by goneall** [comment]
Discussed on tech call 12 June 2018: 
* EXPANDED_FROM_ARCHIVE - Agreed to add
* EXAMPLE_OF - Agreed to add
* TEST_TOOL_OF - Agreed to add
* DEV_TOOL_OF - Agreed to add

Need pull request to add to the spec.

Assigning to @tsteenbe to add a pull request for the 2.2 release.
