### ISSUE TITLE
Question: no field for funding?

### ISSUE THREAD

**Issue by vsoch** [spdx/spdx-spec#121]
Hey SPDX! I have a quick question - I don't see any kind of fields to designate a funder / funding for a package. Am I searching for the wrong term? It seems like the source of support for a package would be something important to have. Thanks!

**Comment by kestewart** [comment]
Hiya vsoch - Funding to support SPDX can be contributed at:
https://funding.communitybridge.org/projects/7083b4ba-d32a-4e51-a225-42d28e58358d

Our goals for the funding are listed there as well. 

Thanks, Kate

**Comment by vsoch** [comment]
hey @kestewart thanks, but I you didn't answer my question. I'm looking for a *field* in the specification where a user (of the specification) could specify a funder. As an example, zenodo.json has a section for "grants" -> https://github.com/datalad/datalad/blob/master/.zenodo.json#L80

Thanks!
