### ISSUE TITLE
Add definition of Packages

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#125]
Based on call in 2019-05-28 tech team call, there was discussion about the absence in the spec of a formal definition of what is meant by a "Package". Submitting this issue as a working draft to address this by adding a definition to section 3 of the spec.

This is relevant both for use within SPDX itself, as well as for e.g. the (awesome) work that the FSFE REUSE project is doing. (cc @carmenbianca)

Here's a first attempt to summarize what was discussed on the tech team call today. Input and criticism welcome!

(cc @kestewart @goneall @nishakm)

= = = = =

In SPDX, a 'Package' refers to any unit of content that can be associated with a distribution of software. Typically, a Package is composed of one or more files. An SPDX document may, but is not required to, provide details about the individual files comprising a Package (see the "File Information" details in section __ below).

Any of the following non-limiting examples can be represented in SPDX as a Package:
* a tarball, zip file or other archive
* a directory or subdirectory
* a dependency within a programming environment or ecosystem (e.g., a Python package, a Golang module, ...)
* a container image, and/or each image layer within a container image
* a collection of one or more sub-packages
* a Git repository snapshot from a particular point in time

Note that some of these could also be themselves represented in SPDX as a File as well.

**Comment by swinslow** [comment]
Recommendations from 2019-06-04 tech team call:

- "can be represented..." => "may be (but are not required to be) represented..."
- title section: "What does 'Package' mean in the context of SPDX?"
- change "dependency" bullet point to: "a separately-distributed piece of software which another Package or File uses or depends upon (e.g., ...)"
- note at the bottom that Relationship elements can be used to indicate relationships between Packages, such as dependency relationships

**Comment by carmenbianca** [comment]
> Note that some of these could **also** be themselves represented in SPDX as a File **as well**.

Double "also" :)

**Comment by swinslow** [comment]
Oops... good point, I’ll fix that. Thanks :)

**Comment by swinslow** [comment]
PR added at #129 -- feel free to take a look!
