### ISSUE TITLE
Define  SPDXREF-NONE & SPDXREF-NOASSERTION 

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#137]
We already have SPDXREF-DOCUMENT to refer to the entire SPDX document, and it can be used in relationships. 

There are some use cases that have been flagged in the [NTIA workgroup](https://docs.google.com/document/d/1YzpLd8VtLIrAQtULZhRf6ZENqmaZ-w71wfhQdpNSpcs/edit#heading=h.f9iwzux6yxmj),  where people want to refer to the "known unknowns" in RELATIONSHIPS.     

By introducing SPDXREF-NONE we can model that an SPDX element (package/file/snippet) has no other elements connected by some relationship to it.

By introducing SPDXREF-NOASSERTION we can model that the author is not asserting where other elements are connected by relationships to it or not.  ie.  There could be some, but the author is not asserting one way or another. 

Examples:    
Relationship:  SPDXREF-SPDXRef-CompressionEng-v3.1 CONTAINS SPDXREF-NONE 
Can be used to explicitly indicate there are NO dependencies

Relationship: Relationship:  SPDXRef-Buffer-v2.2 CONTAINS SPDXREF-NOASSERTION
Can be used to explicitly indicate its not clear if there are dependencies on this package or not.

**Comment by kestewart** [comment]
Review NTIA Framing,  and align with the terminology.

**Comment by kestewart** [comment]
Moving this to 3.0,  and will refine further there.

**Comment by kestewart** [comment]
Move this back to 2.2, as @tsteenbe has a use case with repository managers that trim dependency trees, and this mechanism would enable a way of capturing this knowledge.

**Comment by goneall** [comment]
Would these only be used on the right hand side of relationships?  If so, I can see how we can make this work in the tooling, but it may be a challenge to reflect this in the UML model accurately.

Is there any possibility this would break existing documents since we are introducing reserved ID's?

**Comment by swinslow** [comment]
I don't have a particular preference either way on the overall issue, but I think @goneall is right. Existing SPDX 2.1 or earlier documents could define `SPDXRef-NONE` or `SPDXRef-NOASSERTION` to point to an existing element in the document, and this would change the definition of those identifiers, so it seems that it would break compatibility.

**Comment by kestewart** [comment]
Its unlikely they've used NONE and NOASSERTION,  but the point is valid.   How about we introduce a new character permitted in IDSTRING to deliminate these values.   ie. "*"
so where [idstring] is a unique string containing letters, numbers, *, ., and/or -.

And then we'd use SPDX-*NONE*,   SPDX-*NOASSERTION* as the reserved values, which can't exist in 2.1 (as * isn't valid).

That work for you @goneall, @swinslow  ?

**Comment by goneall** [comment]
What if we loose the prefix SPDXRef-.  This would be consistent with how we treat the license ID's and would resolve the incompatibility.

Example:

```
SPDXRef-Buffer-v2.2 CONTAINS NOASSERTION
```

**Comment by swinslow** [comment]
+1 on omitting SPDXRef- for these, but I don't have a strong preference any which way.

**Comment by kestewart** [comment]
Ok by me.  :-)  Will go ahead with that for the PR.

**Comment by kestewart** [comment]
Discussed on the call,  general agreement with going forward.

Steve raises the point that we should make it clear that use of this is optional, and not required.

**Comment by kestewart** [comment]
see pull request #221
