### ISSUE TITLE
JSON: duplicate keys specVersion and spdxVersion

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#143]
Per the tech team call 2019-09-17, this is one of several issues I'll file that relate to the proposed JSON format file. Specifically, the example in the `new-formats` branch at https://github.com/spdx/spdx-spec/blob/new-formats/examples/SPDXJSONExample-v2.0.json which is from the Java tools' prototype for a JSON format.

The prototype version there has two fields with the same content:
* line 3: `"specVersion" : "SPDX-2.0"`
* line 10: `"spdxVersion" : "SPDX-2.0"`

I think that only one of these is needed. I'd suggest keeping `spdxVersion` since that mirrors the tag-value format, and removing `specVersion`.

**Comment by goneall** [comment]
This looks like an early inconsistency between RDF and tag/value.  I would propose we pick one and deprecate the other across all formats.

Since tag/value is used more that RDF, going with spdxVersion would be least disruptive.

**Comment by goneall** [comment]
This was fixed by PR #149   - closing the issue.
