### ISSUE TITLE
PackageSupplier: Use <> instead of parens for optional email?

### ISSUE THREAD

**Issue by wking** [spdx/spdx-spec#15]
The 2.1 spec [has][1]:

> "Person:" person name and optional "("email")"

and:

> PackageSupplier: Person: Jane Doe (jane.doe@example.com)

However, it would seem more usable if we lean on RFC 2822 and use `<>` to set off the address.  Borrowing from [RFC 2822's rules for `display-name` and `angle-addr`][2], the [ABNF][3] for the `PackageSupplier:` would be would be:

```abnf
package-supplier = "PackageSupplier:" 1*(person / organization)
person = "Person:" name-optional-addr
organization = "Organization:" name-optional-addr
name-optional-addr = display-name [angle-addr]
```

[1]: https://spdx.org/spdx-specification-21-web-version#h.3as4poj
[2]: https://tools.ietf.org/html/rfc2822#section-3.4
[3]: https://tools.ietf.org/html/rfc5234

**Comment by kestewart** [comment]
This will be breaking backwards compatibility, so at a minimum it would be 3.0.    Can you help us understand if doing this will help adoption or support other formats?  (discussed in tech call)

**Comment by wking** [comment]
On Tue, Aug 29, 2017 at 05:23:47PM +0000, Kate Stewart wrote:
> This will be breaking backwards compatibility, so at a minimum it
> would be 3.0.

For best compat, we'd want to add the new <> form as soon as possible,
deprecate the () form but keep it supported, and drop the () form in
3.0.  That way folks who are writing 2.1+ compliant files could start
writing <> now.

I'm assuming that the 2→3 bump protects writers, not readers, since
2.1 readers would not recognize the new-in-2.2 (or whenever) <> form.
But they won't recognize new-in-2.2 short identifiers and such either,
so I think the unrecognized <> is ok.

> Can you help us understand if doing this will help adoption or
> support other formats?  (discussed in tech call)

I don't have code I can link or projects that would pick up SPDX if
this changed happened.  It's just “why invent our own notation when
there's a commonly-used, well-specified notation that already coveres
this concept?”.

**Comment by goneall** [comment]
With 3.0, this is now a structured object, so this is now resolved.
