### ISSUE TITLE
Add new relationships to better capture dependency scopes

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#154]
Continuation of https://github.com/spdx/spdx-spec/issues/12 I would like to add new relationships:

- DEPENDENCY_OF -> Use when package B is a dependency of package A 
- BUILD_DEPENDENCY_OF -> Use when package B is a build dependency of package A e.g. used in building the code of the project.
- DEV_DEPENDENCY_OF -> Use when package B as development dependency of package A e.g. used in the development of the code of the project. 
- TEST_DEPENDENCY_OF  -> Use when package B as test dependency of package A e.g. used for testing of the project.

Above relationship will help us in OSS Review Toolkit capture the information we retrieve from the various package manager better in SPDX.

**Comment by swinslow** [comment]
@tsteenbe Personally I like this, and I like the names you're proposing  :)  To poke at this a bit, though:

* DEPENDENCY_OF -- is this different from the existing PREREQUISITE_FOR?
* BUILD_DEPENDENCY_OF -- different from BUILD_TOOL_OF?
* TEST_DEPENDENCY_OF -- different from TEST_CASE_OF? (I think it is, but we might want to clarify why)

**Comment by kestewart** [comment]
@swinslow -  I like the ones that @tsteenbe is proposing, and there are some subtleties rhere.

BUILD_DEPENDENCY_OF could be different from BUILD_TOOL_OF. and example might be a config file. 

TEST_DEPENDENCY_OF could be more than just a TEST_CASE_OF,  things like tool running the test cases.  

DEPENDENCY_OF... hmm,  I'm working to come up with a good counter why it couldn't be PREREQUISITE_FOR,  other than maybe something for a "post-processing"?   Thomas - any examples come to mind here?

**Comment by tsteenbe** [comment]
PREREQUISITE_FOR is for more like you need to install you software on your system before you can can use it whilst all DEPENDENCY_* all all actively resolvable by the package manager.

DEPENDENCY_OF -> RUNTIME_DEPENDENCY to indicate this dependency is needed when executing the application or post-processing.

**Comment by tsteenbe** [comment]
Agreement is that for 2.2 we leave PREREQUISITE_FOR unchanged, something to revisit for 3.0

**Comment by tsteenbe** [comment]
On second I would like to keep DEPENDENCY_OF but change its meaning from my earlier proposal. Motivation: in Python there only one dependency scope so any tool need a way to describe a "generic" dependency relationship.

- DEPENDENCY_OF -> Use when package B is a dependency of package A but it's unclear what type of dependency relation is.
- BUILD_DEPENDENCY_OF -> Use when package B is a build dependency of package A e.g. need as part of the compiled code of the project and include in the resulting build artifact.
-  DEV_DEPENDENCY_OF -> Use when package B as development dependency of package A e.g. used in the development of the code of the project. Example:  a package.json for a Node (Javascript) project defines 'eslint' a code linter in the 'devDependencies' scope as it used to do a static analysts of the code to detect problems like incorrect indentation.
-  RUNTIME_DEPENDENCY_OF  -> Use when package B is dependency of package A that is needed when executing A. Example: a pom.xml file for a Maven (Java) project defines JUnit as in the "runtime" scope meaning it's a dependency the project needs when the project is executed. 
-  TEST_DEPENDENCY_OF -> Use when package B is a test dependency of package A e.g. used for testing of the project. Example: a pom.xml file for a Maven (Java) project defines JUnit as in the "test" scope meaning it's a test dependency the project needs to executes (unit) tests for the project

**Comment by swinslow** [comment]
This is helpful, though as usual I have some more comments / questions  :)

* DEPENDENCY_OF: makes sense to keep this as a "generic" dependency relationship, though I'd note that I _think_ that makes this identical to PREREQUISITE_OF. Perhaps that's fine for 2.2, and perhaps we should deprecate the PREREQUISITE relationships in 3.0, but if it's intended to have a different meaning then we should flesh out what that is.

* BUILD_DEPENDENCY_OF: I had thought I'd understood this, but now I'm not sure. It sounds like this is a combination of the v2.1 meanings for BUILD_TOOL_OF ("A is used to build B") and CONTAINED_BY ("B contains A"). Is that accurate, or is there something else I'm missing?

The other three (DEV_, RUNTIME_ and TEST_) look great to me.

**Comment by kestewart** [comment]
From discussion in call,   some tools are not clear what type of dependency it is.   
Discussion ensued ending up in clarification prerequisite of that may not be explicitly stated (but may include dependencies),  examples are:  info from a readme , version of kernel, etc. 

Steve is ok for merging for 2.2.   (all others on call were fine too!)
 
Prerequisite_of - leave definition as is.  
Dependency - is a prerequisite that may be explicitly stated 

The  PR needs to explain this difference,
