### ISSUE TITLE
Use tag-value to simplify enums for JSON, YAML and XML

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#155]
Looking at the [JSON](https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.0.json) and YAML(https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXYAMLExample-2.0.yaml) examples and noticed some inconsistency in these files. Sometimes SPDX tag-value is used as a basis whilst in other case RDF/XML.

This seems inconsistent to me. Propose we use the more simplier tag-value values for enums for JSON, YAML and XML formats
 
Examples
[JSON line 27](https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.0.json#L27): "fileTypes" : [ "fileType_source" ] instead of more simpler tag-value "fileTypes" : [ "SOURCE" ]
[JSON line 29](https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.0.json#L29): "algorithm" : "checksumAlgorithm_sha1" -> SPDX RDF, believe the more simpler would be to use “tag-value” e.g. just "algorithm" : "SHA1"
[JSON line 51](https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.0.json#L51) "annotationType" : "OTHER " -> tag-value, for SPDX RDF this would be "annotationType_other"
[JSON line 92](https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.0.json#L92): externalRefs  seem to be based on SPDX RDF
[JSON line 114](https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.0.json#L114): "relationshipType" : "DYNAMIC_LINK"

**Comment by tsteenbe** [comment]
Discussed in the SPDX tech call on November 19, @kestewart  @goneall  @zvr  @swinslow all agreed with this proposal.

**Comment by kestewart** [comment]
Review in call today,  no issues.   Standing by for PR.

**Comment by swinslow** [comment]
@tsteenbe Take a look at #182 -- I think this catches all the appropriate enums for the JSON and YAML examples...
