### ISSUE TITLE
Incompatibility in comment property for license between JSON and RDF/XML

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#158]
We are using JSON formats for the SPDX listed licenses in addition to the RDF/XML formats.

In RDF/XML we use the property name `comment` with the RDFS namespace.

The JSON file uses `licenseComment`.

For examples, see the [Apache JSONLD file](https://spdx.org/licenses/Apache-2.0.jsonld) for the RDF definition and the [straight JSON file](https://spdx.org/licenses/Apache-2.0.json) for the JSON definition.

These fields should be consistent.

**Comment by goneall** [comment]
Propose using `comment`.  Shorter, more consistent with other JSON classes as well as consistent with the RDF.

**Comment by goneall** [comment]
Since fixing this will break something, proposing we address this in SPDX 3.0.

**Comment by kestewart** [comment]
Based on call today,  this can be fixed for the spec in 2.2,  but the license list will be inconsistent and that will be addressed in 3.0

**Comment by kestewart** [comment]
Based on call, we will use comment for JSON in 2.2,  and make XML compatible in future release.   So no change in 2.2 Specification,  and we'll resolve in 3.0.

**Comment by goneall** [comment]
This is resolved in 3.0 - closing
