### ISSUE TITLE
Model XMI cannot be opened

### ISSUE THREAD

**Issue by stevespringett** [spdx/spdx-spec#164]
I've attempted to open the model XMI using two tools that I have access to, both of which support XMI.

Importing using GenMyModel.com does not work. This service supports:
- XMI v1.1 - UML v1.3
- XMI 2.0 - UML v2 (Eclipse)
- XMI (StarUML)

Importing using StarUML v3.2.0 with the XMI v0.9.4 extension installed also does not work. This extension supports:
- XMI v2.0
- XMI v2.1

The XMI extension for StarUML is located here: https://github.com/staruml/staruml-xmi Of relevance is the following statement:

> XMI (XML Metadata Interchange) is for metadata interchange among various software modeling tools. However, XMI functionalities of many tools are not complete or not compliant with XMI standard. Therefore, you need to aware that XMI is not perfect way to interchange data.

It appears the current model was authored with Visual Paradigm and it's likely that the current XMI can only be opened in Visual Paradigm. If XMI is the chosen format to represent the model, then this ticket is to investigate what is required to make the model available in as many tools that support XMI as possible, and to republish the model in a more universally compatible format.

**Comment by goneall** [comment]
I have been trying to find a compatible format between Visual Paradigm and GenMyModel.com

Visual paradigm supports exporting models in XMI 1.0, XMI 1.2, XMI 2.1.  It supports UML 2.0 XMI format.

GenMyModel.com supports import in XMI 1.1 and XMI 2.0.   :(

I would propose switching to GenMyModel for the 3.0 modeling work.

**Comment by stevespringett** [comment]
Ideally, the model could be imported into any UML modeling program. Exported XMI from GenMyModel cannot be opened in StarUML. I don't use Visual Paradigm so don't know if the exported XMI can be imported in that or not.

From my understanding of XMI, simply supporting 2.0 or 2.1 for example between two tools, doesn't imply those two tools would be compatible.

One thing of interest however, is that GenMyModel has an option to make a model 'public' so anyone can view it which is really interesting. I don't know if GenMyModel allows for editing or collaboration of the model.

**Comment by goneall** [comment]
This is no longer in use as of 3.0.

Closing this issue.
