### ISSUE TITLE
Add new relationship FORK_OF

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#169]
To bring SPDX closer to common concepts used by developers I propose to add the FORK_OF relationship to indicate that SPDX Package B was forked from SPDX Package A. 

This relationship give you an easy way to model forks on GitHub, see for example the "forks" of spdx spec in https://github.com/spdx/spdx-spec/network/members.

Aware this new relationship overlaps with the existing DESCENDANT_OF, see FORK_OF as specialization of DESCENDANT_OF that better describes a common practice in the OSS community.

**Comment by kestewart** [comment]
From call:   Concern is introducing more tool specific language,  as well as being a bit of an overloaded term.
