### ISSUE TITLE
Defined file extensions for the various SPDX formats

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#170]
To make it easier for tooling to easily figure out how to parse an SPDX file I propose to define file extensions for the various SPDX formats.

Proposed File Extensions
- .spdx - Use for SPDX doc in tag-value format
- .spdx.json - Use for SPDX doc in JSON format 
- .spdx.rdf - Use for SPDX doc in RDF format
- .spdx.yml - Use for SPDX doc in YAML format
- .spdx.xml  - Use for SPDX doc in XML format

**Comment by goneall** [comment]
Since there can be multiple RDF types (in the future), I would suggest:

.spdx.rdf -> .spdx.rdf.xml

If we want to support turtle, we can use .spdx.rdf.turtle

**Comment by swinslow** [comment]
+1 — I support @tsteenbe's proposal, I think this would be very useful to recommend.

I'm not familiar enough with RDF to weigh in on @goneall's, but it makes sense so I'm also in favor of it  :)

**Comment by kestewart** [comment]
+1 from Kate,  we've needed this.

From discussion on call,  agree go forward with this,  as long gary's point is included.

**Comment by iamwillbar** [comment]
[YAML.org](https://yaml.org/faq.html) recommends the use of .yaml so we should follow that. Otherwise looks good to me.

**Comment by tsteenbe** [comment]
Re-opening ticket https://github.com/spdx/spdx-spec/pull/185/commits/b71378bc256d50df5f5e3d9703ee197fc04d773c has the wrong extension for XML  *.spdx.rdf instead of .spdx.rdf.xml as per the comment from @goneall  above.

Also we should ignore YAML.org recommendation and standardize on .spdx.yml for YAML instead of .yaml.  The .yml is more commonly used then .yaml  see for example Azure Pipelines (azure-pipelines.yml), GitHub Actions (.yml although .yaml is also suported), GitLab (.gitlab-ci.yml), Travis CI (travis.yml), etc. Alternatively we could allow both .yml and .yaml

See also
- https://en.wikipedia.org/wiki/YAML
- https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml

**Comment by swinslow** [comment]
@tsteenbe In #185 @goneall indicated he's fine with omitting '.xml' for 2.2 to maintain compatibility with the previous recommendation, and that this is something that could be changed / fixed in 3.0.

For YAML I don't have an opinion either way.

**Comment by tsteenbe** [comment]
As discussed in tech call in January 28, 2020 - @goneall  @nishakm  @tsteenbe  @swinslow  @rnjudge and Jim Hutchinson agree to recommend using either .yml and .yaml extension.

**Comment by iamwillbar** [comment]
I'll go ahead and submit a PR to update this.
