### ISSUE TITLE
Add new TEST_OF relationship

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#173]
Add new `TEST_OF` relationship for cases where using TEST_TOOL_OF or TEST_CASE_OF is not suitable.

Example usage
- Tooling or user is unable to determine whether use TEST_TOOL_OF or TEST_CASE_OF but is sure it's testing related.
- To make a directory named `tests` that contains both TEST_TOOL_OF or TEST_CASE_OF

**Comment by kestewart** [comment]
Reviewed in meeting.   It comes from ORT encountered use case.    Agree in principle for 2.2.
This is fall back if we don't know if its a test tool or case,  so not included in distributed artifact.

2 or 1 directions?   only have 1 direction here.
