### ISSUE TITLE
JSON and YAML format: how to include packages, files and snippets

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#188]
In the [SPDX 2.1 model](https://wiki.spdx.org/view/Technical_Team/Model_2_1), an SPDX document does not have a convenient method of representing all of the SPDX elements stored in the document.

The method used in 2.1 is to have a DOCUMENT_DESCRIBES relationship between the document and all elements described (the "root of the tree").  Additional elements would be included by relationship references or other SPDX properties which reference and SPDX element.

With the decision to place relationships in a separate array documented in issue #96 , the SPDX element are no longer pulled into the JSON or YAML document since only the ID is included in the relationship.

**Comment by goneall** [comment]
I can think of 3 possible solutions:

1) Change the resolution of #96 to include the actual SPDX element being described rather than just the ID.  This would be the closest to the model, but would duplicate a lot of element definitions.
2) Create an array for each type of element supported (e.g. `package`, `file`, `snippet`).  The element definitions would include the SPDX ID and the type would be determined by which array it is in.
3) Create an array of elements and use a different mechanism to determine the type of the element (e.g. introduce artifact types as described in issue #171

**Comment by goneall** [comment]
@tsteenbe - I think this may be related to the issue you raised on the tech call in early Jan.

@stevespringett - FYI - this is related to the discussion on artifact types

**Comment by tsteenbe** [comment]
Option 2 would be computational heavy as one would need to parse the entire array whilst the user only wants to render the SPDX Package(s) and not File(s) and Snippet(s).

Option 3 (separate array) would work best for JSON and YAML whilst for XML option 2 (single array with entries with types) is common.

In the SPDX tech call on Jan 28, 2020 option 3) array is the way forward. 
Action item @goneall  @tsteenbe to discuss in CISQ/OMG SBOM call.

**Comment by goneall** [comment]
Resolved with PR #197
