### ISSUE TITLE
Add new `OPTIONAL_DEPENDENCY_OF`

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#192]
Sometimes dependencies are optional like for instance will be installed on Windows but not on Mac OS X

**Comment by swinslow** [comment]
Is this significantly different from the semantics of the existing relationship OPTIONAL_COMPONENT_OF? I know that the example given for that one talks about source files, but I guess it seems that the definition would also work for optional dependencies.

(depending on whatever definition of "component" vs. "dependency" one is using, I suppose... I'm not sure whether SPDX really defines either one...)

**Comment by swinslow** [comment]
Discussed on 2020-02-04 tech team call - optional component is re: the thing you're actually scanning vs. dependency is some third party thing you go get somewhere else.

Sense of attendees on the call was generally neutral or in favor of adding. Didn't have quorum so would appreciate input from @iamwillbar @kestewart or others.

**Comment by kestewart** [comment]
I can see this as useful to be able to capture some scenarios, so am +1 to add it.

**Comment by iamwillbar** [comment]
I'm somewhat ambivalent on this, if it is included we should have a clear description to help consumers on the specification choose one of these relationships over the other. Ambiguity will cause misuse or non-use.
