### ISSUE TITLE
Improve spec documentation for new formats JSON, YAML and XML

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#200]
Currently the examples are the only documentation for the new formats.  At a minimum, the specification should reference the examples.  Ideally, we would document the JSON, YAML, and XML to the same level we currently document the RDF/XML and tag/value.

**Comment by kestewart** [comment]
Based on call,   we need to at least mention the new formats,  do a pass,  add pointers to specific files and documents for examples.      

Jason schema will be pointed to (Gary to Contribute).
