### ISSUE TITLE
Add size of file as optional field

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#21]
Size of File (optional) - express as number of bytes similar to mechanism used for snippet.   Will be useful for heuristics working with snippets and licensing.

**Comment by wking** [comment]
On Tue, Aug 29, 2017 at 04:58:44PM +0000, Kate Stewart wrote:
> Size of File (optional) - express as number of bytes similar to
> mechanism used for snippet.  Will be useful for heuristics working
> with snippets and licensing.

Can you provide more context for this heuristic?  The only one I can
think of is “I don't care about copyrights on content that is less
than ${BYTES}/${LINES}”.  Is that really a heuristic we want to
enable?  Or are there other heuristics which consume file size (but
not the file content?) which are more useful?

**Comment by kestewart** [comment]
Moving this to 3.1 - as we don't have others asking for it, and its not essential at this point.

**Comment by kestewart** [comment]
This is being asked for from the dataset profile.   Moving it back into consideration for 3.0.

**Comment by goneall** [comment]
@kestewart - is this still needed?

**Comment by kestewart** [comment]
This has been added in 3.0 in the Dataset Profile:  https://spdx.github.io/spdx-spec/v3.0/model/Dataset/Properties/datasetSize/
