### ISSUE TITLE
Clause, subclause, and annex numbering

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#232]
# Overview

The spec is hard-wired to a numbering system: 

- Each clause name contains an absolute clause number, as in “1-rational.md” and “4-file-information.md.” 
- Headers contain absolute clause and subclause numbers (except for annex subclauses)

This inhibits the addition/removal/rearrangement of clauses and subclauses.

**This numbering system will be broken by conversion to ISO format**, as follows:

- Two unnumbered clauses "Foreword" and "Introduction" will be added the front
- Three new initial numbered clauses, "Scope", "Normative references", and "Terms and definitions" will also be added.
- An optional trailing, unnumbered "Bibliography" annex probably will be added.
- We might want to add other clauses, such as "Conformance".

ISO does **not** allow hanging paragraphs (i.e., clauses or subclauses having text after their header but *before* their next subordinate header. See clause 2 for an example. All these require a new subclause to be inserted at the start of that clause or subclause (which messes up hard-coded numbered from then on).

## Details

ISO requires clauses to be numbered successively starting at 1 for “Scope.” The “Forward” and “Introduction” pseudo-clauses (which precede Clause 1) must not be numbered, and neither must the optional “Bibliography,” (which goes at the end). Annexes are alphabetic, starting with A.

ISO requires certain clauses up-front, in the following order: “1 Scope,” “2 Normative references,” and “3 Terms and definitions.” It might also be useful to have other (user-defined) clauses near the beginning; “Conformance” is one such example.

During this conversion effort and during future revisions, it would be useful if we had the flexibility to add a new clause up front without that negatively impacting the numbering of subsequent clauses and references into them. Likewise, for removing clauses and/or rearranging them over time.

Currently, the md spec is hard-wired to a numbering system:

- Each chapter name contains an absolute chapter number, as in “1-rational.md” and “4-file-information.md.” 
- Headers contain absolute chapter, section, and subsection numbers, as in 

```
# 4 File Information
## 4.1 File Name <a name="4.1"></a>
## 4.2 File SPDX Identifier <a name="4.2"></a>
```

- It appears that all section and subsection headers contain anchor names, which are also hard-wired. [BTW, the “name” attribute is not supported in HTML5. Instead, one is encouraged to use global attribute “id”.]

- Each cross-reference link contains an absolute chapter number in the displayed text (and in the accompanying md filename and section). For example, “1-rational.md” contains the following links:

```
See [section 5 Snippet Information](./5-snippet-information.md) …
See [section 3.8](3-package-information.md#3.8) …

```
Adding ISO clauses 1–3 (and perhaps others) messes up the current chapter numbering scheme (as will the addition, removal, and rearrangement of clauses later). So, what to do in the md? Here are some possibilities:

- Retain the existing numbering and give new clauses (and annexes) new numbers, perhaps in-between existing ones (such as new clause 4b going between existing clauses 4 and 5), although what would we assign to the new-first chapter, “Scope”? This likely would create much confusion for the reader, as things would look very much “out of order,” at least number-wise. Unnumbered pseudo-clauses like “Forward” and “Introduction” would have headers without numbers. (One would not expect to have any cross references to these clauses.)
- Retain the existing numbering scheme, but renumber everything starting from 1 with the new first chapter, “Scope.” This is a non-trivial task: renaming md files, changing clause headers, changing all links having hard-wired numbers. And given the possibility of adding, removing, or rearranging clauses later, this would need to be a programmatic process. Unnumbered pseudo-clauses like “Forward” and “Introduction” would have headers without numbers. (One would not expect to have any cross references to these clauses.)
- Remove the hard-wired numbering scheme completely **(my recommendation)**. This is a non-trivial task: renaming md files, changing clause headers, changing all links having hard-wired numbers. However, adding, removing, or rearranging clauses later would have no impact. Unnumbered pseudo-clauses like “Forward” and “Introduction” would also have headers without numbers.
- Something else?

Issue #254 proposes getting rid of Chapter 1 and dispersing its contents to other places.

Issue #253 proposes adding the suffix "element" to a number of the chapters.

**Comment by RexJaeschke** [comment]
The level-2 header titles of all Clauses (but not yet Annexes) have been changed to use the unique, single-letter ID Kate assigned to the old chapters, as follows:

* D - Document creation information
* P - Package information
* F - File information
* S - Snippet information
* L - Other licensing information
* R - Relationships between SPDX Elements
* A - Annotations
* I - Review information

Rex assigned a unique ID to the following, new Clause:

* C Composition of an SPDX document

Level-1 headers do *not* have any number or letter!

The pseudo-headers do not [yet] have that change, pending other editorial work.

**Comment by RexJaeschke** [comment]
We are *abandoning* the current single-letter ID (D, P, F, …) for clauses and going to an Arabic digit instead (just as ISO will require). So, the clause numbers will now be:

Unnumbered clause: Foreword
Unnumbered clause: Introduction
Clause 1: Scope
Clause 2: Normative references
Clause 3: Terms and definitions
Clause 4: Conformance
Clause 5: Composition of an SPDX document
Clause 6: (formerly Chapter 2) Document Creation Information
Clause 7: (formerly Chapter 3) Package Information
Clause 8: (formerly Chapter 4) File Information
Clause 9: (formerly Chapter 5) Snippet Information
Clause 10: (formerly Chapter 6) Other Licensing Information Detected
Clause 11: (formerly Chapter 7) Relationships between SPDX Elements
Clause 12: (formerly Chapter 8) Annotations
Clause 13: (formerly Chapter 9) Review Information (deprecated)
Unnumbered clause: Bibliography

As for the Annexes, they will be lettered (as required by ISO), resulting in the following mapping:

Annex A: (formerly Appendix I) SPDX License List
Annex B: (formerly Appendix II) License Matching Guidelines and Templates
Annex C: (formerly Appendix III) RDF Data Model Implementation and Identifier Syntax
Annex D: (formerly Appendix IV) SPDX License Expressions
Annex E: (formerly Appendix V) Using SPDX short identifiers in Source Files
Annex F: (formerly Appendix VI) External Repository Identifiers
Annex G: (formerly Appendix VII) Creative Commons Attribution License 3.0 Unported
Annex H: (formerly Appendix VIII) SPDX Lite
Annex I: (formerly Appendix IX) SPDX File Tags
Annex J: (new) Differences from Earlier SPDX Versions

I’ll make these changes and add both translation tables to Annex J.

**Comment by RexJaeschke** [comment]
I spun off an Annex B-specific issue to a new Issue #368.
I spun off an Annex D-specific issue to a new Issue #369 .
Annex J.1 has a translation table showing the V2.2 and corresponding current numbers.

**Comment by RexJaeschke** [comment]
PRs #410 and #411 fixed-up all header anchors and links (after the ordered prefixed were removed from clause and annex md filenames, so numbers are once again consecutive.

**Comment by kestewart** [comment]
Updated mkdocs.yml to refer to above new sections.
see: https://github.com/spdx/spdx-spec/pull/413

@RexJaeschke - Where should the new bibliography go though?    Anything else I missed?
