### ISSUE TITLE
Appendix VI: extend PACKAGE-MANAGER with additional common services

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#24]
extend Appendix VI: External Repository Identifiers category PACKAGE_MANAGER with common developer service cocoapods, rubygems, pip, sbt, etc..

**Comment by wking** [comment]
And maybe mention that Bower is winding down?  From [1]:

  …psst! While Bower is maintained, we recommend yarn and webpack for
  new front-end projects!

[1]: https://bower.io/

**Comment by iamwillbar** [comment]
I think this is obsolete with the addition of PURL support in #152.
