### ISSUE TITLE
Using correct conformance-related terminology

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#244]
Clause 7 of the ISO Directives, “Verbal forms for expressions of provisions” contains rules regarding how to indicate content is a “Requirement,” a “Recommendation,” or a “Possibility and capability.” (This involves the proper use of shall/shall not, may/may not, should, and so forth.)

Check that all normative content uses the correct normative terminology. (From a quick look at the first 4 chapters, this primarily entails changing some/all occurrences of "must" to "shall", and looking which occurrences of "can" should be "may".)

Check that all informative content either uses the correct informative terminology, or at least does not use normative terminology.

For some specifications, it can be useful to have a Conformance clause.

Should we have a separate Conformance clause? Is there something SPDX-specific that we want to say in this regard that is not otherwise implied by the ISO normative and informative requirements?

**Comment by kestewart** [comment]
Cardinality --> explain in conformance chapter - early on.

**Comment by RexJaeschke** [comment]
During a call between Kate and Rex on 2020-04-14, it was decided to have a new Conformance clause, Clause 4. Since then, Rex has started populating it.

**Comment by RexJaeschke** [comment]
Re the use of the "Cardinality construct" used in many (perhaps hundreds) of places in the spec, when it comes to conformance, ISO requires the use of specific words; for example, "shall" indicates a requirement.

Until now, readers of SPDX have been used to the current approach, so rather than recast all those instances into some ISO-ese text, I want to introduce this construct in the Conformance clause and say how it's the SPDX World's way of indicating a requirement. Of course, ISO might push back when we go to publication, and we should be ready to fight that battle then.
