### ISSUE TITLE
Create and populate the new "Normative references" clause

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#252]
[The decisions made in Issue #232 will impact the way in which this md file’s name and headings are chosen.]

1. Create an md file for the new, second, numbered clause with header, “Normative references.” **DONE**

1. Identify all external sources of information needed to implement this spec, making sure to exclude entries that belong in the “Biography” and list them in this clause. **PENDING**

1. Make sure that each entry is mentioned normatively at least once in the spec. **PENDING**

**Comment by RexJaeschke** [comment]
I created a starter version of the this as well as a Bibliography, the entries for which I got by inspecting all references in the spec, to eternal resources.

**Comment by zvr** [comment]
@RexJaeschke, should all the externally-defined namespaces that we use in our XML be listed as Normative references? (see #283)

**Comment by RexJaeschke** [comment]
[See my proposed resolution below.]

In Annex 1, "SPDX License List", there are *many* links to documents on the spdx.org site: exceptions.index.html and friends, along with all the links from the short identifiers, exceptions lists, and deprecated stuff.

Do we have to cite each of these documents in the “Normative references” clause? If so, the corresponding “Normative reference” entry would contain something like the following:

> *BSD Zero Clause License*, https://spdx.org/licenses/0BSD.html

in which case, ISO might object to also having the hyperlink in the Annex table as well (but removing that would make the document less easily navigable for online users).

A normative reference can either be dated or undated. For dated ones, one has to say the date of publication, and newer releases are irrelevant. An undated one means that whatever the latest edition is that’s the one to use. Do we want these to be dated or undated references?

But then, most of these external resources point off to a vendor-specific place for more info. For example, 0BSD.html points to http://landley.net/toybox/license.html, the contents of which may change even though that of 0BSD.html doesn’t.

If we’re publishing a 2.2.1 spec, which if any of these external resources must be frozen to match that edition?

**Rex's proposed resolution**

I dealt with this by simply putting *only* the two following entries in the Normative references clause:

*SPDX License list*, Linux Foundation, https://spdx.org/licenses/
*SPDX License Exceptions list*, Linux Foundation, https://spdx.org/licenses/exceptions-index.html

ISO might push back on this, but I see no point in putting the many hundreds of URIs these two lead to as entries in Normative references unless ISO forces us.

**Comment by RexJaeschke** [comment]
Appendix III, "RDF Data Model Implementation and Identifier Syntax SPDX ® Vocabulary Specification" has the following link:

> `See: http://spdx.org/rdf/ontology/spdx-2-2`

However, that link is broken.

In any event, is this a link to something critical? That is, should this be listed in the "Normative references" clause? If so, then that annex will need to be normative itself (unless it is mentioned in normative text elsewhere). (Annexes have to be labeled "Normative" or "Informative", explicitly.

**Comment by RexJaeschke** [comment]
Annex 6, "External Repository Identifiers" has the following links (among others):

> https://github.com/package-url/purl-spec
> https://docs.softwareheritage.org/devel/swh-model/persistent-identifiers.html

Are these links to something critical? That is, should they be listed in the "Normative references" clause? (Or, alternatively, the informative Bibliography?) 

BTW, all other links shown in this annex *have* been added to Normative references.

**Comment by RexJaeschke** [comment]
Based on xx, I just asked my XML guru the following question: Should any externally-defined namespaces that we use in our XML be listed as Normative references?

His reply was, as follows:

> In general I’d say that if the standard *requires* that XML elements or attributes in externally-defined namespaces be used in specific circumstances, the standard should make normative reference to where the XML schemas or vocabularies are formally defined. In edge cases the only suitable reference might itself be to a machine-readable XML schema, but usually there will be human-readable documentation that defines the semantics of the XML schema or namespace in question, and it is that documentation that should be cited in Normative References, possibly along with a link to any machine-readable schema or vocabulary (although such electronic resources could be listed in a normative annex).

**Comment by goneall** [comment]
> However, that link is broken.

I just fixed the broken link.

> Are these links to something critical? That is, should they be listed in the "Normative references" clause? (Or, alternatively, the informative Bibliography?)

Yes - they are more definitive (as in they contain more precise definitions) for the RDF vocabulary than the text in the spec

**Comment by goneall** [comment]
@RexJaeschke I'm not exactly sure what needs to be done - can you describe the taks?

**Comment by RexJaeschke** [comment]
All known issues resolved; closed.
