### ISSUE TITLE
Create and populate the new "Terms and definitions" clause

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#253]
[The decisions made in Issue #232 will impact the way in which this md file’s name and headings are chosen.]

1. Create an md file for the new, third, numbered clause with header, “Terms and definitions.” **DONE**

1. Identify which terms are _fundamental_ to the spec and define them here using the (strict) limits required by ISO (must be no more than a phrase that could replace every occurrence of the term). (Lesser terms can defined at their first use and by setting the term name in italics in that one place.) **PENDING**; Rex made a first pass at this.

1. For a small number (20 or so) of entries, it is easier to simply hard code their numbers, bearing in mind that adding, removing, and re-arranging entries might cause some editorial effort.
While md cannot help with auto-numbering such entries, Word can via a series of SEQ fields. 
If it is decided to hard code entry numbers in the md, then do so. **Handled by #381**

1. If ISO does retain bad-break inhibitors, inhibit bad page breaks between the first, second, and third lines, of each entry in the Word spec. **PENDING** A publication-only issue

[In the final ISO spec, this will be Clause 3, hence the 3. prefixes.]

Entries must be numbered (as in 3.1, 3.2, ..., 3.n) possibly with nested, numbered sublists (as in 3.1.1, 3.1.2, ..., 3.1.n).

An entry's format is
```
3.x (in bold)
<term> (in bold>
definition ...
```

**Comment by RexJaeschke** [comment]
# Specific Questions:

## Q1: SPDX document vs. SPDX file

What is the difference between an SPDX document and an SPDX file?

## Q2: The need for a name for top-level thingies

I invented the (placeholder) term “blob”, so I can talk about the top-level thingies inside a document (such as Document Creation Information thingies, Package Information thingies, and so on), as I don’t see a term for these. Might this be what is referred to as a “section”? If “section” is something else, it should be defined here as a term. (Initially I used “element” but found that term used differently in other places. What is the definition of “element”?)

Here’s just one example of why we need such a clearly defined, top-level term, like “blob”: In Chapter 3, “Package Information”, it says, “In `tag:value` format, the order in which package and files occur is syntactically significant.” Say what? My guess is that given my invention of the term blob this should read “... the order in which package [blob(s)] and file [information blob(s)] occur [in an SPDX Document|file] is syntactically significant.”

## Q3: Package

I don’t see a definition of “package.” We’ll also want one for “sub-package.”

## Q4: File

Do we need a definition for “file” beyond the usual IT concept?

## Q5: License

I don’t see a definition for “license.” What about “license list”; does that need defining?

## Q6: Component

I don’t see a definition for “component.”

**Comment by RexJaeschke** [comment]
Re "The need for a name for top-level thingies", on Apr 21, Kate proposed we use "Fact", as that was the term used way-back-when! I have done that in new text and made a conscious decision to spell it with a leading uppercase letter to make it stand out as a proper noun, vs. an ordinary English word.

**Comment by RexJaeschke** [comment]
I have created a starter version of this new clause.

**Comment by RexJaeschke** [comment]
I see the term "section" used in many places, but we have no definition for that. It seems to correspond with what we're now calling a "Fact."

**Comment by RexJaeschke** [comment]
@kestewart: I need help for the issues listed above as Q1, Q4A, Q4B, Q5, Q6, Q7 (especially), and Q8.

**Comment by kestewart** [comment]
SPDX file - should be replaced with SPDX document.

**Comment by goneall** [comment]
I created PR #443 to attempt to address these issues.

I will create a separate pull request to update the SPDX file and document references after reviewing grepping the text for SPDX file.

**Comment by goneall** [comment]
see PR #444 for changes to fix the SPDX file references.
