### ISSUE TITLE
Decide what to keep from Chapter 1: Rationale and how to use it

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#254]
I propose deleting this chapter and moving its content into the new ISO structure, as follows.

1.1 Charter and 1.2 Definition

- Together, they provide the content for the new clause "Scope." **DONE**

1.3 Why is a common format for data exchange needed?

- Content is a candidate for the new "Introduction." **DONE**

1.4 What does this specification cover?

- Move to new clause, "Composition of an SPDX document". **DONE**

1.5 What is not covered in the specification?

- Move to new clause, "Composition of an SPDX document". **DONE**

1.6 What does "Package" mean in the context of SPDX?

A short definition of "package" goes in "Terms and definitions." **NO FURTHER ACTION NEEDED HERE**

1.6 Format Requirements and 1.7 Conformance

- This content goes in a new "Conformance" clause. **DONE**

1.9 Differences from SPDX Specification 2.1

- Goes into a new, informative annex. **DONE**

**Comment by RexJaeschke** [comment]
As all actions have been completed, I'm closing this.

**Comment by WilsonHorse1** [comment]
ISC License

Copyright (c) [year], [fullname]

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
