### ISSUE TITLE
Marking annexes as normative or informative

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#256]
Make sure that

- each annex is explicitly marked as normative or informative **DONE**
- each normative annex is referenced from at least one normative place in the spec
- each informative annex is not referenced as part of any requirement.

ISO annexes (appendices) have a title format different to clauses. This will automatically happen if text is dragged/dropped into the ISO template.

**Comment by RexJaeschke** [comment]
As Kate wrote in Issue #366,

> Can we mark this as "This annex is informative" to avoid problems? Its just reproducing information that is available elsewhere.

Will do.

**Comment by RexJaeschke** [comment]
During a call with Kate on 2020-06-02, we came up with the classifications below.

The following annexes are Normative (critical to the spec):
- Annex C: (formerly Appendix III) RDF Data Model Implementation and Identifier Syntax
- Annex D: (formerly Appendix IV) SPDX License Expressions
- Annex F: (formerly Appendix VI) External Repository Identifiers
- Annex H: (formerly Appendix VIII) SPDX Lite

The following annexes are Informative (FYI, restated, background info):
- Annex A: (formerly Appendix I) SPDX License List
- Annex B: (formerly Appendix II) License Matching Guidelines and Templates
- Annex E: (formerly Appendix V) Using SPDX short identifiers in Source Files
- Annex G: (formerly Appendix VII) Creative Commons Attribution License 3.0 Unported
- Annex I: (formerly Appendix IX) SPDX File Tags
- Annex J: (new) Differences from previous editions

**Comment by RexJaeschke** [comment]
@kestewart: The following need resolution:

1. No normative clause or annex contains a reference to the normative Annex C (formerly Appendix III), so the normative requirements in C are *not* reachable from the spec. We need to add a normative reference or make C Informative.

1. No normative clause or annex contains a reference to the normative Annex H (formerly Appendix VIII), so the normative requirements in H are *not* reachable from the spec. We need to add a normative reference or make H Informative.

1. Normative annex D (formerly appendix IV) makes two normative reference to informative Annexes A and B, in the following:
  > The exact syntax of license expressions is described below in [ABNF](http://tools.ietf.org/html/rfc5234).
  > ...
  > license-id = \<short form license identifier in Annex [A.1](./appendix-I-SPDX-license-list.md#XX)>
  > license-exception-id = \<short form license exception identifier in Annex [B.2](appendix-II-license-matching-guidelines-and-templates.md#XX)>

  We need to make A and B Informative, or redirect the references to a normative place.

**Comment by kestewart** [comment]
C - add at end of 5.1
H - in conformance
D - not sure I understand this.
