### ISSUE TITLE
Update SPDX 2.2 RDF Ontology Diagram

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#260]
https://github.com/spdx/spdx-spec/blob/development/v2.2/chapters/img/spdx-2.2-rdf-ontology.png

is not valid,   need a new image to be added to the document.

**Comment by goneall** [comment]
@zvr Can you update the diagram with the latest OWL document and create a PR or add the daigram to the issue?

**Comment by goneall** [comment]
@zvr Never mind - I just saw PR #303 - reviewing it now
