### ISSUE TITLE
Version 3.0: Is a separate identities field used for anything?

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-spec#261]
Section 2.2 Document Metadata has 8 fields, including:

    creators: Identity[1..*]

where Identity is defined in Sections 2.7-2.10, and where the YAML example of creators is:

    creators:
    - person:
        name: William Bartholomew
        email: iamwillbar@github.com
    - organization:
        name: GitHub

But Section 2.2.4 shows a conflicting example with a separate "identities" field after documentMetadata containing an SPDXID field.

I'm guessing that using SPDXRef with a SPDXID fragment identifier is a mistaken v2 holdover and that v3 intends to replace it with the Identity structure of Section 2.7.

Question: Is that guess correct?  I'm working on an information model for SPDX 3.0, and if the top-level identities field is not used then it can be deleted.

    SpdxDocument = Map {
         1 documentMetadata DocumentMetadata,
         2 identities      Identity [1..*],          // Does this field exist?
         3 artifact        Artifact [0..*],
         4 relationship    Relationship [0..*],
         5 annotation      Annotation [0..*]
    }
    DocumentMetadata = Record {
         1 spdxVersion     SPDXVersion,
         2 dataLicense     CC0-LICENSE,
         3 spdxID          SPDXREF-DOC,
         4 documentNamespace URI,
         5 documentName    String,
         6 created         DateTime,
         7 creators        Identity [1..*],
         8 externalDocumentReferences ExternalDocumentReference [0..*]
    }
    SPDXVersion = String(%^SPDX-\d{1,4}\.\d{1,4}$%)
    CC0-LICENSE = String(%^CC0-1\.0$%)
    SPDXREF-DOC = String(%^SPDXRef-Document$%)
    ExternalDocumentReference = String
    Identity = Choice {
         1 person          Person,
         2 organization    Organization,
         3 tool            Tool
    }
    Person = Record {
         1 name            String,
         2 email           String /email
    }
    Organization = Record {
         1 name            String
    }
    Tool = Record {
         1 name            String,
         2 version         String
    }
    Artifact = Choice {
         1 package         Package,
         2 file            File,
         3 snippet         Snippet
    }
    Package = String
    File = String
    Snippet = String

**Comment by goneall** [comment]
@davaya The 3.0 spec is under development and not yet stable - so there are probably a few more inconsistencies.  This particular item of the identities structure is under active discussion.

You may want to implement the 2.2 spec since it is stable.  If you want to go in the 3.0 direction, I would suggest joining the spdx-tech mailing list and watching the issues since things will be in flux for a while.

**Comment by davaya** [comment]
Thanks Gary, I am on the spdx-tech mail list, and my intent in developing the SPDX 3.0 information model is to identify issues for discussion and eventual resolution by the tech committee.   At this point the answer matters less than the question :-).

In the fullness of time the group will decide between a normalized or de-normalized approach to representing identities, and the issue can then be closed.

**Comment by goneall** [comment]
@davaya - Can this issue be closed?  If not, I can move it over to the model repo.

**Comment by goneall** [comment]
Closing - no response from above comment.
