### ISSUE TITLE
Bullet lists are not formatted in generated spec pages

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#267]
Looking at (for example) https://spdx.github.io/spdx-spec/v2-draft/1-rationale/, it looks like bullet points are not being rendered as a list in the generated draft spec. Here are a couple of screenshots:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/678569/79582137-5c976a00-8099-11ea-9b05-af57fa58a1f2.png">

<img width="718" alt="image" src="https://user-images.githubusercontent.com/678569/79582161-65883b80-8099-11ea-941e-c31af6f5af8a.png">

**Comment by kestewart** [comment]
@tsteenbe - can you take a look at this,   markdown looks ok in: https://github.com/spdx/spdx-spec/blob/development/v2.2/chapters/1-rationale.md

**Comment by kestewart** [comment]
Empty line missing before list, should fix.  Per discussion on call.

**Comment by iamwillbar** [comment]
This is fixed, you can see this here: https://spdx.github.io/spdx-spec/v2-draft/6-other-licensing-information-detected/
