### ISSUE TITLE
Odd bold formatting for certain keywords in spec examples

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#268]
In the tag-value and RDF examples in the generated draft spec, certain words and fragments appear to be getting bolded for unclear reasons. A bit hard to see but here are a couple of examples:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/678569/79583404-1216ed00-809b-11ea-8afc-e75ea9e0c89d.png">

In that example, "and" is bolded -- from inspecting the element, looks like it is getting assigned the `hljs-keyword` CSS class:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/678569/79583518-34106f80-809b-11ea-89f2-2793b450013f.png">

Here's a different one -- "Created" and a portion of the date (prior to the second colon) are getting assigned the `hljs-selector-tag` CSS class:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/678569/79583575-47bbd600-809b-11ea-8619-92bd3c3307d0.png">

<img width="391" alt="image" src="https://user-images.githubusercontent.com/678569/79583712-6ae68580-809b-11ea-996b-98853904e579.png">

**Comment by kestewart** [comment]
@tsteenbe - any ideas why this is occuring?

**Comment by zvr** [comment]
This can be closed now that @tsteenbe made everything ` ```text `

**Comment by kestewart** [comment]
Just checked in latest.  All looks good.   Closing.
