### ISSUE TITLE
Rationale nits

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-spec#269]
* Do the following format requirements say the same thing?  If so, one may be deleted.
1.7.3 Must be suitable to be checked for syntactic correctness independent of how it was generated (human or tool).
1.7.5 Must permit automated specification syntax validation.

* In 1.7.6, the bullets are not rendered as a list.

* 1.7.7 says "Interoperability between all the supported file formats will be preserved."  Aside from being passive voice it sounds good on the surface.  But what does it mean to "preserve interoperablity" between two file formats?  If applications A and B understand format X and format Y, what characteristics of those formats would cause them to meet or not meet this requirement?  In other words, is this a testable requirement?

**Comment by kestewart** [comment]
@davaya - thanks for the feedback.

re:   1.7.3 & 1.7.5 - redundant - will take up in the meeting tomorrow.
re:   1.7.6 - @swinslow noted we've got a rendering problem (see: https://github.com/spdx/spdx-spec/issues/267),  its looking ok in the sources at: https://github.com/spdx/spdx-spec/blob/development/v2.2/chapters/1-rationale.md
re: 1.7.7 - Each of the formats should be able to be verified, and then translated to one of the other supported formats.   We've been doing this between RDF, tag:value and spreadsheets for 5+ years now at this point.   With this release we're adding in the JSON, YAML, and XML (development) version.   There is support for this in the SPDX tooling.    ok?

**Comment by davaya** [comment]
For 1.7.7, my thought process is that standards specify what must be done by conforming implementations, and implementations (including tooling) are tested for conformance based on whether or not they do what the standard says.

Phrasing the requirement as you say makes your intent clearer:  SPDX defines how to validate a document in each supported format, and how to translate a document without loss to each other supported format.

**Comment by kestewart** [comment]
For 1.7.3 - add word in automate,  then delete 1.7.5

For 1.7.7 - Change to: Interoperability between all the supported file formats will be preserved. SPDX defines how to validate a document in each supported format, and how to translate a valid document without loss to each other supported format.    (Gary, Steve explicit ok,  no dissenters on call).

Kate to create PR after call.
