### ISSUE TITLE
JSON is not a supported file format

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-spec#270]
Section 1.7.6 says: Current supported formats include YAML, JSON, RDF, flat text, .xls spreadsheets.

But JSON does not appear to be supported - it is mentioned only three times: once in section 7 as example "package.json", once in Appendix I as the JSON License, and once in Appendix IV as "package.json".   Is there information separate from the rendered 2.2 spec that defines the contents of a file in .spdx.json format?

**Comment by goneall** [comment]
@davaya There is a JSON schema at https://github.com/spdx/spdx-spec/blob/development/v2.2/schemas/spdx-schema.json.

I'm thinking we should add a pointer to the schema in the document.

@kestewart What do you think?  Should we add it to section 1.7.6?

**Comment by kestewart** [comment]
@goneall - am fine with adding references to the appropriate schemas in 1.7.6.
You willing to submit the PR?
