### ISSUE TITLE
Spec generator handles angle brackets in titles incorrectly

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#271]
The generator for the prettified spec doesn't seem to like angle brackets in section titles  :)

Example: https://spdx.github.io/spdx-spec/v2-draft/appendix-VI-external-repository-identifiers/

![Screenshot from 2020-04-19 13-11-38](https://user-images.githubusercontent.com/678569/79694627-85596400-823f-11ea-8517-3569175ce45e.png)

**Comment by kestewart** [comment]
Recommendation is to update the text for headings in Appendix VI.   Ok to have <  >  in text in body, just make headings simpler.
