### ISSUE TITLE
Spec generator does not display all subsections in sidebar

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#272]
Some subsections are not being included in the table-of-contents sidebar in the generated spec site.

For example, in https://spdx.github.io/spdx-spec/v2-draft/6-other-licensing-information-detected/, section 6 includes subsections 6.1-6.5, but only 6.1 shows up in the subsections list:

![Screenshot from 2020-04-19 13-19-37](https://user-images.githubusercontent.com/678569/79694776-8dfe6a00-8240-11ea-8ecf-db29c41e2cbe.png)

**Comment by kestewart** [comment]
@tsteenbe, @iamwillbar - any ideas what might be triggering this?

**Comment by iamwillbar** [comment]
This is fixed, you can see the result here: https://spdx.github.io/spdx-spec/v2-draft/6-other-licensing-information-detected/
