### ISSUE TITLE
Various typo fixes and errors

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#274]
This is a placeholder issue to note the handful of typo fixes and the like in the PR I've submitted at #273.

These include things like fixing misuse of smart quotes in document examples, some typos in language (though I haven't re-read every word), etc. Some are fixing broken rendering (e.g. missing bullet points that fell out from 2.1 to 2.2) while others are stylistic improvements. Nothing is intended to be a material or substantive change.

**Comment by kestewart** [comment]
Reviewed #273, and applied the changes.     Thank you very much for the detailed review that cleanup pass is much appreciated!
