### ISSUE TITLE
Proposal - make the Attribution Text be a property of the SpdxItem

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#280]
Currently in the 2.2 spec, Attribution Text is a property for the package and the file.  The definition of an SPDX item is anything that is copyrightable and can have a license.  It seems that it would be consistent and logical to associate the attribution text with all copyrightable items since they could carry a license which requires attribution.

The practical implication is we would add Attribution Text as a property to Snippets.  Although this may not be used much (we all agree Snippets are not used nearly as widely as Files and Packages), it would be consistent and I could argue for some use cases where it may be helpful.

Another consistent approach would be to remove this as a property from the File making the argument that Packages are the distributed element and is the only class that needs the attribution text.

Having this as a direct property to Package and File but not Snippet seems inconsistent IMO.

**Comment by goneall** [comment]
@kestewart If you agree with the proposal, I can write up a PR with the spec changes.

**Comment by kestewart** [comment]
@goneall - I agree with the proposal.   We should make this consistent.
