### ISSUE TITLE
Errors in XML definitions in the spec text

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-spec#284]
1. 2.3.6, example: 0305E82C33... --> 0305E82C33123#SPDXRef-Document
1. 2.4.6: Document --> spdx:SpdxDocument
1. 2.6.6: spdx:Document --> spdx:SpdxDocument
1. 3.2.6, first example: rdf:ID="SPDXRef-1" --> rdf:about="#SPDXRef-1"
1. 3.2.6, second example: 28A9B0349A1B --> 28A9B0349A1B#SPDXRef-1
1. 3.16.4: In RDF, it is delimited by \<licenseComment\>. --> 
1. 3.22.4: In RDF, it is delimited by \<ExternalRefComment\>. --> 
1. 3.23.6: attributionText --> spdx:attributionText
1. 4.2.6, first example: rdf:ID="SPDXRef-1" --> rdf:about="#SPDXRef-1"
1. 4.14.6: fileContributor --> spdx:fileContributor
1. 5.1.6, first example: rdf:ID="SPDXRef-1" --> rdf:about="#SPDXRef-1"
1. 5.1.6, second example: 28A9B0349... --> 28A9B0349A1B#SPDXRef-1
1. 5.3.6: spdx:byteRange --> spdx:range
1. 5.4.6: spdx:byteRange --> spdx:range
1. 5.10.6: spdx:snippetName --> spdx:name
1. 6.3.6: spdx:licenseName --> spdx:name
1. 7.1.6: relationship --> spdx:relationship
1. 7.1.6 (and in example): `SpdxElement` is never defined. Use Document, Package, File, or Snippet.
1. 8.3.6: annotationType --> spdx:annotationType
1. 8.3.6, example: spdx:annotationType --> annotationType
1. 8.4.6 (and in example): SpdxElement is never defined. Use Document, Package, File, or Snippet.
1. IV.5, end of section (License Exceptions): the attributes should be in `code` in one words and with lower first letter
   * seeAlso: (optional) --> (optional, one or more)
   * example: --> (optional)

@goneall let me know whether you agree with these...

**Comment by kestewart** [comment]
@goneall - to review,  and then Alexios will make pull request.

**Comment by goneall** [comment]
I fixed 8 in a separate pull request

The RDF:ID is OK, but your fix is also correct and I think a bit more consistent - so feel free to update

**Comment by goneall** [comment]
@zvr If you don't mind - go ahead and create a PR for everything except 8 (which should be merged soon)
