### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-spec#285]
I've gone through all pages of the spec and marked some issues:

1. list and links in 1.7.6 not rendered
   * https://spdx.github.io/spdx-spec/v2-draft/1-rationale/#17-format-requirements
1. example tag-value in 4.16.5 is in red
   * https://spdx.github.io/spdx-spec/v2-draft/4-file-information/#416-file-dependencies-deprecated
1. example RDF in 5.3.6 is in red
   * https://spdx.github.io/spdx-spec/v2-draft/5-snippet-information/#53-snippet-byte-range
1. classes in 5.3.6 are not in `code` (cf. 5.4.6)
   * https://spdx.github.io/spdx-spec/v2-draft/5-snippet-information/#53-snippet-byte-range
1. reference to "Appendix IV" in 5.5.1 is not a link
   * https://spdx.github.io/spdx-spec/v2-draft/5-snippet-information/#55-snippet-concluded-license
1. should the list of all relationship types be sorted by name?
   * https://spdx.github.io/spdx-spec/v2-draft/7-relationships-between-SPDX-elements/#71-relationship
1. example RDF in 7.1.6 is incorrectly indented
   * https://spdx.github.io/spdx-spec/v2-draft/7-relationships-between-SPDX-elements/#71-relationship
1. property and class in 8.2.6 not in `code`
   * https://spdx.github.io/spdx-spec/v2-draft/8-annotations/#82-annotation-date
1. sections 9.2 and 9.3 do not appear in table of contents
   * https://spdx.github.io/spdx-spec/v2-draft/9-review-information-deprecated/
1. no sections of Appendix II appear in table of contents
   * https://spdx.github.io/spdx-spec/v2-draft/appendix-II-license-matching-guidelines-and-templates/
1. numbering in CC-BY-3.0 license text in appendix restarts from 1 in different places
   * https://spdx.github.io/spdx-spec/v2-draft/appendix-VII-creative-commons-attribution-license-3.0-unported/

**Comment by kestewart** [comment]
@zvr,  can you re-check the renderings of the lists, when you get on line?   I applied William's fix this evening, so hopefully the list issues are sorted.

**Comment by kestewart** [comment]
@tsteenbe - can you look into why some parts are rendering in "red",   no clue from looking at the source why this is so.

**Comment by tsteenbe** [comment]
Of @zvr list only point 6 and 11 are still to-do the rest has been addressed in https://github.com/spdx/spdx-spec/pull/294

**Comment by tsteenbe** [comment]
Fixed 11 in https://github.com/spdx/spdx-spec/pull/295.

**Comment by kestewart** [comment]
@zvr - can you check we've got them all handled, and then close this?

**Comment by tsteenbe** [comment]
@kestewart  as said above I still need to implement 6 which I will do later today, for 11 the PR is still open but all the other points should now be fixed, see https://spdx.github.io/spdx-spec/v2-draft/

**Comment by zvr** [comment]
Can confirm that everything is OK besides 6 and 11 (well, with a couple of typos I submitted in #296)

**Comment by kestewart** [comment]
Thanks @zvr for confirming!   PR #299 from Steve has been applied to address the issues you caught in #296 and a few others. 

@tsteenbe - standing by for PR,  and then we can close this issue.

**Comment by kestewart** [comment]
@tsteenbe - please do not implement #6 (should the list of all relationship types be sorted by name?
https://spdx.github.io/spdx-spec/v2-draft/7-relationships-between-SPDX-elements/#71-relationship).   I was looking at it and I think its going to end up being more confusing.   Right now related things are roughly grouped together.   @zvr - Lets revisit this in 3.0.    

@zvr - #11 is merged now.     I'm going to mark this as closed.    Please reopen if you disagree.
