### ISSUE TITLE
Change cardinality of selected fields from manditory to optional.

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#29]
SPDX 2.1 has 34 mandatory tags.   Propose to reduce the number of mandatory fields to minimal fields needed for exchange to reduce friction to participate.   

Believe the following fields could be made optional:
§2.4 DocumentName
§2.5 DocumentNamespace - Most of the time these URL are totally artificial as producers do not maintain SPDX as linked data
§3.9 PackageVerificationCode - Verification should be optional, license scanners ignore different type of files such as .git dirs and as such two scanners can produce different PackageVerificationCode for the same package
§3.15 PackageLicenseDeclared - PackageLicenseConcluded and PackageLicenseInfoFromFiles provide the same information
§5.3 SnippetByteRange - Making this optional reduces friction to SPDX participation.  Maintainer can easily manually specify SnippetLineRange but SnippetByteRange requires tooling

Gary: consider going to profiles?   Simpler - same field names,  make optional or not.   Some redundancy in documentation.

SPDX-Document
2.1.5 SPDXVersion
2.2.5 DataLicense
2.3.5 SPDXID
2.4.5 DocumentName 
2.5.5 DocumentNamespace 
2.8.5 Creator
2.9.5 Created
 
SPDX-Package
3.1.5 PackageName
3.2.5 SPDXID
3.7.5 PackageDownloadLocation
3.9.6 PackageVerificationCode
3.13.5 PackageLicenseConcluded
3.14.5 PackageLicenseInfoFromFiles
3.15.5 PackageLicenseDeclared
3.17.5 PackageCopyrightText
 
SPDX-File
4.1.5 FileName
4.2.5 SPDXID
4.4.6 FileChecksum
4.5.5 LicenseConcluded
4.6.5 LicenseInfoInFile
4.8.5 FileCopyrightText
 
SPDX-Snippet
5.1.5 SnippetSPDXID
5.2.5 SnippetFromFileSPDXID
5.3.5 SnippetByteRange
5.5.5 SnippetLicenseConcluded
5.8.5 SnippetCopyrightText
 
Non-SPDX License Identifier
6.1.5 LicenseID
6.2.5 ExtractedText
6.3.5 LicenseName
 
SPDX–Annotation
8.1.5 Annotator
8.2.5 AnnotationDate
8.3.5 AnnotationType
8.5.5 AnnotationComment

**Comment by wking** [comment]
I suggest we split this issue up into per-property (or few-property)
issues to keep discussion focused.  Trying to sort out the cardinality
of many properties in a single issue seems like it could get
confusing.  Maybe this issue should just be about DocumentNamespace,
since you have good motivation for making that optional above?

**Comment by goneall** [comment]
@kestewart - I think this is resolved - can we close?

**Comment by kestewart** [comment]
Yes, this has been resolved in 3.0.  Closing.
