### ISSUE TITLE
Bump license to CC BY 4.0?

### ISSUE THREAD

**Issue by wking** [spdx/spdx-spec#3]
Should we bump [the current CC BY 3.0][1] to the [current 4.0 license][2]?  The CC covers the improvements [here][3] and suggests (in the [“Clarity about adaptations” section][3]) that a license bump from 3.0 to 4.0 is a valid adaptation licence choice, so we may not need to collect “I'll provide my previous contributions under the CC BY 4.0 as well” statements from previous contributors.

[1]: https://github.com/spdx/spdx-spec/blob/098a74606e8f0cfe2abc5bfb4b2285eab021ee98/LICENSE
[2]: https://creativecommons.org/licenses/by/4.0/
[3]: https://creativecommons.org/share-your-work/licensing-considerations/version4/

**Comment by kestewart** [comment]
Discussed this on the SPDX call today.  No objection to updating to 4.0 from Gary, Alexios, Uday or Kate.   Suggestion is we do this after we figure out Contributing.MD,  and do it for the next release.

**Comment by swinslow** [comment]
I'd suggest this for a conversation with the legal team on the next call. Would like to confirm that there's agreement that the spec can move to 4.0 in full, and not end up in a "CC-BY-3.0 AND CC-BY-4.0" scenario.

**Comment by goneall** [comment]
@jlovejoy Can you add this to the next legal call to confirm we can move to CC-BY-4.0 for the spec?
