### ISSUE TITLE
Allow Relationship Types to be Predicates

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#30]
Allow relationship types to be predicates 

(e.g. http://mynamspace#mypackage spdx:contains http://mynamespace#myfile).
Verbose due to the presence of optional comment field
Details from discussion from Yev: 

Package → Relationship
Relationship → File

Package:contains → File

contains: http://myname:myFile

<.... id=”myPackage”>
	<spdx:contains id=”http://myname:myFile” />
</rdf:Description>

http://myNamespace#myPackge spdx:contains http://myNamepsace#myFile

Thomas notes they are using relationship comments to customize relationship.  So would not like to see this ability remove.    Likes the proposal, but not want to see “other” removed. 

Yev,  both should be valid (short version, as well as original).   Yev to provide example.  Not make old ones go away, just enable addition of concise way of expressing relationships.      
Thomas agrees Tag value will become clearer as result of having this additional syntax. 
Open question - can annotation describe a relationship?   Based on model,  not able to.  So not a solution at this point.

**Comment by kestewart** [comment]
GIven no solution, has been presented, and there are lots of other considerations around namespaces right now.  Moving this to 3.0

**Comment by swinslow** [comment]
@kestewart agreed -- I'm not really able to weigh in on RDF stuff but this feels like a 3.0 issue.

**Comment by goneall** [comment]
With the restructuring of the `Relationship` class in 3.0, this issue feels a bit stale - so I'm going to close it.

@kestewart if you think this is still an issue, feel free to reopen
