### ISSUE TITLE
Add examples for YAML and JSON

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-spec#317]
Update the specification content to include example snippets for YAML and JSON:

- [X] Document creation information
- [ ] Package information
- [ ] File information
- [ ] Snippet information
- [ ] Other licensing information
- [X] Relationships
- [X] Annotations

**Comment by kestewart** [comment]
Can you go ahead and add in the example tables you've got for the sections noted, and I'll start to work on the tables for the other parts.

Rex is working through and translating over, so if we can get the examples in the structure we want now,  less work later for all of us.

**Comment by goneall** [comment]
@iamwillbar Same question - shall we close this and work on it in 3.0?

**Comment by iamwillbar** [comment]
@goneall yes, I think that makes sense.
