### ISSUE TITLE
Need Help with "Differences from previous editions"

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#328]
I have created a new (informative) annex, "Differences from previous editions", and populated it with stuff I think belongs there. Here are the outstanding issues I'm aware of:

* Do we want to add info about releases earlier than 2.1? Note that ISO only makes available the latest edition of a spec, so it might be useful to readers (especially those still dealing with earlier editions) to keeping a  "running history" here. **YES, PENDING**

* Update the links to and titles of the V2.2.1 clauses and annexes. **DONE**

* Assuming the "rule" numbers in the list are not sacred, remove them; otherwise, do what? **Rule numbers removed**

**Comment by kestewart** [comment]
I think the material you're looking for can be taken right from:
https://www.linuxfoundation.org/blog/2020/05/spdx-2-2-specification-released/

A version of similar information (with history) is also available in: https://docs.google.com/presentation/d/1JGVS6vzGwueTDCBHWUNy9ItEFHZ5BwFZoUZsl7Ccxsw/edit#slide=id.g84d1f18d15_0_220

Will this suffice?

**Comment by RexJaeschke** [comment]
@kestewart: I currently start with diffs between 2.2.1 and 2.1, but I'm thinking I should move all those entries to "diffs between 2.2 and 2.1" and then add a new "diffs between 2.2.1 and 2.2" where I say "convert to ISO format". How does that sound?

**Comment by kestewart** [comment]
That sounds about right.

**Comment by RexJaeschke** [comment]
Completed.
