### ISSUE TITLE
Consider whether '+' should work for Exceptions IDs too

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#346]
It looks to me like the `+` operator only works with License IDs in the current syntax, not Exception IDs.

There was a discussion at https://github.com/spdx/license-list-XML/issues/1027#issuecomment-627394072 about an instance where this would be nice to have. Further discussion in that thread indicated that it isn't necessarily required, but it's probably worth at least discussing as part of 3.0 whether this change is useful to make.

**Comment by goneall** [comment]
Since this would be a non-breaking change, moving this to a 3.1 milestone

**Comment by swinslow** [comment]
There hasn't been any further discussion of this since my originally filing this issue nearly 4 years ago, so I'm going to go ahead and close it.

For the record, personally I don't see a need for this. I suspect it's vanishingly rare for licensors to use an "or-later" construct with regards to future versions of _license exceptions_. If someone really needs to communicate this in a license expression, they can always use a `LicenseRef-` or `ExceptionRef-`, or perhaps even suggest that the "or-later" construct be added to the official [Exceptions List](https://spdx.org/licenses/exceptions-index.html).
