### ISSUE TITLE
First fields for sections in tag:value format

### ISSUE THREAD

**Issue by tbetker** [spdx/spdx-spec#348]
The SPDX Specification 2.1 (and also 2.2) explicitly states that in tag:value format, 
- a Package section must start with PackageName ("A new Package Information section is denoted by the Package Name field."),
- a File section must start with FileName ("The first field to start off the description of a File must be the File Name in tag:value format"),
- a Snippet section must start with SnippetSPDXID ("The first field to start off the description of a Snippet must be the Snippet Identifier in tag:valueformat.").

However, there are no corresponding rules for License, Relationship, Annotation and Review sections, which is quite an issue when parsing a tag:value file -- if there are multiple sections of the same type in a row, where does one end and the next one begin?

As far as I can tell, the spdx-tools Verifier tool assumes that
- a License section starts with LicenseID,
- a Relationship section starts with Relationship,
- an Annotation section starts with Annotator,
- a Review section starts with Reviewer.

My suggestion would be to add appropriate language to this effect to chapters 6, 7, 8, 9.

**Comment by goneall** [comment]
Relationships, Annotations, and Reviews are required to be on a single line for tag/value - so I think we're OK there.  

I agree the license section should be more clearly specified as proposed.

@kestewart - do you agree?

**Comment by tbetker** [comment]
I am not sure what "single line for tag/value" means here, but I guess I didn't explain the issue very well. Here is a simple example:

    ...
    Relationship: ...
    RelationshipComment: ...
    Relationship: ...
    ...

Which Relationship section does the RelationshipComment belong to -- the first one or the second? Syntactically, both are correct, but what should the parser assume?

Annotation sections are a bit different because all fields are mandatory, so if you have two (arbitrary) permutations of Annotator, AnnotationDate, AnnotationType, SPDXREF, AnnotationComment, you may assume that the second Annotation starts when you see a field you have already seen before. This makes the parser's life a lot harder, though; it's much easier if you can assume that a new Annotation starts when you see an Annotator.

**Comment by goneall** [comment]
@tbetker I was thinking about the mandatory fields on Relationship.  You are correct in that the `RelationshipComment:` is on a separate line and the current parsing expects it to follow `Relationship:`.  I agree we should document this as well.

**Comment by goneall** [comment]
@tbetker did you mean to close the issue?  Seems like a reasonable thing to document.  

My only concern is if we introduce an incompatibility by adding an ordering requirement in the spec we didn't add before.

In 3.0, this wouldn't be an issue since we allow breaking changes in major release.

**Comment by kestewart** [comment]
Agree that Relationship: starts a relationship section.  RelationshipComment is associated with the Relationship that precedes it, and this is documented in: 7.2.4 Data Format: Free form text that can span multiple lines, **refers only to the immediately preceding relationship.**

**Comment by goneall** [comment]
Moving to 3.0 milestone

**Comment by goneall** [comment]
Since we are moving to a very different syntax for tag/value in 3.0, I'm going to close this issue.

cc: @kestewart
