### ISSUE TITLE
Introduce CopyrightText at all levels and relax cardinality

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#36]
Thomas: Instead of PackageCopyrightText and CopyrightText add introduce new PackageCopyrightHolder and CopyrightText. Both optional and more than one entry can exists per SPDX-File or SPDX-Package. Better indicates individual rights holders and makes parsing of this data easier.

Kate: https://spdx.org/spdx-specification-21-web-version#h.2grqrue - relax one to many?
Yev: Copyright holder implies present tense,  could have been reassigned.   Declared vs concluded may be required,  not sure we want to go there.
Thomas: Changing cardinality would help.  
Yev:  We’ll need to apply this to Files & Snippets,  as well.
Gary, Kate, Yev, Alexios, Thomas - all +1 on relaxing cardinality.   2.2,  permit cardinality to go from one to many.    Shelve copyrightholder until more compelling use case. 
	Tags: PackageCopyrightText, FileCopyrightText, SnippetCopyrightText; RDF: property spdx:copyrightText

**Comment by wking** [comment]
On Tue, Sep 12, 2017 at 09:52:30AM -0700, Kate Stewart wrote:
> Tags: PackageCopyrightText, FileCopyrightText, SnippetCopyrightText…

I'm not particularly clear on how tag/value parsing works, but if the
parser is figuring out *which* snippet/file/package is involved based
on the context, won't it be able to figure out the type too?  If it
can figure out the type, can't we define a single CopyrightText type
and explain that it can be used in all of those contexts?  For an
example in another spec, HTML has “Contexts in which this element can
be used” (e.g. in [1]).

[1]: https://www.w3.org/TR/html5/grouping-content.html#the-p-element

**Comment by kestewart** [comment]
Include this as part of the licensing rework for 3.0 when we go to base and profiles.

**Comment by goneall** [comment]
This is resolved in the 3.0 spec
