### ISSUE TITLE
Annex D (formerly Appendix IV): SPDX license expressions - Subclause Numbering

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#369]
Attention @kestewart 

The title is now "\# D SPDX license expressions`, and the three level-2 headers are "\## D.1", "\## D.2", and "\## D.3". So far, so good!

However, what is now D.3, "Composite License Expressions", has 5 level-3 headers with numbers of the form "1) xx", "2) xx", ... "5) xx". Are these numbers sacred? If not, I propose replacing them with "D.3.1 xx" through "D.3.5 xx", which is what ISO would require. What to do?

**Comment by kestewart** [comment]
Go ahead and apply to align with ISO.

**Comment by RexJaeschke** [comment]
Done in PR #373
