### ISSUE TITLE
Deployment for v3.0 failing

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#379]
The following error is reported by the Github deploy action on the development/v3.0 branch:

```
...
 9 files changed, 49 insertions(+), 49 deletions(-)
To github.com:spdx/spdx-spec.git
 ! [remote rejected] gh-pages -> gh-pages (cannot lock ref 'refs/heads/gh-pages': is at 359c5a9bb2ab5e5302e154b59dcdb7a1c4ee5884 but expected 86a75921e9916207ac825f3ef264c1f95f9c19e1)
error: failed to push some refs to 'git@github.com:spdx/spdx-spec.git'
```

This is likely related to PR #377

**Comment by goneall** [comment]
@iamwillbar do you mind taking a look at this one?

**Comment by iamwillbar** [comment]
I think this was caused by two deploys running simultaneously. Re-running the job succeeded. I'll file a separate issue for this but it's probably pretty low priority for now.
