### ISSUE TITLE
Put each sentence on its own line in the Markdown source?

### ISSUE THREAD

**Issue by wking** [spdx/spdx-spec#4]
I help out with the Open Container Initiative, which [does][1] [this][2].  There's no effect on the rendered content, and putting each sentence on its own line helps with `git blame`-based workflows.  For example, links like [this][3] can target a single sentence.  And it's easier to see the last commit that the content with sentence granularity (instead of paragraph granularity):

```
$ git blame chapters/appendix-IV-SPDX-license-expressions.md | grep ' 90)'
f902b619 (Thomas Steenbergen 2017-05-02 22:46:48 +0200  90) Sometimes a set of license terms apply except under special circumstances. In this case, use the binary "WITH" operator to construct a new license expression to represent the special exception situation. A valid \<license-expression> is where the left operand is a \<simple-expression> value and the right operand is a \<license-exception-id> that represents the special exception terms.
```

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc6/style.md#one-sentence-per-line
[2]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc6/style.md#L3-L7
[3]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc6/style.md#L7

**Comment by tsteenbe** [comment]
Thank you for sharing. I like the concept but not sure with the non technical users (think legal counsels) we have in the SPDX community we be able to maintain it. Ideally this should be verified by tooling in pre-submit. Let me discuss this in the next Tech team call (https://wiki.spdx.org/view/Technical_Team)

**Comment by wking** [comment]
On Sun, Jul 16, 2017 at 01:34:12AM -0700, Thomas Steenbergen wrote:
> I like the concept but not sure with the non technical users (think
> legal counsels) we have in the SPDX community we be able to maintain
> it.  Ideally this should be verified by tooling in pre-submit.

Getting a false-positive-proof test for this seems tricky.  For
example [1]:

  A common example is when software is offered under a choice of one or more licenses (e.g., GPL-2.0 OR BSD-3-Clause).

contains a few periods that do not terminate the sentence.  I think a
reasonable solution is just to leave commit access in the hands of
users who have internalized whatever style rules are in force.  That's
not going to be fool-proof either, but I expect it will fail with
false-negatives (which we can always fix with follow-up commits)
instead of having a false-positive that blocks good material from
coming in.

[1]: https://github.com/spdx/spdx-spec/blame/cfa1b9d08903befdf03e669da6472707b7b60cb9/chapters/appendix-IV-SPDX-license-expressions.md#L5

**Comment by kestewart** [comment]
If we can find a tool to check this on commit automatically,  we'll re-open this.    Its a good idea but asking for this level of manual discipline is going to be hard to keep up.    Based on tech team call on 2017/12/19.

**Comment by wking** [comment]
> Its a good idea but asking for this level of manual discipline is going to be hard to keep up.

I [don't see a problem with occasional lapses][1].  Do other folks see a problem with spotty manual enforcement?  Or put another way, does this repository want to adopt a *different* wrapping policy?  Or is wrapping up to each individual contributor?

[1]: https://github.com/spdx/spdx-spec/issues/4#issuecomment-315818812
