### ISSUE TITLE
Update other subsections mentioning cardinality?

### ISSUE THREAD

**Issue by jmudge** [spdx/spdx-spec#404]
1. [conformance.md](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/conformance.md) 4.3 includes examples of cardinality. Cardinality is now represented in a tabular format in other document chapters. Should these cardinality examples be updated (e.g. replaced by three tables) or left unchanged?
2. [composition-of-an-SPDX-document.md](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/composition-of-an-SPDX-document.md) 5.2.1 includes "Cardinality: Mandatory, one.". Should this text be updated (e.g. replaced by a table) or left unchanged?

**Comment by RexJaeschke** [comment]
While changing these to be tables sounds like a good idea, as table numbers span all clauses, that would *require every* subsequent table (which is pretty much all tables) to have their hard-coded numbers changed! As such, I suggest changing the 4.3 case to not look like a table. I don't have a suggestion for 5.2.1, but ti is not currently a table, so is unaffected by that argument.

**Comment by RexJaeschke** [comment]
Decided to leave as-is and see if ISO pushes back.
