### ISSUE TITLE
Missing copyrightText for `SPDXRef-Saxon` in examples

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#409]
In SPDX examples, the package `SPDXRef-Saxon` is missing mandatory field `copyrightText ` see
- https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXYAMLExample-2.2.spdx.yaml#L166-L179
- https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXJSONExample-v2.2.spdx.json#L130-L144
- https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXXMLExample-v2.2.spdx.xml#L257-L273

**Comment by goneall** [comment]
@tsteenbe Good catch - I'll add that in the next update.

**Comment by goneall** [comment]
Fixed in #416
