### ISSUE TITLE
Normative children and informative parent information

### ISSUE THREAD

**Issue by wking** [spdx/spdx-spec#41]
We currently have some awkward wording around cardinality (#40).  I think the difficulty comes from defining cardinality alongside the child element, when it's really a parent property.  I'd rather see each parent clearly define their allowed children, with potential backlinks from children to possible parents.  For an example of this in another spec, see HTML's [`html`][2] and [`p`][3] elements, which have a [normative “Content model”][4] and a [convenience “Contexts in which this element can be used”][5].  Once we shift those around, we could have the root element clearly declare that it could contain zero or more package entries, zero or more file entries, etc.

This would be a rather large change, and there are a number of open PRs already in flight.  I'm happy to put together a PR for this, but it would be good to get at least preliminary agreement on the approach first, and ideally have fewer in-flight PRs going on in parallel ;).

[2]: https://www.w3.org/TR/html5/semantics.html#the-html-element
[3]: https://www.w3.org/TR/html5/grouping-content.html#the-p-element
[4]: https://www.w3.org/TR/html5/dom.html#element-dfn-content-model
[5]: https://www.w3.org/TR/html5/dom.html#element-dfn-contexts

**Comment by goneall** [comment]
With the 3.0 model and spec, this is now how we define the information - closing
