### ISSUE TITLE
Tables: Cell containing multiple lines of text with explicit line breaks

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#418]
@jmudge I've run the complete V2.2.1 md file set through pandoc, and am studying the result to see what needs tweaking to get a correct/better Word rendering. I'm currently looking at tables.

In 6.1, we have the following table:

```text
> Table 2 — Metadata for the SPDX version field
> | Attribute | Value |
> | --------- | ----- |
> | Required | Yes |
> | Cardinality | 1..1 |
> | Format | `SPDX-M.N` where:<br>* `M` is major version number<br>* `N` is minor version number. |
```

which renders nicely in GitHub as

> Table 2 — Metadata for the SPDX version field
> | Attribute | Value |
> | --------- | ----- |
> | Required | Yes |
> | Cardinality | 1..1 |
> | Format | `SPDX-M.N` where:<br>* `M` is major version number<br>* `N` is minor version number. |

as the embedded HTML `<br>`s each force a newline. But, the `*`s do *not* render as bullets. Unfortunately, it appears these line breaks are *ignored* during the pandoc conversion, with the result being a single line cell entry, as follows:

> | Attribute | Value |
> | --------- | ----- |
> | Format | `SPDX-M.N` where:* `M` is major version number* `N` is minor version number. |

with *no* intervening space before the `*`s.

I tried replacing the line breaks with two trailing spaces, which md uses to indicate a line break *without* a paragraph break, but that did not solve the problem. (Interestingly, in ordinary paragraphs, the 2-trailing spaces *does* cause pandoc  to generate a soft-return (ala `<br>`)!

If we can’t think of a solution in md, I'll have to reformat those occurrences in the Word version. That said, do you recall that we have many instances of this kind of thing?

I see a similar problem in 6.6 and 6.7. What we really need is the ability to have an unnumbered list inside a table cell, and as best as I can see, that is *not* possible using md's table syntax.

**Comment by jmudge** [comment]
@RexJaeschke  interestingly in the generated HTML output the newlines in the table cells are displayed and the `*` characters are not, so Table 2 is displayed as follows:
![HTML](https://user-images.githubusercontent.com/11298435/84593787-eb302980-ae45-11ea-9c65-47c86813a0cc.png)

The md `*` characters in table cells can be removed or replaced with HTML bullets.

If the HTML output is imported into Word then the newlines in the table cells are preserved as can be seen below (note in this example Word borders for the table have been enabled):
![Word](https://user-images.githubusercontent.com/11298435/84594078-ab6a4180-ae47-11ea-8772-c79bbe447ab3.png)

**Comment by RexJaeschke** [comment]
We can resolve this by using pandoc to go through HTML and then to Word.
