### ISSUE TITLE
HTML Tags and HTML-like Constructs Ignored by pandoc

### ISSUE THREAD

**Issue by RexJaeschke** [spdx/spdx-spec#419]
@jmudge, FYI.

I'm experimenting with pandoc to convert the SPDX spec md files to Word for submission to ISO. The spec currently has some embedded HTML, which (mostly) works fine when rendered in GitHub; however, it is **ignored** by pandoc. (pandoc can also detect related shortcomings/errors in the markdown.) While I stumbled on some of these things in my research, I just discovered that if one runs pandoc requesting a log file with the command-line option

> `--log=`*FILE*

pandoc write log messages in machine-readable JSON format to *FILE*. And one kind of message is `"type": "InlineNotRendered"`, which points to something in the md input that went unprocessed by pandoc.

Here's what I found:

Offending Tokens | Location | Comments
------------------- | ---------- | ------------
`<condition>`, `<feature>` | 4.3 | These are *not* intended to be HTML tags, so  `<` and `>` need to be escaped.
Anchors ala `<a name="2.1"></a>` | Every level-2 and -3 header | We removed the numeric prefixes from all md filenames and headers to avoid hard-coding the order of clauses and subclauses, and used anchors for all link targets. As pandoc ignores these, *all* link targets in the Word spec after conversion are broken. (As it happens, they are already broken for another reason, the change from multiple md input files to one Word file.)
`<br>`/`</br>` | Numerous places | Used in an effort to allow multiple lines of text in a table cell.
`<sup>`/`</sup>` | 7.9 | Used (twice) to support a footnote in a table. (The associated anchor `<a name="Algorithm">` was also ignored.)
`<ul>`/`</ul>` and `<li>`/`</li>` | Several places | Used to get bullet lists in a table cell.
`<pre>`/`</pre>` | 12.1 | Used in conjunction with `<br>` to get a multi-line cell.
`<<` ... | B.15.2 | Contains the following non-code-fenced text: `“<<>>”`, `<<var; . . . >>`, `<<beginOptional; . . .>>`, `<<endOptional>>`, `<<var; . . . >>`, and `<<var;name=organizationClause3;original=the copyright holder;match=.+>>`. Those that have the form of an HTML tag simply disappear (and I think need to be fixed in the md anyway); the "partial" tags mostly make it as text.

**Comment by jmudge** [comment]
@RexJaeschke FYI the constructs that pandoc is able to convert to the output format depends upon the specific conversion being performed. For example if the file document-creation-information.md is converted to HTML instead of Word then pandoc seems to be able to convert most of the constructs used in the input file and the generated log file is empty.

I believe it would be worth investigating further the suggestion made in https://github.com/spdx/spdx-spec/issues/418 of first converting the GitHub flavored markdown content to HTML using pandoc, as an intermediate stage, prior to importing the HTML into Word.

**Comment by RexJaeschke** [comment]
Thanks for that idea, John. I just put all the source through pandoc to HTML, and as you pointed out, the log file is empty, as is handled the well-formed embedded HTML. (However, I thought it would have reported the text that was rejected/ignored.) A *quick* glance at the DOCX generated from the HTML shows the HTML was applied as intended. So this approach might work provided it doesn't have any unexpected side-effects.

**Comment by RexJaeschke** [comment]
I escaped the occurrences of HTML tag-like text in 4.3 and B.15.2.

**Comment by RexJaeschke** [comment]
For 4.3, replaced escaped backslashes with open/close braces.
