### ISSUE TITLE
Update version numbers from 2.2 to 2.2.1

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#420]
Here are a couple of places where I'm seeing 2.2 that should probably be updated to 2.2.1:

* [setup.py](https://github.com/spdx/spdx-spec/blob/9f369218c72a379bdaff083d4c52aa0df9bf9d89/setup.py#L14): line 14: `version = "2.2.0",`
* [chapters/index.md](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/index.md#the-software-package-data-exchange-spdx-specification-version-22): title: `The Software Package Data Exchange (SPDX®) Specification Version 2.2`
* [chapters/rationale.md](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/rationale.md#18-conformance-): 1.8.2 and 1.8.3: should references to 2.2 here be updated to 2.2.1?

**Comment by RexJaeschke** [comment]
- I don't know how to fix setup.py.
- I fixed index.md (also correcting the link to now Annex G).
- rationale.md is *no longer* part of the spec. Perhaps it should be deleted.

**Comment by kestewart** [comment]
Fixed setup.py in https://github.com/spdx/spdx-spec/pull/425
Need to figure out how to delete rationale.md,  but its not harmful for it to be there for now.
