### ISSUE TITLE
'packages' in XML vs. 'package' in RDF

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#421]
Found `packages` used in spdx.xml example, why is it not `package` like RDF?

https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXXMLExample-v2.2.spdx.xml#L246-L256 vs. https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXRdfExample-v2.2.spdx.rdf.xml#L1821-L1831

**Comment by goneall** [comment]
Tend to agree - this is a general problem where we use the plural form for all the XML properties when in XML it should be singular.

**Comment by goneall** [comment]
Since this is a change to XML which is not stable in 2.2, I'm moving this issue to 2.3

**Comment by goneall** [comment]
@tsteenbe how important is this to be resolved in 2.3?  I've got a pretty deep stack of 2.3 work to do before release.

**Comment by goneall** [comment]
In 3.0, we agreed all properties should be singular for all serializations which resolves this issue.  Closing.
