### ISSUE TITLE
Update license matching templates to allow nested rules in Optional text

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#429]
Propose changing the [Template Format](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/license-matching-guidelines-and-templates.md#b152-template-format-) to allow nesting rules inside an `<<beginOptional>>` `<<endOptional>>` rule.  Nesting of rules inside a `<<var; ...>>` would would still be disallowed.

Many of the current licenses already nest rules inside optional text and the current Java tools support the nesting.  This proposal would bring the spec up to date with what is being used in practice.

**Comment by kestewart** [comment]
@goneall - is this still an issue in 2.3?    https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/license-matching-guidelines-and-templates.md#b152-template-format-

**Comment by goneall** [comment]
This issue is made obsolete with the recent changes to the matching guidelines chapter.
