### ISSUE TITLE
Some package in examples are missing the PackageVerificationCode

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#440]
The following packages in the examples are missing mandatory package verification code see https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXYAMLExample-2.2.spdx.yaml#L203-L220

**Comment by swinslow** [comment]
Just mentioned in #439 -- these shouldn't have package verification codes b/c filesAnalyzed is false: https://spdx.github.io/spdx-spec/v2-draft/package-information/#79-package-verification-code-field

so I think this is correct as-is.

**Comment by tsteenbe** [comment]
Thank you for pointing this out @swinslow closing this ticket
