### ISSUE TITLE
Update version number for the class diagram in section in Annex C

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#442]
The version number referenced above the diagram is 2.2, it should be updated to 2.2.1 to be consistent with the spec version.

**Comment by goneall** [comment]
The number number above the graphic was updated in PR #431

**Comment by goneall** [comment]
If the URL to the vocabulary needs to be updated, the directory `http://spdx.org/rdf/ontology/spdx-2-2` needs to be copied to `http://spdx.org/rdf/ontology/spdx-2-2-1` and the URL updated.

Since I do not have access to the AWS store containing these files, someone with access (e.g. @swinslow) will need to make the copy.

Once the copy is made, I can update the PR to include the new reference.

**Comment by kestewart** [comment]
@swinslow - any update?

**Comment by swinslow** [comment]
Thanks @goneall and thanks for the reminder @kestewart. This is now updated and live at https://spdx.org/rdf/ontology/spdx-2-2-1/, also https://spdx.org/rdf/ontology/spdx-2-2-1/spdx-ontology.owl.xml for the corresponding XML.

I do have several questions for @goneall -- sorry for the minutiae, just want to make sure I'm setting this up right for the RDF situation:

1. In each of these files, I changed every instance of "2.2" to "2.2.1" instead; is that what you meant in your comment above?
2. I note that the "Version IRI" at the top of https://spdx.org/rdf/ontology/spdx-2-2-1 is http://spdx.org/rdf/terms/2.2.1; however, that link is not currently valid. (The same was the case for the 2.2 and 2.1 equivalents.) Should http://spdx.org/rdf/terms/2.2.1 actually point to a copy of these same RDF terms?
3. The first "IRI" listed is http://spdx.org/rdf/terms -- that currently points to the 2.2 document. Should I replace the document at http://spdx.org/rdf/terms with the 2.2.1 version?
4. For what it's worth, the `http:` links above now automatically get upgraded to `https:` connections by the new S3 website hosting. Just noting that in case it means we should also change these links to be `https:` instead.
5. Looking at the website contents, I see also that https://spdx.org/rdf/spdx-terms-v2.2/ currently has a copy of the same v2.2 documents. Should I create a copy of this for 2.2.1?

**Comment by kestewart** [comment]
@swinslow - yes please, go ahead and create a 2.2.1 copyt of the terms on the website.

**Comment by swinslow** [comment]
Thanks @kestewart, https://spdx.org/rdf/terms/ is now updated to 2.2.1 and https://spdx.org/rdf/spdx-terms-v2.2.1/ is also valid now.

**Comment by goneall** [comment]
Resolved per comment above
