### ISSUE TITLE
Inconsistency in capitalization of SPDX Document

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#448]
This is an issue I contributed to when replacing SPDX file with SPDX document.

I was planning on creating a pull request to capitalize Document since it is a defined term, but then I realized there are many occurrences in the spec where SPDX document is lower case.

I can create a PR to change the upper case `SPDX Document` to `SPDX document` in all cases, but I wanted to check if this is preferred or would we rather have it be `SPDX Document`.  Note that most of the occurrences prior to my changes had lower cases.

I also noticed at least on inconsistency with `SPDX File` and `SPDX file` as well.

@kestewart @RexJaeschke Any opinions on whether we should:

- Change all `SPDX document` to `SPDX Document`
- Change all `SPDX Document` to `SPDX document`
- Leave it as is - don't worry about the inconsistency

**Comment by swinslow** [comment]
Thanks @goneall -- I'm putting together a PR for the issues noted in #454, which includes this one. 

In the absence of a preference for either one, I'm going to go ahead and change all of them to "SPDX document" -- if that isn't preferred, we can switch it back the other way.

**Comment by tsteenbe** [comment]
@goneall  @swinslow  As https://github.com/spdx/spdx-spec/pull/455 has been merged which believe addresses this issue we can close this issue.

**Comment by swinslow** [comment]
All set in the spec itself, though I think the ontology and JSON schema may still need to be fixed (if a fix is considered necessary -- I don't feel strongly either way if it won't be part of the published ISO document).

**Comment by goneall** [comment]
Thanks @swinslow !  I can copy/paste the updated definitions to the OWL ontology in a couple weeks.  I just created issue #459 to track.
