### ISSUE TITLE
Improve Package Home Page

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#450]
Package Home Page can have values an URI,  NONE or NOASSERTION but the cardinality of the field is optional, one.
Having NONE as an option could be omitted as the creator could simply omit the `PackageHomePage` from the SPDX Package.

**Comment by puneeth072003** [comment]
@tsteenbe I'd be more than happy to take up this issue

**Comment by goneall** [comment]
Resolved in 3.0 - closing this issue
