### ISSUE TITLE
Sidebar has very poor visibility

### ISSUE THREAD

**Issue by ericonr** [spdx/spdx-spec#452]
The issue appears in Qutebrowser, Firefox and Firefox mobile, so it doesn't seem to be due to any system theming. Light gray letters with a white background are nearly unreadable.

Screenshot: https://imgur.com/a/19UwuQ1

**Comment by decon-harsh** [comment]
Hey I am new in this community. I would love to take this up.

**Comment by letmaik** [comment]
Could this be fixed? It's really not legible.

**Comment by seabass-labrax** [comment]
@letmaik, @ericonr, thank you for bringing attention to this issue! I've made some edits to the styling for the specification page in pull request #574.

Here's a comparison between the current styling and the styling to be added:

## Before

![specification-before](https://user-images.githubusercontent.com/79224200/134386991-a142849b-4fc5-4cef-b651-c1a3721db5d8.png)

## After

![specification-after](https://user-images.githubusercontent.com/79224200/134387018-7b9c4744-7360-4a30-b19d-062b08d64857.png)

**Comment by letmaik** [comment]
@seabass-labrax Awesome, perfect! :)

**Comment by ericonr** [comment]
Looks much more readable, thanks!

**Comment by seabass-labrax** [comment]
Glad I could help! The improved contrast is now live on the specification at <https://spdx.github.io/spdx-spec/> :)

**Comment by ericonr** [comment]
That looks wonderful! Thanks a lot.
