### ISSUE TITLE
Problem with name (attributionText) and its format

### ISSUE THREAD

**Issue by Yash-Varshney** [spdx/spdx-spec#463]
https://github.com/spdx/spdx-spec/blob/6e9f36f5b0becb96172e54cdcd614a685b0b5e9a/examples/SPDXJSONExample-v2.2.spdx.json#L66

According to [package-attribution-text](https://spdx.github.io/spdx-spec/3-package-information/#323-package-attribution-text), the name of the above should be `attributionText` instead of `attributionTexts`.
Moreover, the data format should only be a string ( free form text that can span multiple lines. ), whereas here it is a string within a `list`.
If JSON follows the given format, please inform me otherwise do the necessary.

**Comment by Yash-Varshney** [comment]
@kestewart I would like to raise your attention towards it.
Thanks

**Comment by goneall** [comment]
@Yash-Varshney The cardinality for the package-attribution-text is optional one or many(`0..*`), so a list is appropriate.

For JSON and YAML, any list is made into a plural.  XML and RDF/XML use singular.

**Comment by Yash-Varshney** [comment]
Thanks @goneall for informing me about it, it will be helpful in designing its parsers.
I'm closing this issue.
