### ISSUE TITLE
Create v2.2/ directory for https://spdx.github.io/spdx-spec/

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#466]
Currently, https://spdx.github.io/spdx-spec/ is the link for the 2.2 version of the SPDX spec. This means that links to pages at /spdx-spec/ will become invalid when 2.2.1 is released, because 2.2.1 changes the names of a bunch of the pages for ISO purposes.

Is it possible to create https://spdx.github.io/spdx-spec/v2.2/ with a static copy of the 2.2 spec, so that we will be able to link directly to it now with links that won't change?

cc @kestewart

**Comment by kestewart** [comment]
@iamwillbar has been solving this as part of 2.3 release.    Closing this, as I think we've mostly got it sorted now.    Please reopen if you disagree.
