### ISSUE TITLE
Make checksums optional in next  spec

### ISSUE THREAD

**Issue by pombredanne** [spdx/spdx-spec#47]
Having checksums mandatory is very impractical and you often end up with SPDX docs with checksums that do not match what you redistribute by the bit making them useless in practice.
Having checksums is not a bad idea but making them mandatory is a very bad one IMHO and it makes creating valid SPDX document difficult without a good reason.

**Comment by pombredanne** [comment]
It also makes a document not reusable across versions of a codebase even if you only added one space to one of the files. I think the best is an enemy of the good here

**Comment by kestewart** [comment]
This is going to need discussion in tech team and legal team.

**Comment by mcjaeger** [comment]
I had also a problem with the overall package checksum, when I added the spdx document to the actual codebase of the project. The way I am seeing it now is that spdx documents are maybe not suited for being part of the distribution package, but maybe better put as metadata.

**Comment by goneall** [comment]
> I had also a problem with the overall package checksum

I have run into this issue when the package is pulled from a repository and is not "pre-packaged" in a neat archive file suitable for checksum creation.

**Comment by goneall** [comment]
Checksums are now optional in SPDX 3.0.  Closing this issue.
