### ISSUE TITLE
Allow byte range to be optional in Snippets

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#485]
Discussed on 2020-11-03 tech team call. Agreed to make byte range fields in Snippets to be optional, rather than mandatory. This makes it easier to use Snippets to model subfile-related data without making it required to specify the exact portion of a file that is being referenced.

The relevant field is currently 5.3 in v2.2 of the spec: https://spdx.github.io/spdx-spec/5-snippet-information/#53-snippet-byte-range

**Comment by kaushal-khurana-17** [comment]
I am a beginner at this issue can you help me. How to start it?

**Comment by kaushal-khurana-17** [comment]
Can you help me?

**Comment by goneall** [comment]
@kaushal-khurana-17 I would wait to work on this issue - we are finalizing a new format for the 3.0 version of the spec.  Once the new spec version is ready, we can work on the 3.0 related issues.

**Comment by goneall** [comment]
This is resolved in 3.0 - it is now optional
