### ISSUE TITLE
hasFiles fields in examples 

### ISSUE THREAD

**Issue by mmurto** [spdx/spdx-spec#487]
The example files contain fields under PackageInformation for files of the package, for example:

https://github.com/spdx/spdx-spec/blob/6b44f663463b6f351e264435baf9a5c3b302cd83/examples/SPDXJSONExample-v2.2.spdx.json#L91

https://github.com/spdx/spdx-spec/blob/6b44f663463b6f351e264435baf9a5c3b302cd83/examples/SPDXYAMLExample-2.2.spdx.yaml#L179-L182

https://github.com/spdx/spdx-spec/blob/6b44f663463b6f351e264435baf9a5c3b302cd83/examples/SPDXRdfExample-v2.2.spdx.rdf.xml#L909-L910

The ontology files and schema files also include the field:

https://github.com/spdx/spdx-spec/blob/6b44f663463b6f351e264435baf9a5c3b302cd83/ontology/SPDX-2.2-ontology.html#L473

https://github.com/spdx/spdx-spec/blob/6b44f663463b6f351e264435baf9a5c3b302cd83/schemas/spdx-schema.json#L295-L302

I'm currently trying to list the source files of a package in an SPDX document, for which the hasFiles field would seem to be a more lightweight option, but the spec seems to require listing these relationships in the Relationships section. Is the hasFiles approach valid SPDX, and if it is, can it be found in the spec?

**Comment by goneall** [comment]
The spec describes the `spdx:hasFile` property in the [File Information introduction section](https://spdx.github.io/spdx-spec/4-file-information/#4-file-information).

Using `hasFile` for the purpose of listing source files for a package would be appropriate and the preferred method.  Relationships could also be used, but they are more compute and memory intensive and harder to read for a human.

**Comment by mmurto** [comment]
> The spec describes the `spdx:hasFile` property in the [File Information introduction section](https://spdx.github.io/spdx-spec/4-file-information/#4-file-information).

Ah, thanks @goneall! I totally missed that!
