### ISSUE TITLE
SPDX-FileCopyrightText tag is too long

### ISSUE THREAD

**Issue by puitgfr** [spdx/spdx-spec#488]
Hello,
In most of my files, adding the `SPDX-FileCopyrightText` tag ends up with a line of more than 80 characters, e.g:
```;; SPDX-FileCopyrightText: 2018-2020 François Puitg <francois.puitg@univ-grenoble-alpes.fr>```
(ok, my email address is quite long, but I can't change it anyway, neither my name).
Even with recent files (no range of years), it's still 86 char wide.

Linters don't like that, and visual effect is not attractive, to say the least (and considering that this line is among the earliest one sees when opening the file).

Wouldn't it be possible that the spec permits the use of shorter tags (for instance: `SPDX-Copyright`)?

**Comment by zvr** [comment]
While you can put the correct SPDX tag in the file, I believe that all scanners out there (i.e., programs that extract information from source files) definitely handle lines with a usual copyright notice.

In other words, you can simply use

     ;; Copyright 2018-2020 François Puitg <francois.puitg@univ-grenoble-alpes.fr>

**Comment by puitgfr** [comment]
Thanks for your reply. Indeed [reuse](https://github.com/fsfe/reuse-tool), for instance, is happy with it. So this is what I ended up doing, but I would have preferred to stick with the spec and use the proper SPDX tag ; I guess one day scanners will deprecate the use of `Copyright ...`.

**Comment by swinslow** [comment]
Hi @puitgfr, thanks for your earlier comments on this. A bit of background for others as well:

The form for this tag was heavily discussed in mid-2019 as part of the lead-up to the SPDX 2.2 release. You can find details about the discussion in issue #122 and also in the [2019-07-11 legal team minutes](https://wiki.spdx.org/view/Legal_Team/Minutes/2019-07-11).

The upshot is that, although some folks (myself included, initially!) were in favor of taking the shorter `SPDX-Copyright:` approach, it was felt that a better approach would be to allow a general process for expressing Copyright statements as well as other information that can be populated into the File sections in SPDX documents. Based on that, SPDX 2.2 defined a generic mechanism for expressing these File tags; see [appendix IX of the spec](https://spdx.github.io/spdx-spec/appendix-IX-file-tags/) for more details.

**Comment by Freso** [comment]
The “[appendix IX of the spec](https://spdx.github.io/spdx-spec/appendix-IX-file-tags/)” link is dead. Was that meant to refer to [Annex I](https://spdx.github.io/spdx-spec/v2.2.2/diffs-from-previous-editions/) (I being the 9th/XIth letter)?
