### ISSUE TITLE
Generate the license list chapter

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#5]
@tsteenbe Following up on the tech call on 10 July, I updated the license generation tools to create a markdown page for the license list: https://github.com/spdx/license-list-data/blob/master/licenses.md

To make this work for the license-list-data repository, the links and the text are different from the license list chapter itself.  You are welcome to use the licenses.md to help generate the chapter text, but it may be easier to just generate the page using a node.js script using a well structured JSON file as input.

I would recommend using the JSON table of contents page at https://github.com/spdx/license-list-data/blob/master/json/licenses.json and https://github.com/spdx/license-list-data/blob/master/json/exceptions.json.  The structure and tag names for these pages are stable.  If you would like to get the license list for a specific version, checkout the tag by the version name.

**Comment by kestewart** [comment]
2.7 license list will be incorporated into 2.1.1 so having this,  would be helpful.

**Comment by kestewart** [comment]
see #6
