### ISSUE TITLE
Example in clause 10.2.3 should be the same in Tag and RDF

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#515]
Tag:

    ExtractedText: <text>This software is licensed under the Beer License.</text>

RDF:

    <ExtractedLicensingInfo rdf:about="licenseRef-Whiskeyware">
          <licenseId>LicenseRef-Whiskeyware</licenseId>
          <extractedText>This software is licensed under the WHISKEY-WARE LICENSE.</extractedText>
     </ExtractedLicensingInfo>

The RDF should also be "Beer License"

**Comment by kestewart** [comment]
This has been fixed in 10.2.3 in 2.3 release
