### ISSUE TITLE
JSON schema doesn't have a document namespace

### ISSUE THREAD

**Issue by nishakm** [spdx/spdx-spec#520]
I am trying to convert an example of external document reference (https://github.com/swinslow/spdx-examples/blob/master/example6/spdx/example6-bin.spdx) into JSON format and I can't seem to find the equivalent for "DocumentNamespace". Is there some other way of describing this field?

**Comment by swinslow** [comment]
Hi @nishakm, looking at the [sample JSON file](https://github.com/spdx/spdx-spec/blob/cd0876094cfe96e5ecf5fb04c61244d5e077673a/examples/SPDXJSONExample-v2.2.spdx.json), I think the equivalent for the tag-value field `DocumentNamespace` in JSON is the property `spdxDocument`:

https://github.com/spdx/spdx-spec/blob/cd0876094cfe96e5ecf5fb04c61244d5e077673a/examples/SPDXJSONExample-v2.2.spdx.json#L18-L20


The format is the same, as a URI which I'm assuming is used as the document's namespace. It looks like this comes from the name of the field used in the RDF format (see [section 2.5.6 of the 2.2 spec](https://spdx.github.io/spdx-spec/2-document-creation-information/#25-spdx-document-namespace)).

**Comment by SamuraiAku** [comment]
Maybe the schema should be changed to documentNamespace instead?  That's much clearer.

**Comment by nishakm** [comment]
Does this look good to you? https://github.com/swinslow/spdx-examples/blob/d384fb04402c55e6be9bc98b3f69bf7674bf092c/example7/spdx/example7-bin.spdx.json

**Comment by SamuraiAku** [comment]
> Hi @nishakm, looking at the [sample JSON file](https://github.com/spdx/spdx-spec/blob/cd0876094cfe96e5ecf5fb04c61244d5e077673a/examples/SPDXJSONExample-v2.2.spdx.json), I think the equivalent for the tag-value field `DocumentNamespace` in JSON is the property `spdxDocument`:
> 
> https://github.com/spdx/spdx-spec/blob/cd0876094cfe96e5ecf5fb04c61244d5e077673a/examples/SPDXJSONExample-v2.2.spdx.json#L18-L20
> 
> The format is the same, as a URI which I'm assuming is used as the document's namespace. It looks like this comes from the name of the field used in the RDF format (see [section 2.5.6 of the 2.2 spec](https://spdx.github.io/spdx-spec/2-document-creation-information/#25-spdx-document-namespace)).


@swinslow actually what you are looking at there is inside the externalReferences property.  That is referring to the namespace of that external document. Although by my reading of the spec, that's not right. The external reference (section 3.21 of the spec) does not even allow for an SPDX document to be one of the things to be referenced. So that looks like another error in the schema to me.

**Comment by SamuraiAku** [comment]
> Does this look good to you? https://github.com/swinslow/spdx-examples/blob/d384fb04402c55e6be9bc98b3f69bf7674bf092c/example7/spdx/example7-bin.spdx.json

You've got documentNamespace which is good.  But I just tried running it through the SPDX online tool and it errors out for me with something else:
> Analysis exception processing SPDX file: string is not a valid SPDX class

**Comment by SamuraiAku** [comment]
This issue is resolved in #528

**Comment by goneall** [comment]
> I just tried running it through the SPDX online tool and it errors out for me with something else

I identified the issue - it is an inconsistency in how creator information is represent in JSON.  See https://github.com/swinslow/spdx-examples/issues/34
