### ISSUE TITLE
Conversion of tag-value to JSON creates a field not in the schema

### ISSUE THREAD

**Issue by SamuraiAku** [spdx/spdx-spec#527]
When I run the [official tag-value example file](https://github.com/spdx/spdx-spec/blob/v2.2/examples/SPDXTagExample-v2.2.spdx) through the online converter tool to JSON, it turns the tag "DocumentNamespace" into the JSON field "documentNamespace".  Which makes a lot of sense, except that field does not exist in the [JSON schema](https://github.com/spdx/spdx-spec/blob/v2.2/schemas/spdx-schema.json).  Instead it's believed that the field "spdxDocument" is the intended field for the namespace.  See this [issue in SPDX-specs](https://github.com/spdx/spdx-spec/issues/520).

Personally I think it would be clearest if the schema was changed to match what the tool is putting out in this instance, but either way this is a discrepancy.

**Comment by goneall** [comment]
Resolved with PR #528
