### ISSUE TITLE
JSON schema is missing SPDXID property at the Document level

### ISSUE THREAD

**Issue by SamuraiAku** [spdx/spdx-spec#529]
This is defined in the SPDX spec, section 2.3.  I see it defined in the example files, but it is not in the schema.

**Comment by goneall** [comment]
Thanks @SamuraiAku - I updated PR #528 to include this.  Please let me know if you see any other issues.  BTW - I plan on adding more detail in the the schema over the next week.  I'll update the same PR as the work progresses.

**Comment by goneall** [comment]
Resolved with PR #528
