### ISSUE TITLE
JSON schema is missing the spdxElementId element from relationships

### ISSUE THREAD

**Issue by SamuraiAku** [spdx/spdx-spec#531]
Describing a relationship requires three parts (section 7.1 of the spec). For example

> SPDXRef-DOCUMENT DESCRIBES SPDXRef-MyPkg

The schema has the second and third parts of this relationship (relationshipType and relatedSpdxElement) but not the first (spdxElementId going by the available example).

**Comment by goneall** [comment]
PR #528 has been updated to resolve this issue.

Thanks again @SamuraiAku for the extensive reviews!

Feel free to review the [updated schema](https://github.com/spdx/spdx-spec/blob/updatejsonschema/schemas/spdx-schema.json) and let me know if you see any additional issues.

**Comment by davaya** [comment]
The relationship does have three parts:
> SPDXRef-DOCUMENT DESCRIBES SPDXRef-MyPkg

But relationships can be serialized in two ways:
1) by including relationshipType and relatedSpdxElement in the spdxElement (as originally defined), or
2) by creating a separate list of 3-tuples (as this patch does)

In my opinion creating a separate list of 3-tuples is unnecessarily complicated when the identical semantics is represented by including an element's relationships within the element.

Note that for better or worse, the class model currently defines Relationship as an Element, which means that it has a required id plus all optional element properties.  So it's not a 3-tuple; it's potentially a 20-tuple with creation information, licenses, a list of annotations, relationships between relationships, and on and on and on.

When we update the schema to include all of the element baggage in relationships, I believe that the original structure (include the list of relationships IDs in the spdxElement) is cleaner than including spdxElement in each relationship.

**Comment by goneall** [comment]
Resolved with PR #528
