### ISSUE TITLE
Ambiguous field names in JSON version of SPDX generated 

### ISSUE THREAD

**Issue by Xenos5282** [spdx/spdx-spec#538]
In the final JSON generated, there are three different name-value pairs named as "name". This doesn't seem to comply with the SPDX standard, and it lacks precision. Examples are from the [sample JSON](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXJSONExample-v2.2.spdx.json) given here.

- In the name:value pair "name" : "Example_Document_Name", “name” should be changed to "documentName". 
Eg: `"name" : "SPDX-Tools-v2.0"` should be `"documentName" : "SPDX-Tools-v2.0"`

- Within the array hasExtractedLicensingInfos : [ ], "name" : "Example_license_name" is repeated for each licenseId, “name” should be changed to “licenseName”.
Eg: `"name" : "CyberNeko License"` should be `"licenseName" : "CyberNeko License"`

- under the “packages” element, “name” should be “PackageName”.
Eg: ` "name" : "glibc"` should be `"packageName" : "glibc"`

**Comment by kestewart** [comment]
Looks like this has been fixed now.   Please reopen if this is not the case.
