### ISSUE TITLE
Ontology should not redefine standard OWL and RDFS properties

### ISSUE THREAD

**Issue by rivettp** [spdx/spdx-spec#539]
There is no need to redefine the standard elements rdfs:comment, owl:deprecatedClass, owl:deprecatedProperty, owl:qualifiedCardinality - and in fact, the way it's done can cause problems in applications importing spdx along with other ontologies: specifically my company had a fairly hard to track down reasoning problem caused by the redefinition of rdfs:comment.
 
Further, OWL does not even have owl:deprecatedClass, owl:deprecatedProperty - it has the property owl:deprcated and the classes owl:DeprecatedClass, owl:DeprecatedProperty (notice capital D).

**Comment by goneall** [comment]
I don't believe there was an intent to redefine any of these terms.  This is likely an error in the OWL file which include references to those terms.

@rivettp Could you create a pull request which corrects these errors for review?

**Comment by goneall** [comment]
Since resolving this would break some of the SPDX 2.X tooling, I'm moving this issue to 3.0.

**Comment by goneall** [comment]
This is now resolved with the 3.0 release - we've basically moved to SHACL for validation.
