### ISSUE TITLE
Problem in ontology definition of ns:term_status

### ISSUE THREAD

**Issue by rivettp** [spdx/spdx-spec#540]
As defined it does not make sense: it's defining ns:term_status as an annotation property but then it's defining a triple with itself as subject with value "stable".
I think the intent is to assert that the spdx ontology is itself stable. 
In which case use the property with the ontology as the subject
So you'd have:

<owl:Ontology rdf:about="http://spdx.org/rdf/terms">
    <ns:term_status>stable<ns:term_status> ;

**Comment by goneall** [comment]
I'm not sure what the intent was - but it definitely looks like an error.  It can probably be safely removed.

**Comment by goneall** [comment]
This was resolved with the recent schema updates
