### ISSUE TITLE
Specifying strong hashes (e.g. SHA-256+) for `ExternalDocumentRef` in SPDX 2.2

### ISSUE THREAD

**Issue by johnterickson** [spdx/spdx-spec#571]
It seems that `ExternalDocumentRef` requires `SHA-1` as the checksum and doesn't provide for an option to specify additional hashes (e.g. with hash types that are not [broken](https://shattered.io/).

**Is there a canonical way of doing so?** 

@iamwillbar and I were considering having a separate file entry that matches the (URI, SHA-1) tuple in the `ExternalDocumentRef` but also provides `SHA-256`.

Some related discussions and PRs:
https://github.com/spdx/spdx-examples/pull/36/files
https://github.com/spdx/spdx-examples/issues/31

**Comment by johnterickson** [comment]
Ideally, we'd have a consistent way to connect the `ExternalDocumentRef` and the `File`.  Maybe `DESCRIBES`? https://spdx.github.io/spdx-spec/7-relationships-between-SPDX-elements/

**Comment by iamwillbar** [comment]
`DESCRIBES` is the other direction, you'd want to use `DESCRIBED_BY`. The proposal here would be that if **Document A** wants to reference **Document B** then:

1. **Document A** has an `ExternalDocumentRef` to **Document B** that includes the SHA1 hash.
2. **Document A** contains a `File` representing **Document B** that has both a SHA1 hash and the preferred stronger hashes (I'd recommend at least a SHA256 for consistency with SPDX 3.0). This should have a **FileType** of `SPDX` and a unique `SPDXID`.
3. **Document A** contains a `Relationship` of type `DESCRIBED_BY` from `[Document B Namespace]#SPDXRef-Document` to `[Document A Namespace]#SPDXRef-File-[SPDXID from Step 2]`.

@goneall thoughts?

**Comment by goneall** [comment]
@iamwillbar - I agree with your analysis and reccomendation above.

**Comment by jeff-schutt** [comment]
The `ExternalDocumentRef` `[Checksum]` value in [Section 6.6.1 Table 7](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/document-creation-information.md#66-external-document-references-field-) refers back to the list of supported checksum algorithms described in the `FileChecksum` field of File Information [Section 8.4](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/file-information.md#84-file-checksum-field-). 

So updates to the list of acceptable file checksum algorithms, as requested in https://github.com/spdx/spdx-spec/issues/626, should also resolve this issue.

Could be worth adding @iamwillbar's proposal to an Appendix to the Spec where a Best/Leading/Recommended Practices are documented.

**Comment by jiaw37** [comment]
[manifest.spdx.zip](https://github.com/spdx/spdx-spec/files/8354445/manifest.spdx.zip)
Attached is a sample of the json, please verify if this looks right? I added comments to the json to signify the parts

**Comment by kuro6** [comment]
@jiaw37 are you waiting for input from anyone in particular? Do you have all the info you need to close this ticket?

**Comment by jiaw37** [comment]
@iamwillbar there is some confusion with step 3. 
I think it should read 
Document A contains a Relationship of type DESCRIBED_BY from `[Document A Namespace]`#SPDXRef-Document to `[Document B Namespace]`#SPDXRef-File-[SPDXID from Step 2]
Where Document A and Document B are flipped. because the SPDXID from step 2, is the id for Document B, not Document A. 

The following is an example we have came up with, please let me know if it looks correct

In the File Array 
```
{
      "fileName": "./externalmanifest.spdx.json",
      "SPDXID": "SPDXRef-File--externalmanifest.spdx.json-FA85D11F1A249A36E850690D7358E8A98C6143D4",
      "checksums": [
        {
          "algorithm": "SHA256",
          "checksumValue": "a815923eb89c9d25c04bdeeba7fd43eb19b66f0eaf45c2155d982dff8155d4cf"
        },
        {
          "algorithm": "SHA1",
          "checksumValue": "fa85d11f1a249a36e850690d7358e8a98c6143d4"
        }
      ],
      "licenseConcluded": "NOASSERTION",
      "licenseInfoInFiles": [
        "NOASSERTION"
      ],
      "copyrightText": "NOASSERTION",
      "fileTypes": [
        "SPDX"
      ]
}
```

In the externalDocumentRefs array 
```
{
      "externalDocumentId": "DocumentRef-nameab-1.0-fa85d11f1a249a36e850690d7358e8a98c6143d4",
      "spdxDocument": "https://random/name/1.0/uR06mWBqXkOtYxrJKmIUab",
      "checksum": {
        "algorithm": "SHA1",
        "checksumValue": "fa85d11f1a249a36e850690d7358e8a98c6143d4"
      }
}
```

In the relationship array, one thing to keep in mind, when `spdxElementId` and `relatedSpdxElement` are switched, it fails the spdx validation tool, because it is looking for the spdxElementId in the file array. 
```
{
      "relationshipType": "DESCRIBED_BY",
      "relatedSpdxElement": "SPDXRef-DOCUMENT",
      "spdxElementId": "SPDXRef-File--externalmanifest.spdx.json-FA85D11F1A249A36E850690D7358E8A98C6143D4"
}
```

**Comment by kestewart** [comment]
This needs further discussion, after discussion with Gary we're not going to block the 2.3 release on this.    @iamwillbar can you get with @johnterickson and come up with a recommendation for 3.0.

**Comment by goneall** [comment]
This is no longer applicable for 3.0 - closing
