### ISSUE TITLE
Describing patch installers

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-spec#582]
I'm working on an SPDX document to describe a "patch installer" that will add, remove, or update components in an existing installation. The `FILE_ADDED`, `FILE_MODIFIED`, and `FILE_DELETED` relationships refer to files, is there any reason they couldn't be used (or expanded) to relate packages with a patch?

For example:

```
Package Software-1.0
CONTAINS Package ComponentA-1.0
CONTAINS Package ComponentB-1.0

Package Software-1.0-Patch1
PATCH_FOR Package Software-1.0
CONTAINS Package ComponentA-1.1
FILE_DELETED Package ComponentA-1.0
FILE_ADDED Package ComponentA-1.1
FILE_DELETED Package ComponentB-1.0
```

This would intend to describe a package installer that upgrades an existing Software-1.0 installation by upgrading ComponentA from 1.0 to 1.1 and removing ComponentB.

**Comment by goneall** [comment]
I don't see any issues with using the `FILE_ADDED`, `FILE_MODIFIED`, and `FILE_DELETED` for patch installers.

I don't think we had that use case documented for 2.0 - once I get the use cases moved over to a Github repo, perhaps we can add this to the list.

**Comment by swinslow** [comment]
@iamwillbar If you have an example (or multiple examples!) of SPDX documents demonstrating the patching use case for SPDX 2.2, I'd be very happy to add them to https://github.com/spdx/spdx-examples.

I'd created an issue (https://github.com/spdx/spdx-examples/issues/33) a while back to add something along these lines, would be great to document it there -- and/or, to work through the specifics and options with input from others.

**Comment by kestewart** [comment]
From call,  there is some interest in getting this added to 2.3 releationship set, but we need to understand better FILE_DELETED use case a bit more.    This would be a good thing to get codified into a best practice and use case description.

**Comment by goneall** [comment]
@kestewart @iamwillbar Is this a request to change/add relationships in the spec?  If so, can we get a PR put in for the change?

**Comment by kestewart** [comment]
FILE_DELETED is relationship in 2.3 set.   see: https://spdx.github.io/spdx-spec/v2.3-RC1/relationships-between-SPDX-elements/
