### ISSUE TITLE
clarify PackageName field

### ISSUE THREAD

**Issue by AnnieJovitha** [spdx/spdx-spec#585]
I have a question on 'PackageName' field, If I understand the spdx spec, for the package name for  'spring-boot-actuator' package is 'org.springframework.boot/spring-boot-actuator'  is this right or not?

PackageName: org.springframework.boot/spring-boot-actuator
PackageVersion: 2.1.1.RELEASE
PackageSummary: spring-boot-actuator
PackageHomePage: http://projects.spring.io/spring-boot/
ExternalRef: PACKAGE-MANAGER purl pkg:maven/org.springframework.boot/spring-boot-actuator@2.1.1.RELEASE

is the above PackageName the right way to use it? or should it be 'spring-boot-actuator'

**Comment by kestewart** [comment]
Closing this as I don't think there's further action to take in the spec.   Please reopen if you disagree.
