### ISSUE TITLE
Relationship for the root component

### ISSUE THREAD

**Issue by AnnieJovitha** [spdx/spdx-spec#587]
I have a question regarding the relationship for the root component or the package itself. I used the spdx-sbom-generator tool to create the spdx for the project. I see after the creation the information of the main package itself followed by the relationship listing all the 1000+ components being listed with the 'DEPENDS_ON' relation. Does this relationship of 1000+ information adds value? Because the following section also lists alls the individual packages with their relationship with other packages.

SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: test-spdx-action-0.1.0
DocumentNamespace: http://spdx.org/spdxpackages/test-spdx-action-0.1.0
Creator: Tool: **spdx-sbom-generator-source-code**
Created: 2021-10-19T06:02:27Z

##### Package representing the test-spdx-action

PackageName: **test-spdx-action**
SPDXID: SPDXRef-Package-test-spdx-action-0.1.0
PackageVersion: 0.1.0
PackageSupplier: Organization: test-spdx-action
PackageDownloadLocation: NONE
FilesAnalyzed: false
PackageChecksum: 
PackageHomePage: NOASSERTION
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: NOASSERTION
PackageCopyrightText: NOASSERTION
PackageLicenseComments: NOASSERTION
PackageComment: NOASSERTION

**Relationship: SPDXRef-Package-test-spdx-action-0.1.0 DEPENDS_ON SPDXRef-Package-dns-equal-1.0.0 
Relationship: SPDXRef-Package-test-spdx-action-0.1.0 DEPENDS_ON SPDXRef-Package-postcss-reduce-initial-4.0.3
Relationship: SPDXRef-Package-react-dev-utils-11.0.1 DEPENDS_ON SPDXRef-Package-babel.code-frame-7.10.4 
Relationship: .........** 
.........

##### Package representing the babel/code-frame

PackageName: babel/code-frame
SPDXID: SPDXRef-Package-babel.code-frame-7.10.4
PackageVersion: 7.10.4
PackageSupplier: Organization: babel/code-frame
PackageDownloadLocation: https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.10.4.tgz
FilesAnalyzed: false
PackageChecksum: SHA256: 0d32786bf46182100be9a46eaa104021ef5c235e45428dea37ad4bb5cfc5e193
PackageHomePage: https://babeljs.io/
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: NOASSERTION
PackageCopyrightText: NOASSERTION
PackageLicenseComments: NOASSERTION
PackageComment: NOASSERTION

Relationship: SPDXRef-Package-babel.code-frame-7.10.4 DEPENDS_ON SPDXRef-Package-babel.highlight-7.10.4 
......
...

**Comment by goneall** [comment]
I'm not familiar with the spdx-sbom-generator code myself, but from your description it looks like the tool is including both direct and indirect relationships to the top level package.

If my understanding is correct, the specification allows this approach since the relationships are valid, even though they are redundant (assuming you havehave tools that traverse the full graph of relationships).

We do not have a [best practices](https://wiki.spdx.org/view/Technical_Team/Best_Practices) documented for the case when you have indirect relationships.

My personal opinion is a document, within itself, should not include redundant relationships just to keep the size of the document more reasonable.  All the tools I am aware of traverse the indirect relationships - so these are not needed.  I don't feel strongly about this opinion and am very open to other views.

**Comment by AnnieJovitha** [comment]
Agree with your view. Better to have a 'best practises' page updated/ to think on this question. is it possible to get the attention of the team to address this in the  'best practises' document?

Is it possible to get involved in discussion from the team? (I also have quite lot of questions in regards to other fields)

**Comment by goneall** [comment]
> is it possible to get the attention of the team to address this in the 'best practises' document?

We're always looking for volunteers to help document these.  @seabass-labrax - I was wondering if we should move these out of the wiki into a repo to make it easier to collaborate.  What do you think?

> Is it possible to get involved in discussion from the team? (I also have quite lot of questions in regards to other fields)

Absolutely - see the [tech team participate page](https://spdx.dev/participate/tech/) for various ways to connect with the team.  In addition to issues against the spec (like this), the email distribution list and weekly tech calls are pretty effective.

**Comment by AnnieJovitha** [comment]
Thank you @goneall, I will get in touch with the team.

**Comment by seabass-labrax** [comment]
@AnnieJovitha, the SPDX Tech Meeting is today if you're interested! :)

@goneall, I'd certainly agree that GitHub would be a good place for the information. There's quite a lot of information that probably isn't relevant to SPDX 2.2 (or 3.0 for that matter), so it may need to be rewritten. An appendix to the specification might be suitable, as then we could have it in the existing MkDocs site. It would be best to track this on the Outreach Team mailing list, I think - please could you start a thread there? Thanks :)
