### ISSUE TITLE
Contradiction in Clause 5.2.3

### ISSUE THREAD

**Issue by Jayman2000** [spdx/spdx-spec#593]
>[5.2.3 File information section](https://spdx.github.io/spdx-spec/composition-of-an-SPDX-document/#523-file-information-section)
>One instance of the File Information [section] shall exist for each file in the software package.
>[…]
>Cardinality: Optional, one or many.

“shall” and “optional” are basically opposites.

**Comment by kestewart** [comment]
Agreement to clean up the wording here in 2.3 from call.   Pull request welcome.

**Comment by rnjudge** [comment]
I can try to help with this.

**Comment by kestewart** [comment]
@nishakm to review the PR and check.

**Comment by nishakm** [comment]
Is the change just `s/shall/may`? I can submit a PR for this. Is it targeted to 2.3?

**Comment by Jayman2000** [comment]
> @Jayman2000 can you clarify the contradiction -- does it still exist?

I can still find it [here](https://github.com/spdx/spdx-spec/blob/development/v2.3/chapters/composition-of-an-SPDX-document.md#523-file-information-section-).

Hopefully, this will clarify why I think this is a contradiction:

> One instance of the file information shall exist for each file in the software package.

I’m assuming here that a word was accidentally left out and that the author meant “one instance of the file information _section_”. To me, that quote means that every SPDX document needs to have at least one file information section instance because every SPDX document describes at least one software package.

> Cardinality: Optional, one or many.

To me, that quote means that you could create an SPDX document with zero file information section instances. So which one is it? Are you allowed to have zero or do you need to have at least one?

Now that I’m rereading it, I’m realizing that there’s another way you could interpret this clause. You could interpret it as “you need to have one file information section instance per file per package information section instance, but you can have zero file information section instances because you can have zero package information sections instances.”

---

> According to https://github.com/spdx/spdx-spec/blob/development/v2.3/chapters/file-information.md file name and file SPDX identifier, at least some of `File Information` fields are required (i.e. file field name, file SPDX identifier, etc). There are a few descriptors that are not required (i.e. `File type field`), but at least _some_ file information is required which seems appropriate for the description using `shall exist`.

Yes, but those fields are required inside file information section instances. This issue is about whether or not file information section instances are required, not about what each of them must contain
