### ISSUE TITLE
Looking for JSON SPDX SBOM containing all of the NTIA minumum element fields

### ISSUE THREAD

**Issue by rjb4standards** [spdx/spdx-spec#608]
We are just beginning to code up the JSON parse logic to extract the NTIA minimum elements, but the examples online are missing some of the NTIA minimum elements in some packages. Does anyone have a complete JSON SPDX example to share that contains all of the NTIA minimum elements? 
Will happily sign an NDA if needed.

Thanks,

Dick Brooks
Lead Software Engineer for SAG-PM (TM) at Reliable Energy Analytics, LLC.

**Comment by kestewart** [comment]
Closing this as the NTIA minimum elements is now documented in 2.3 see: https://spdx.github.io/spdx-spec/v2.3-RC1/how-to-use/#k2-satisfying-ntia-minimum-elements-for-an-sbom-using-spdx
