### ISSUE TITLE
JSON schema does not support PERSISTENT-ID category of external references

### ISSUE THREAD

**Issue by coderpatros** [spdx/spdx-spec#612]
The schema only supports `[ "OTHER", "SECURITY", "PACKAGE_MANAGER" ]` for reference category.

Relevant section https://github.com/spdx/spdx-spec/blob/2be70fcdf33c7e54290c17924a2b471d87afa0f0/schemas/spdx-schema.json#L340-L344

**Comment by seabass-labrax** [comment]
Hello @coderpatros; thank you for opening this issue! I've made pull request #613 to fix this. Happy Christmas! :smiley::christmas_tree::snowman_with_snow:

**Comment by goneall** [comment]
Resolved with PR #613
