### ISSUE TITLE
Inconsistencies for external reference categories in JSON schema

### ISSUE THREAD

**Issue by coderpatros** [spdx/spdx-spec#618]
Just grabbed the latest JSON schema and noticed that there is inconsistencies with the spec and usage of underscores and hyphens.

The values used for external reference categories are `"OTHER", "SECURITY", "PACKAGE_MANAGER", "PERSISTENT-ID"`

In the SPDX spec they are `SECURITY | PACKAGE-MANAGER | PERSISTENT-ID | OTHER`

**Comment by goneall** [comment]
@coderpatros Good catch!  I just created a PR to update PERSISTENT-ID to use underscores.

We decided to translate all dashes to underscores in the JSON format for enumerations to be consistent with some programming languages.

**Comment by coderpatros** [comment]
Thanks @goneall

**Comment by kestewart** [comment]
@goneall link to PR?   can this be closed?

**Comment by goneall** [comment]
Resolved with commit 04068cb2ef5fc25003e5c266468861940f08f8d4

**Comment by goneall** [comment]
Note that PR #783 updates the examples to be consistent with the updated schema
