### ISSUE TITLE
Relationship for repackaging

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-spec#620]
I'm helping design an SPDX document for a scenario where a build produces a directory of binaries (for example, Package-BuildOutput) and different subsets of those binaries are used to create installers (for example, Package-Installer-English and Package-Installer-Japanese).

We'd like to relate the installer packages back to the build output package to help understand the lineage of the files in the packages. I see three relationships that could be used:
* `GENERATED_FROM` - the installer package was generated from the build output package
* `VARIANT_OF` - the installer package is a variation of the build output package
* `PACKAGE_OF` - the installer package is a package of the contents of the build output package

I lean towards the installers being `GENERATED_FROM` since there is a transformation process to go from the build output to installer. `VARIANT_OF` feels like it is more suited for peers in the lineage (for example, the language installers could be `VARIANT_OF` each other) and `PACKAGE_OF` feels more appropriate when taking the whole package and repackaging it.

Thoughts?

**Comment by goneall** [comment]
Although I use `GENERATED_FROM` more for the relationship between source files and compiled binaries, I tend to agree that it also makes sense in the relationship between the build output and the install package.  A close second would be the `PACKAGE_OF` the the installer is packaging the output of the build process for distribution.   I agree `VARIANT_OF` is more of a peer relationship.

**Comment by iamwillbar** [comment]
Thanks for the feedback!
