### ISSUE TITLE
Support additional file checksum algorithms

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#626]
The following checksum algorithms are in the CycloneDX spec.  Adding this to SPDX would enable higher fidelity translations between the 2 formats:

"SHA3-256"
"SHA3-384"
"SHA3-512"
"BLAKE2b-256"
"BLAKE2b-384"
"BLAKE2b-512"
"BLAKE3"

**Comment by kestewart** [comment]
Reviewed and this has been fixed.
