### ISSUE TITLE
Download location should recommmend a fully qualified git ref, not a bare tag or branch name

### ISSUE THREAD

**Issue by MarkLodato** [spdx/spdx-spec#636]
In git, a bare `<refname>` (e.g. `main`) can refer to a tag or a branch. If the name refers to both, it is ambiguous what it refers to; see [gitrevisions(7)](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitrevisions.html). Some tools use the tag, while others (e.g. `git checkout`) use the branch.

In the SPDX "Package download location field", the field `[@<revision_tag_or_branch>]` is undocumented. For git, most reader would assume it means a bare tag or branch name, e.g. `main` or `v1.2.3`. Unfortunately that is ambiguous as noted above.

In order to make the download location fully unambiguous, I suggest explaining this field and recommending that the full `refs/heads/<branch>` or `refs/tags/<tag>` be used, rather than a bare `<branch>` or `<tag>`. This avoids a problem in the case where someone accidentally (or intentionally!) creates a tag that shadows a branch, or vice versa.

**Comment by kestewart** [comment]
From call,  there's desire to to include this in 2.3, but we need to make this a non breaking change, so will introduce a new keyword.

**Comment by kestewart** [comment]
We don't have a volunteer at this point to generate a PR, so moving it forward to resolve as part of 3.0

**Comment by ivanayov** [comment]
I realised I've written the PR description to automatically close this. 
Should we reopen or bring the [discussion](https://github.com/spdx/spdx-spec/pull/703#discussion_r888102595) to a new issue?

**Comment by MarkLodato** [comment]
I suggest reopening this one to resolve. I'll send a PR to address.

_From @ivanayov in https://github.com/spdx/spdx-spec/pull/703#discussion_r890316762:_
> Regarding `<describeOutput>`, `<rev>~[<n>]`, and/or `<rev>^[<n>]`, I think we would definitely like to allow, given that:
> 
> * contents of a branch might change over time
> * in case the build is cut-off on such a reference, it's better if the sbom reflects that
> 
> `<rev>:<path>` - not sure if this should be encouraged. Do you know any good example? The only reason to allow that IMO is if this is anyway how the build is created and we want that information to be visible. Which in the other hand might be a good enough reason to allow? Same with `<rev>^{<type>}` / `<ref>^{}` - I cannot think of a practical use-case to reference a build to that, but if you know any example, this might make sense.
> 
> Absolutely agree on the last 3.

So then I suggest we just say that this is interpreted as a `<rev>`, but the last 3 are disallowed.
