### ISSUE TITLE
How to identify a SPDX component from external?

### ISSUE THREAD

**Issue by tschmidtb51** [spdx/spdx-spec#646]
Dear colleagues,

I was looking for a way to identify a single component of and SPDX SBOM in another document (e.g. a CSAF one). I have a hunch that it works this way:

```
https://document.namespace#SPDXRef-something
```

Is that correct? If so, is that specified somewhere and could you please point me to that location?

**Comment by tschmidtb51** [comment]
This is related to a CSAF issue as I was looking how SPDX is doing what is called a [bom-link in CylconeDX](https://cyclonedx.org/capabilities/bomlink/). See https://github.com/oasis-tcs/csaf/issues/407#issuecomment-1073745911 as example.

**Comment by goneall** [comment]
> Is that correct? If so, is that specified somewhere and could you please point me to that location?

This is correct for the RDF serialization format.

It is documented in the [SPDX Document namespace field](https://spdx.github.io/spdx-spec/document-creation-information/#65-spdx-document-namespace-field).

The tag/value format does not implement any direct linking, but you can identify the external references by their use of the [External Document Reference](https://spdx.github.io/spdx-spec/document-creation-information/#66-external-document-references-field).  This field contains the external document's namespace which can be used to correlate to and verify the external tag/value document containing the element being referenced.

@tschmidtb51 if you feel the documentation doesn't describe this clearly enough, pull requests to help clarify are welcome.

**Comment by tschmidtb51** [comment]
@goneall Could you please also check, that https://github.com/oasis-tcs/csaf/issues/484#issuecomment-1077745182 is correct?

**Comment by goneall** [comment]
> Just to make sure:
> 
> I would use `https://swinslow.net/spdx-examples/example4/main-bin-v2#SPDXRef-libc` to identify the `libc` as used in [this binary](https://github.com/spdx/spdx-examples/blob/7b78ca07e64490cff7817593b9fa83c35db59dd7/example4/spdx/example4-bin.spdx#L48-L55).
> 
> And I would use `https://swinslow.net/spdx-examples/example7/hello-imports#SPDXRef-go-module-rsc.io/quote` to identify [this module](https://github.com/spdx/spdx-examples/blob/7b78ca07e64490cff7817593b9fa83c35db59dd7/example7/spdx/example7-third-party-modules.spdx.json#L30-L38).
> 
> Correct?

Correct

**Comment by goneall** [comment]
> Could you please also check, that https://github.com/oasis-tcs/csaf/issues/484#issuecomment-1077745182 is correct?

@tschmidtb51 I'm don't know enough about the CSAF spec to verify overall correctness, but the URI's look correct.

**Comment by tschmidtb51** [comment]
> > Could you please also check, that [oasis-tcs/csaf#484 (comment)](https://github.com/oasis-tcs/csaf/issues/484#issuecomment-1077745182) is correct?
> 
> @tschmidtb51 I'm don't know enough about the CSAF spec to verify overall correctness, but the URI's look correct.

Thanks for the confirmation. From my perspective, this question was solved and the issue can be closed.
