### ISSUE TITLE
Question: Is SPDX 3.0 backwards compatible with 2.x ?

### ISSUE THREAD

**Issue by hectorj2f** [spdx/spdx-spec#655]
We're thinking to support SPDX 3.0 draft version although we've realized that the v3.0 milestone would happen on July. So our first question comes related to the backwards compatibility between versions. We have SPDX clients that produce v3.0 and v2.2 at the moment. 
Also we're interested on understanding whether the current "draft" is stable enough to start adopting it, meaning if there are expected breaking changes. Thanks in advance.

**Comment by goneall** [comment]
Getting back to this issue - we are now (finally) getting ready for the release of SPDX 3.0.

You can find the spec [here ](https://spdx.github.io/spdx-spec/v3.0/) and in the development/v3.0 branch.

There are definitely breaking changes.

A migration guide is available [here](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit).

Closing this issue as answered/resolved.
