### ISSUE TITLE
Contributing.md does not mention SPDX Community Specification CLA

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#657]
[CONTRIBUTING.md](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/CONTRIBUTING.md) does not mention the [SPDX Community Specification Contributor License Agreement 1.0](https://github.com/spdx/governance/blob/main/0._SPDX_Contributor_License_Agreement.md) or the DCO requirement.

Propose to add section to CONTRIBUTING.md explaining that besides CC-BY-3.0 also SPDX Community Specification CLA applies.

**Comment by goneall** [comment]
@swinslow Can you review this issue?  Would you mind adding PR?

**Comment by swinslow** [comment]
Sure, I'll submit a PR for this.

**Comment by swinslow** [comment]
Note to self -- will also add copy of [Community-Spec-1.0](https://github.com/spdx/governance/blob/main/1._Community_Specification_License-v1.md) to [LICENSE file](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/LICENSE) in spdx-spec repo, while retaining copy of existing CC-BY-3.0 text for pre-existing portions of the spec.

**Comment by swinslow** [comment]
Should I submit this to a different branch, since it looks like 2.2.2 was [released earlier today](https://github.com/spdx/spdx-spec/releases/tag/v2.2.2)?

**Comment by goneall** [comment]
@swinslow - there is a related PR - if you could update or close this once the PR is rebased.

**Comment by swinslow** [comment]
@goneall Thanks, this should be fixed for v3.0 in #900.
