### ISSUE TITLE
typo of company name in https://spdx.dev/tools-commercial/

### ISSUE THREAD

**Issue by fu7mu4** [spdx/spdx-spec#662]
It's just typo. FOSSID is a product of snyk, not synk.

1. go to https://spdx.dev/tools-commercial/
2. search snyk in that page.

see https://snyk.io/

**Comment by seabass-labrax** [comment]
Thank you for reporting this, @fu7mu4 - I'll let our website admin know as soon as possible!

**Comment by kestewart** [comment]
While starting to publish the 2.3, figured out where this was, and have fixed it.   Thanks!
