### ISSUE TITLE
Use bd_export_spdx2.2 for Black Duck instead of Hub-SPDX in https://spdx.dev/tools-commercial/

### ISSUE THREAD

**Issue by fu7mu4** [spdx/spdx-spec#663]
Hub-SPDX for Black Duck written in https://spdx.dev/tools-commercial/ is outdated, ant its links are dead link.
Now they use  bd_export_spdx2.2 instead of Hub-SPDX. See https://github.com/blackducksoftware/bd_export_spdx2.2
Of cource, you can use bd_export_spdx2.2 for Downloading a report in SPDX format from Black Duck Hub.

Please change Hub-SPDX with bd_export_spdx2.2.
Its usage is written in README , https://github.com/blackducksoftware/bd_export_spdx2.2/blob/master/README.md

**Comment by kestewart** [comment]
Fixed the website while updating the 2.3 release.   Should be good now.
