### ISSUE TITLE
Point https://spdx.github.io/spdx-spec/ to pick up 2.2.2 (currently 2.2.1)

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#680]
Would like to update the docs to push out the 2.2.2 to the online version. 
What needs to be updated?

**Comment by NorioKobota** [comment]
Relates to PR #676. 
You need to update mkdocs version in requirements.txt that exists in v3.0 and master(main) branch.
ref: https://github.com/NorioKobota/spdx-spec/actions/runs/2306819019

**Comment by goneall** [comment]
This is resolved with PR #702 PR #701 PR #699 PR #698 PR #697 PR #693 PR #692 and/or PR #676
