### ISSUE TITLE
Unclear or broken links

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#7]
Several links within the 2.1 specification are broken or unclear where they are referring to.

Examples

> 2.9  .. This field is distinct from the fields in section 7, which involves the addition of information during a subsequent review. 

Guess this link is incorrect refers to Relationship section. How does this related to `Created` attribute?
 
> 5.5 If the Concluded License is not the same as the License Information in File, a written explanation should be provided in the Comments on License field (section X.5). With respect to NOASSERTION, a written explanation in the Comments on License field (section X.7) is preferred.

X.5? X.7. Think this should be twice reference to 5.7

In Appendix I: SPDX License List  Master Files -> http://git.spdx.org/?p=license-list.git%3Ba=summary 404's should point to https://github.com/spdx/license-list

**Comment by kestewart** [comment]
Some of these appear to be references to sections in 2.0, we missed in updating for 2.1

2.9 " fields in section 7" --> "fields in section 8"   
(it was a reference to Annotation Date, which could happen later than initial Document creation date)

5.5  Yes, the reference should be to 5.7.   Also spotted case another fix in this statement,  see highlighting. 
 "If the Concluded License is not the same as the License Information in File, a written explanation should be provided in the Comments on License field (section X.5).  With respect to NOASSERTION, a written explanation in the Comments on License field (section X.7) is preferred."
Should be:
If the Concluded License is not the same as the License Information in **Snippet**, a written explanation should be provided in the Comments on License field (section 5.7).  With respect to NOASSERTION, a written explanation in the Comments on License field (section 5.7) is preferred.

Yes,   we missed fixing this when migrating from git.spdx.org to github for the license list.   The reference you list is correct redirect.  Appendix I: SPDX License List Master Files -> http://git.spdx.org/?p=license-list.git%3Ba=summary 404's should point to https://github.com/spdx/license-list

**Comment by goneall** [comment]
The license list master files recently moved to https://github.com/spdx/license-list-XML - this is the URL we should point to for the master files.
