### ISSUE TITLE
Inconsistency in the syntax of comments in tag-value format

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#712]
In the SPDX standard, we have several fields for commenting various entities.

In the list below, we have cases where delimiting the comment by <text> .. </text> is always mandatory, and cases where it is mandatory only when the comment has multiple lines.

This is inconsistent and adds unnecessary complexity to the standard.

I would recommend to make  <text> .. </text> always mandatory.

What do you think?

Best regards,

Marc-Etienne

CreatorComment:
•	In tag:value format this is delimited by `<text> .. </text>`
DocumentComment:
•	In tag:value format this is delimited by `<text> .. </text>`
PackageComment:
•	In tag:value format multiple lines are delimited by `<text>...</text>`
ExternalRefComment:
•	In tag:value format this is delimited by `<text>...</text>`
FileComment:
•	In tag:value format multiple lines are delimited by `<text> .. </text>`
SnippetComment:
•	In tag:value format multiple lines are delimited by `<text> .. </text>`
LicenseComment:
•	In tag:value format multiple lines are delimited by `<text> .. </text>`
RelationshipComment:
•	In tag:value format multiple lines are delimited by `<text> .. </text>`
AnnotationComment:
•	In tag:value format multiple lines are delimited by `<text> .. </text>`

**Comment by goneall** [comment]
This is one of those things that makes Tag/Value much more complex to parse and I'm all in favor of decreasing the complexity.

Since this would be a breaking change, it would have to be a 3.0 update.

**Comment by goneall** [comment]
We will be replacing tag/value in 3.0 - closing this issue since any change prior to 3.0 would be a breaking change.

cc: @kestewart
