### ISSUE TITLE
SPDX validator throws error while validating v2.2 sample JSON

### ISSUE THREAD

**Issue by Doktoreher** [spdx/spdx-spec#723]
https://tools.spdx.org/app/validate/ validator throws the following error when applied to the sample JSON (https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.2.spdx.json)

"Error!
Analysis exception processing SPDX file: Missing document namespace"

**Comment by goneall** [comment]
I just tried it and ran into the same error.  The v2.3 examples does work.

Since we haven't updated the examples in v2.3 to the 2.3 spec changes, we can just copy those examples back over to v2.2.

**Comment by goneall** [comment]
I just checked and the version 2.2.1 examples also work.

I'll create a PR copying the v2.2.1 examples to the v2.2 repo.

@Doktoreher FYI - I updated the title to be more specific to the version of the examples not working.

**Comment by goneall** [comment]
Resolved with PR #724
