### ISSUE TITLE
How to use SPDX for LICENSE in github?

### ISSUE THREAD

**Issue by alex4200** [spdx/spdx-spec#726]
Hello, 

I am very new to this SPDX "thing" and the flood of information, data and repos confuse me. 

Sorry if this is the wrong to ask this kind of question, but I did not see any contact form. 

So if I understand it correct, SPDX is just a way to say what license a file has. Is that correct? 

Does this also apply to the main LICENSE file that I have in my github repo? Can I just remove all content of that file and replace the text of the LICENSE file by something like

`SPDX-License-Identifier: GPL-3.0-or-later` ?

**Comment by goneall** [comment]
Hi @alex4200 - SPDX is a standard way of describing the contents of a package including the license for the package.  There are a couple of related standards for how you can describe the license within your source package - I would suggest looking into the [FSFE Reuse](https://reuse.software/dev/) for guidance on best practices related to declaring licenses for your packages.  They are compatible with the SPDX specification but goes further in describing best practices.

**Comment by alex4200** [comment]
Thanks @goneall for your link - so what I understand of the examples given, the best practice is to create a LICENSE folder containing the licenses in text form, and not in SPDX form? Do I understand that correct?

**Comment by goneall** [comment]
> so what I understand of the examples given, the best practice is to create a LICENSE folder containing the licenses in text form, and not in SPDX form? Do I understand that correct?

That is my understanding as well.  In addition to the license file, you should have comments in each of the source files with an SPDX license identifier (see the [Comment Headers](https://reuse.software/spec/#comment-headers) section of the REUSE spec).

If you follow the format specified for the REUSE comment headers, automated tooling will be able to recognize your license and copyright choices even if the file is copied into another repo.
