### ISSUE TITLE
For RelationTypes it is not clearly statet, which types are inverses of each other

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-spec#744]
currently https://github.com/spdx/spdx-spec/blob/development/v2.3/chapters/relationships-between-SPDX-elements.md  does not explain, that `DEPENDENCY_OF` and `DEPENDS_ON` are inverses of each other. Making that explicit and stating that `$A DEPENDENCY_OF $B` is equivalent to `$B DEPENDS_ON $A` would be helpful. There are also others that have this property. And there is also `COPY_OF` which is the inverse of itself.

**Comment by kestewart** [comment]
Agree this needs to be improved, but we're missing a PR to update the documentation at this point, and relationship directionality are being revisited in 3.0, so moving this issue to here.

**Comment by goneall** [comment]
Documentation has been improved in 3.0 - closing this issue.

If there is any remaining concerns, please open a pull request or a specific reccomendation.
