### ISSUE TITLE
Release SPDX 2.3

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#774]
The following tasks need to be completed for the 2.3 release:

- [x] Complete review period (end of day Wednesday 10 August 2022)
- [x] All issues in the 2.3 milestone are closed or assigned to another milestone
- [x] All pull requests in the 2.3 milestone are closed or assigned to another milestone
- [x]  Merge development/v2.3 branch to master
- [x] Add 2.3 release tag to master
- [x] Create development/v2.3.1 branch and make it the default
- [x] Generate specification documents
  - [x] PDF
  - [x] HTML
  - [x] RDF
  - [x] OWL
- [x] Update RDF artifacts
  - [x]  http://spdx.org/rdf/ontology/spdx-2-3
  - [x]  http://spdx.org/rdf/terms
- [x] Update https://spdx.org/specifications
  - [x] Update current version
  - [x] Add 2.2 to previous versions
  - [x] Update version on document structure image (also needs to be updated in `chapters/img/spdx-22.1-document.png`)
- [x] Update other website references to 2.3
  - [x] https://spdx.org/frequently-asked-questions-faq-0
  - [x] Add entry to ["Short History"](https://spdx.org/about)
- [x]  Announcements
  - [x] Write up of blog
  - [ ] Publish blog on LF site
  - [ ] Publish reference to blog News on the [SPDX homepage](https://spdx.org/)
  - [x] Announcement email to main lists
  - [x] Announcement to OpenChain and any other relevant communities

**Comment by kestewart** [comment]
Closing this as 2.3 was published a while ago.
