### ISSUE TITLE
Add location to document Creator Tool Metadata information to ensure reproducibility

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#78]
Use Case:  Enable reproduce accurate results, some parameter metadata for the tooling would be useful to captured, and fed back into a different run of the tools. 

Use Case:  Location to store data that is not able to be communicated between export and import of SPDX

**Comment by kestewart** [comment]
This is getting into provenance use cases,   annotations may be able to handle?

**Comment by kestewart** [comment]
This is a topic we'll cover in the 3.0 Provinence Profile.

**Comment by goneall** [comment]
ping @kestewart

**Comment by kestewart** [comment]
This has been handled by the build profile see: https://spdx.github.io/spdx-spec/v3.0/model/Build/Properties/configSourceUri/
