### ISSUE TITLE
File `licenseInfoInFile` typos in 2.3 json Examples

### ISSUE THREAD

**Issue by bjamesv** [spdx/spdx-spec#781]
https://github.com/spdx/spdx-spec/blob/aadf3b0b8dbbabdb4d880b0fc714255fea436ff7/examples/SPDXJSONExample-v2.2.spdx.json#L164

field should be rendered as `licenseInfoInFile` per spec https://spdx.github.io/spdx-spec/file-information/#863-examples

There may be similar occurrences of this elsewhere in the examples, I haven't checked around yet.

**Comment by bjamesv** [comment]
@goneall

**Comment by goneall** [comment]
@bjamesv This is by design - for the JSON and YAML, any property with a cardinality `1..*` or `0..*` is pluralized.

**Comment by bjamesv** [comment]
👍 thank you
