### ISSUE TITLE
Support normalization of license names

### ISSUE THREAD

**Issue by vlsi** [spdx/spdx-spec#787]
`pom.xml` sometimes list license names, and it turns out the naming differs from what SPDX uses.

For instance: https://github.com/spdx/tools/blob/9554be24025f69228b9708ce418b45257e00b04a/pom.xml#L9-L11

However that naming is never mentioned in SPDX: https://github.com/spdx/license-list-XML/blob/5b1f68375508e854a6aa6d1fb87225cb98e50ece/src/Apache-2.0.xml#L3

Does it make sense to implement a normalizer that would enable to infer Apache-2.0 from `The Apache Software License, Version 2.0`?

**Comment by goneall** [comment]
@vlsi - this is rather (very) stale - I would recommend we open a [change proposal](https://github.com/spdx/change-proposal) if we want to implement a normalization.

Note: we would need a volunteer to do the implementation work.
