### ISSUE TITLE
Discrepancy in JSON schema Primary Package Purpose

### ISSUE THREAD

**Issue by kzantow** [spdx/spdx-spec#794]
The JSON schema for v2.3.1 includes `primaryPackagePurpose` as a `string` type: https://github.com/spdx/spdx-spec/blob/development/v2.3.1/schemas/spdx-schema.json#L408-L412 but the spec says the cardinality is: `0..*`: https://spdx.github.io/spdx-spec/v2.3/package-information/#724-primary-package-purpose-field. Which is correct? It seems like from the wording of the spec, it should actually be `0..1` and the JSON schema is correct?

**Comment by goneall** [comment]
From this issue: https://github.com/spdx/spdx-spec/issues/720 - it looks like we decided on a cardinality of `0..1`.

It looks like we updated the JSON schema but forgot to update the spec itself.  @kzantow - would you mind creating a PR to fix the spec?

**Comment by kzantow** [comment]
Sure thing, @goneall !

**Comment by kzantow** [comment]
Done. I haven't contributed to this repo before, so hopefully that's all that is needed!

**Comment by goneall** [comment]
Thanks @kzantow
