### ISSUE TITLE
JSON schema should include `documentNamespace` as required

### ISSUE THREAD

**Issue by kzantow** [spdx/spdx-spec#795]
According to the spec here: https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#65-spdx-document-namespace-field `Document Namespace` is required, but the JSON schema does not include it as a required field here: https://github.com/spdx/spdx-spec/blob/development/v2.3.1/schemas/spdx-schema.json#L738

**Comment by goneall** [comment]
Thanks @kzantow  - good catch.

I'll create a PR to resolve (the JSON schema is generated).
