### ISSUE TITLE
Spec should allow 0..1 checksums for non-SHA1 checksums on files, not 0..*

### ISSUE THREAD

**Issue by nicoweidner** [spdx/spdx-spec#801]
In the spec for the file checksum field (https://spdx.github.io/spdx-spec/v2.3/file-information/#84-file-checksum-field), it says:
```
Cardinality | 1..1 for the SHA1 algorithm, 0..* for all other algorithms
```
This means that a file needs to have exactly one `SHA1` checksum, but could have 100 `SHA256` checksums, for example. I believe each other algorithm should appear with cardinality 0..1 instead?

**Comment by alilleybrinker** [comment]
I think this is saying that you _have to_ provide a SHA1 checksum, but you can provide any number (including none) of other checksums. So it's not saying that each type of checksum can be repeated, but rather that you can have any many other checksums as you want.

**Comment by goneall** [comment]
> I think this is saying that you have to provide a SHA1 checksum, but you can provide any number (including none) of other checksums.

I believe this was the intent.  The cardinality applies to the entire checksum.

**Comment by nicoweidner** [comment]
I suppose I am being nitpicky about wording here. I find it confusing since the same sentence lists the cardinality of one specific algorithm (SHA1) and the cardinality of the union of all other algorithms. I would prefer `0..1 for each other algorithm`, but I get how the sentence is intended.

**Comment by goneall** [comment]
Since this is different in 3.0, I'm closing this as "not planned"
