### ISSUE TITLE
JSON schema question: `hasFiles`

### ISSUE THREAD

**Issue by kzantow** [spdx/spdx-spec#805]
I'm trying to figure out where `hasFiles` is defined in the spec and it no longer seems to be, from what I can tell, yet it's defined in the latest JSON schema here: https://github.com/spdx/spdx-spec/blob/development/v2.3.1/schemas/spdx-schema.json#L345-L352

There was an older issue (#487) that points to a moved section of the spec (section 4, which is now section 8) but I cannot find any reference to this in the current 2.3 docs.

Could someone explain how this relates to the spec? Or should this be removed?

**Comment by goneall** [comment]
@kzantow the `hasFiles` is synonymous to a relationship between an `SpdxPackage` and an `SpdxFile` with a contains relationship.

It is documented in the [SPDX Ontology](http://spdx.org/rdf/terms#hasFile) and JSON Schema - although the documentation could definitely be improved - any pull requests along this line are greatly appreciated.

The `hasFiles` originates from the Tag/Value representation where the files immediately following the package used the `hasFile` property when translating to other formats.

For 3.0, this is likely to be deprecated in favor of the relationship referenced above.

For SPDX 2.3, having a `hasFiles` or a `CONTAINS` relationships between the package and the file are both valid.  This does imply the tooling has to deal with both representations.  Note that this is also the case for `documentDescribes` which is synonymous to the `DESCRIBES` relationship between the `SpdxDocument` and the `SpdxElement`.

**Comment by kzantow** [comment]
Thanks for the follow-up @goneall. Just so I understand, it [looks like this field was deprecated in 2.0](https://spdx.org/rdf/terms/#d4e4761) (based on the comment "_relationshipType_contains introduced in SPDX 2.0 deprecates property 'hasFile' from SPDX 1.2_"), so will it probably be _removed_ in 3.0? But for 2.0 versions, a consumer should support both forms?

**Comment by goneall** [comment]
> Just so I understand, it [looks like this field was deprecated in 2.0](https://spdx.org/rdf/terms/#d4e4761) (based on the comment "relationshipType_contains introduced in SPDX 2.0 deprecates property 'hasFile' from SPDX 1.2"), so will it probably be removed in 3.0? But for 2.x versions, a consumer should support both forms?

For 2.x, a consumer should support both forms.  For 3.0, it is likely it will be removed, but until the spec is finalized there's a chance it will remain.  There is a lot of discussion on having serialization shortcuts supported in specific serialization formats - the outcome of those discussions may impact this field.

**Comment by kzantow** [comment]
Thanks for all the clarification @goneall!
