### ISSUE TITLE
Is there a reason for this redundancy in the example files?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-spec#808]
Several items are duplicated in:
https://github.com/spdx/spdx-spec/blob/810d229fed8093aae03d9dd42aa0a8174611121a/examples/SPDXYAMLExample-2.3.spdx.yaml#L201-L215

**Comment by goneall** [comment]
If this hasn't been fixed already, it will be resolved in SPDX 3.0 - closing
