### ISSUE TITLE
A typing question regarding LicenseInfoInFile

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-spec#809]
I am confused by the fallback of LicenseInfoInFile:

https://github.com/spdx/spdx-spec/blob/810d229fed8093aae03d9dd42aa0a8174611121a/chapters/file-information.md?plain=1#L303

I think examples for parsed values are `LicenseInfoInFile=[NONE]` or `LicenseInfoInFile=["MIT", NOASSERTION]`, so it is a list where elements can be `NONE` or `NOASSERTION` or `SPDX License Expression`. But the fallback tells me, that it should be `LicenseInfoInFile=NOASSERTION` if not present, which is no longer a list? Is this correct, or should it be `[NOASSERTION]` as default

**Comment by goneall** [comment]
@maxhbr Good point - we should not change the type for the fallback IMO.  I agree with your proposed solution.

**Comment by meretp** [comment]
While implementing the tag-value parser and testing it with the files from the [package-analysis repo](https://github.com/Open-Source-Compliance/package-analysis/tree/main/analysed-packages) I came across this issue. Many of these files have `LicenseInfoFromFiles= [NOASSERTION]` which lead to a ParsingError in the `tools-python`. From the issue and your response @goneall, I assume that the tools should at least be able to parse these values and probably this should be clarified in the spec.

**Comment by goneall** [comment]
This field has been removed in SPDX 3.0 - closing as not planned
