### ISSUE TITLE
support matching http | https

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/spdx-spec#81]
Companion issue to https://github.com/spdx/license-list-XML/issues/633

Track there for now; one potential solution would affect the SPDX License List and one would affect the spec.

**Comment by kestewart** [comment]
Update to Appendix II? link to license list matching guidelines? 
(Gary notes this should be fixed in the tools as well as well)

**Comment by kestewart** [comment]
Discussion in call,  Appendix needs to be updated for release,  so catch this.
@swinslow  will do the update

**Comment by swinslow** [comment]
Website has been updated: https://spdx.org/spdx-license-list/matching-guidelines

as has the copy in spdx/license-list-XML: https://github.com/spdx/license-list-XML/pull/974 and https://github.com/spdx/license-list-XML/blob/master/DOCS/matching-guidelines

I'll submit a PR to modify Appendix II in the spec to also reflect these changes.

**Comment by swinslow** [comment]
@kestewart I've submitted #202 to fix this -- if it looks good to you, feel free to merge!
