### ISSUE TITLE
Add link to annotations in deprecated reviews section

### ISSUE THREAD

**Issue by nicoweidner** [spdx/spdx-spec#810]
The [reviews section](https://spdx.github.io/spdx-spec/v2.3/review-information-deprecated/) notes that reviews are deprecated since 2.0. But it doesn't give any indication on what should be used instead. The corresponding comment can be found in the [differences from earlier versions](https://spdx.github.io/spdx-spec/v2.3/diffs-from-previous-editions/) section, but that's quite hidden. I think a comment in the reviews section would be good.

**Comment by goneall** [comment]
The deprecated sections have been removed in the 3.0 spec.

Closing as not planned
