### ISSUE TITLE
How to handle files that are contained in multiple packages in tv format?

### ISSUE THREAD

**Issue by meretp** [spdx/spdx-spec#811]
According to the [spec](https://spdx.github.io/spdx-spec/v2.3/composition-of-an-SPDX-document/#5.2.3):

> Files are assumed to be associated with the package information that immediately precedes it, if a package exists.

How to handle a file that is contained in at least two packages? Would the file information be duplicated, once following the first package information and once following the second package information? Or would the file information once follow the first package and the relation to the second package would be encoded in a `CONTAINS`-relationship?

**Comment by seabass-labrax** [comment]
For SPDX 2.x, I would suggest your first suggestion of duplication, as it seems the safer option regarding tooling support. For instance, it prevents possible ambiguity regarding whether the 'Files Analysed' field is expected to be set or not. Logically, I believe that the second option of additional `CONTAINS` relationships is valid, however I would not be confident that other tools will support this.

For SPDX 3.0, the existence of an Element will be entirely independent from its serialisation in tag-value format. That means that either option would be valid and indeed identical from a logical perspective. Thus, you can choose to serialise the Element as many times as you like for readability - the only thing that matters is the `CONTAINS` relationships. Please let me know if you'd like me to elaborate with examples!

**Comment by meretp** [comment]
Thanks for the answers @seabass-labrax! 
I am dealing with the `tools-python` and as we are currently refactoring the codebase this question came up. 
The internal data model of `tools-python` decouples packages and files and uses relationships nevertheless, so we don't have any duplication there. This approach seems to already fit to SPDX3.0. 

But regarding SPDX 2.x: Your comment that most tools would use duplication here helps us to implement the tag-value parser. We haven't implemented a refactored tag-value parser yet (and I am not sure how the current parser is dealing with duplicated file information) but your hint indicates that we need to add some logic to avoid duplicated files in the internal data model when parsing a tag value file. The current implementation of the writer on the other hand duplicates the information, which is perfectly fine then. 

Closing this issue as my question is answered.

**Comment by seabass-labrax** [comment]
Glad to be of assistance :smiley:
