### ISSUE TITLE
What is the right string value for the package purpose OPERATING-SYSTEM in json?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-spec#813]
in the spdx-schema.json it is written as `OPERATING_SYSTEM`:

https://github.com/spdx/spdx-spec/blob/810d229fed8093aae03d9dd42aa0a8174611121a/schemas/spdx-schema.json#L411

but in https://spdx.github.io/spdx-spec/v2.3/package-information/#724-primary-package-purpose-field it is called `OPERATING-SYSTEM`, which looks like it should be `-` instead of `_`. What is correct?

(might be good to avoid dashes in Enums)

**Comment by tsteenbe** [comment]
@maxhbr  This issue keeps on popping up in other enums as well @goneall  told me when he did SPDX 2.3 he changed it compared to SPDX 2.2.

**Comment by goneall** [comment]
Sorry about the late response to this issue.

The SPDX spec document tag/value.  There is a well understood issue where the JSON format is not adequately documented in the spec.

The only authoritative spec for JSON is the JSON Schema - so the answer should be with the underscore.

@tsteenbe the OPERATING-SYSTEM was introduced in 2.3, so it does not apply to my previous comments on 2.2.

**Comment by goneall** [comment]
Closing this as resolved
