### ISSUE TITLE
Not All Checksum Algorithms Are Displayed Correctly

### ISSUE THREAD

**Issue by init-dcat-ap-de** [spdx/spdx-spec#815]
The[ html representation of the ontology](https://spdx.org/rdf/terms/#d4e2129) does not show all defined checksum algorithms
![grafik](https://user-images.githubusercontent.com/14979304/203945690-a461161f-882b-400e-ac8f-a6bc49e22e94.png)

This is only a problem in the front end, since the rdf has the missing algorithms listes:

> adler32, blake2b256, blake2b384, blake2b512, blake3, md2, md4, md5, md6, sha1, sha224, sha256, **sha384, sha3_256, sha3_384, sha3_512, sha512**

**Comment by goneall** [comment]
@init-dcat-ap-de Thanks for pointing this out.  The HTML is generated from the OWL document which does contain the algorithms.  I noticed a comma after the sha256 value - I wonder if this is a limitation in the tool that generates the HTML.

@zvr - could you take a look?

**Comment by zvr** [comment]
Oh, wow! It seems that (at least) one of the tools in the toolchain has a line length limit and silently truncates the long line.

Thanks for the report, @init-dcat-ap-de -- I'll fix it and push a new version of the HTML doc in the next couple of days.

**Comment by goneall** [comment]
The SPDX 3.0 uses a different toolchain - closing as resolved
