### ISSUE TITLE
What is the correct way to specify the ID of the externalDocumentRef in RDF?

### ISSUE THREAD

**Issue by meretp** [spdx/spdx-spec#816]
When trying to parse the [SPDXRdfExample-v2.2.spdx.rdf](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXRdfExample-v2.2.spdx.rdf.xml) with the python-tools the above question has arisen.

 Looking into the rdf ontolgy, the html spec and the provided example files I encountered different ways to specifiy the ID:
 
- The [SPDXRdfExample-v2.3.spdx.rdf.xml](https://github.com/spdx/spdx-spec/blob/efa69656db9db4fcc871de563cbbd104fc1e33c3/examples/SPDXRdfExample-v2.3.spdx.rdf.xml#L1916-L1927) contains an `externalDocumentId` node what is consistent with the rdf [ontology](https://spdx.org/rdf/terms/#d4e2364).
- The [SPDXRdfExample-v2.2.spdx.rdf](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXRdfExample-v2.2.spdx.rdf.xml) doesn't contain this node but you can find the Id at the end of the `rdf:resource` in the top node `ExternalDocumentRef``<spdx:ExternalDocumentRef rdf:about="http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301#DocumentRef-spdx-tool-1.2">` (see [here](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXRdfExample-v2.2.spdx.rdf.xml#L4062))
- The example in the [html-spec](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#66-external-document-references-field) doesn't contain the extra node either (both for version 2.3 and 2.2.2) but instead the top node `externalDocumentRef`  <externalDocumentRef rdf:ID="DocumentRef-spdx-tool-1.2"> contains a tag `rdf:ID`.

Since these are 3 different ways to express one thing, which one is the correct way?

**Comment by goneall** [comment]
The `rdf:ID="DocumentRef-spdx-tool-1.2` and `rdf:about="http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301#DocumentRef-spdx-tool-1.2` are equivalent per the RDF spec if the SPDX document namspace is `http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301` (see [this stackoverflow article](rdf:about="http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301#DocumentRef-spdx-tool-1.2) for an explanation).

I don't believe the [SPDXRdfExample-v2.3.spdx.rdf.xml](https://github.com/spdx/spdx-spec/blob/efa69656db9db4fcc871de563cbbd104fc1e33c3/examples/SPDXRdfExample-v2.3.spdx.rdf.xml#L1916-L1927) should be including the property / node `externalDocumentId`.  It is redundant with the ID.

This is probably a bug introduced with a change in the Ontology to include the property name which the [SPDX Java RDF Store](https://github.com/spdx/spdx-java-rdf-store) picked up on and included the property. 

There isn't much harm in the additional property and the JSON Schema does include this property (see PR #535).

We should probably take this back out of the ontology and fix the [JSON Schema Generator](https://github.com/spdx/tools-java/blob/master/src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java) to add the property even though it isn't in the Ontology.

**Comment by goneall** [comment]
This is resolved in 3.0
