### ISSUE TITLE
v2.2 examples have cyclic CONTAINS relationships

### ISSUE THREAD

**Issue by nicoweidner** [spdx/spdx-spec#817]
See e.g. https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXJSONExample-v2.2.spdx.json#L263-L267 and https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXJSONExample-v2.2.spdx.json#L275-L279. Seems to be present in other formats as well.

Not sure if this is forbidden by the spec (probably not) or really relevant for the examples, but at least it doesn't seem to make a lot of sense...

**Comment by goneall** [comment]
@nicoweidner Good point - this doesn't make much sense.  I can create a PR to remove.

BTW - cycles are allowed in relationships, so it isn't technically invalid - it just doesn't make sense.  I think this occurred when we changed the spec to use CONTAINS relationships for the `hasFiles` property.

**Comment by goneall** [comment]
Since we're reworking the examples for SPDX 3.0, closing this as no longer relevant
