### ISSUE TITLE
Problem of cardinality in some of fields

### ISSUE THREAD

**Issue by dyphn1** [spdx/spdx-spec#818]
In the SPDX version 2.3 spec.

The [PackageName](https://spdx.github.io/spdx-spec/v2.3/package-information/) field cardinality is 1..1.
But in the sample that have more than on package described in one SPDX file.

Does it correct?
How do I know exactly how many times those fields can appear in SPDX?

Like [LicenseID](https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/#101-license-identifier-field)
Could it describe more than one times? 

Because now I have a package with two extra-license files.

**Comment by alilleybrinker** [comment]
`PackageName` is part of the Package Information section, so I'd take the `1..1` cardinality to mean it appears exactly once _per package_. Similarly, `LicenseID` is defined once _per custom license_.

**Comment by dyphn1** [comment]
I see.
So cardinality decide that how many times the description could be described on each paragraph. Right?

So, If I describe a paragraph like this
```
LicenseID: LicenseRef-1

....

# Package glibc
PackageName: glibc
...
PackageLicenseConcluded: LicenseRef-1 AND Zlib
...
LicenseID: LicenseRef-2
...
FileName: ./docs/xxx.txt
LicenseConcluded: LicenseRef-1 AND LicenseRef-2

# Package Saxon
PackageName: Saxon
....
PackageLicenseConcluded: LicenseRef-1 AND GPL-2
...
LicenseID: LicenseRef-3
...
FileName: ./docs/sss.txt
LicenseConcluded: LicenseRef-1 AND LicenseRef-3
```
Is this correct?

**Comment by alilleybrinker** [comment]
I think once per _package_, not once per paragraph, but otherwise yes.

**Comment by goneall** [comment]
I believe this has been answered - closing issue as resolved
