### ISSUE TITLE
Multiple LicenseCrossReference in one line in tag/value example

### ISSUE THREAD

**Issue by nicoweidner** [spdx/spdx-spec#823]
In [the tag/value example](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/examples/SPDXTagExample-v2.3.spdx#L337), multiple cross references are concatenated in a single line:
```
LicenseCrossReference: http://people.apache.org/~andyc/neko/LICENSE, http://justasample.url.com
```
[The spec](https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/#104-license-cross-reference-field) gives the cardinality as `0..*`, so I suspect it should really be two lines instead:
```
LicenseCrossReference: http://people.apache.org/~andyc/neko/LICENSE
LicenseCrossReference: http://justasample.url.com
```
This feels more consistent with other properties and also makes it easier for tools parsing tag/value.

**Comment by goneall** [comment]
Since tag/value will be significantly restructured in 3.0, closing this as no longer relevant 

cc: @kestewart
