### ISSUE TITLE
Empty brackets for creators without email?

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-spec#824]
The [spec states for the creator field](https://spdx.github.io/spdx-spec/v2.3-RC1/document-creation-information/#68-creator-field):
> Person: person name" and optional "(email)"

which I would interpret as omitting the whole "(email)" part if no email is present. Instead, the examples read like
> Creator: Person: Jane Doe ()

i.e. they omit the "email" but not the parentheses. Which of these two options is the required behavior?

**Comment by goneall** [comment]
This is now a structured class in SPDX 3.0 - closing as no longer relevant
