### ISSUE TITLE
Duplication in JSON schema: crossRefs and seeAlsos

### ISSUE THREAD

**Issue by nicoweidner** [spdx/spdx-spec#826]
Extracted licensing infos in the json schema have [a crossRefs property](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/schemas/spdx-schema.json#L120) as well as [a seeAlsos property](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/schemas/spdx-schema.json#L172). Looking at the tag/value spec and the rdf example listed there, I suspect there should only be `seeAlsos`, and `crossRefs` is unused: https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/#104-license-cross-reference-field

**Comment by goneall** [comment]
This is related to https://github.com/spdx/spdx-spec/issues/46 - `crossRefs` are one of the listed license specific fields used in the license list XML.  We could remove this from the JSON schema, or we could add the license list XML fields to the spec as suggested in issue #46

**Comment by nicoweidner** [comment]
Hm, I see. I vaguely remembered having read about it before. I stumbled across it while working on the Python tools. If the status of `crossRefs` is not so clear, it's probably ok not to support them for now, right?

**Comment by goneall** [comment]
>  If the status of `crossRefs` is not so clear, it's probably ok not to support them for now, right?

I completely agree that it is not necessary to support `crossRefs` in Python (or any other language tools) before we conclude on #46.

**Comment by goneall** [comment]
I believe this is resolved in 3.0
