### ISSUE TITLE
Clarification about PackageDownloadLocation

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#830]
```PackageDownloadLocation``` can be a URL.

This example given in the spec is:
```
PackageDownloadLocation: http://ftp.gnu.org/gnu/glibc/glibc-ports-2.15.tar.gz
```
You can do a ```wget``` on the URL to get the software.

Is is mandatory that fetching the URL downloads the software?

I have tools that output things like:
```
PackageDownloadLocation: https://busybox.net/
PackageDownloadLocation: https://alpinelinux.org/
```
In that case, I cannot automate the download of the software, which I think is the purpose of ```PackageDownloadLocation```.

So is this kind of output correct SPDX?

**Comment by goneall** [comment]
> Is is mandatory that fetching the URL downloads the software?

Yes and no.  Yes in that the string has to conform to syntax that can allow it to be downloaded.  However, it can be a string that represents a specific version control location.  So if you want to use the `PackageDownloadLocation` for downloading automated content, you'll need to implement protocols for all the supported version control patterns.  See the [package download location examples](https://spdx.github.io/spdx-spec/v2.3/package-information/#773-examples) for a list of different `PackageDownloadLocation` string formats mentioned in the spec.

**Comment by vargenau** [comment]
If the content of ```PackageDownloadLocation``` is a VCS location, I know what to do.

My question was when the ```PackageDownloadLocation``` is a URL.

I have a tool that generates:
```
PackageDownloadLocation: https://alpinelinux.org/
```

In this case, I have to manually browse the website to find the real download URL, for example ```https://dl-cdn.alpinelinux.org/alpine/v3.17/releases/x86/alpine-standard-3.17.1-x86.iso```

So my question is: can I complain to the tool vendor that the SPDX is incorrect?

**Comment by goneall** [comment]
> So my question is: can I complain to the tool vendor that the SPDX is incorrect?

In my opinion - yes.  Although, when reading the spec it isn't very clear on this.  Something we may want to clarify in a future release of the spec.

**Comment by vargenau** [comment]
Yes, my point was that the spec is not very explicit about it. I agree it should be clarified in the next release.
