### ISSUE TITLE
Invalid TagExample 2.3: List of cross references separated with comma 

### ISSUE THREAD

**Issue by meretp** [spdx/spdx-spec#840]
I discovered the following line in the [example file](https://github.com/spdx/spdx-spec/blob/386ce342a28f12d31b77a549261857eda16f9304/examples/SPDXTagExample-v2.3.spdx#L337) for tag-value:

> LicenseCrossReference: http://people.apache.org/~andyc/neko/LICENSE, http://justasample.url.com

From my understanding of the spec and also the analogous example file in rdf where the references have two individual tags, I think this should be changed to:
> LicenseCrossReference: http://people.apache.org/~andyc/neko/LICENSE
> LicenseCrossReference: http://justasample.url.com

Please let me know if I am correct, I'll be happty to open a PR to fix this.

**Comment by goneall** [comment]
@swinslow - I recall a similar issue with a difference between how the Golang tools and Java tools handled multiple list items in tag/value - do you recall the details issue and how it was resolved?

**Comment by goneall** [comment]
In 3.0+ we will have a significantly different tag/value representation.  Closing this issue as no longer relavent.

cc: @kestewart
