### ISSUE TITLE
Can I use NOASSERTION in case of the NTIA SBOM minimum elements?

### ISSUE THREAD

**Issue by HyuckjunChoi** [spdx/spdx-spec#846]
For example, SPDX's Package Supplier field is the one of the NTIA SBOM minimum elements.
Can I use NOASSERTION in this field for the following reasons?

the SPDX document creator has attempted to but cannot reach a reasonable objective determination;
the SPDX document creator has made no attempt to determine this field; or
the SPDX document creator has intentionally provided no information (no meaning should be implied by doing so).

Otherwise I have to fill the Package Supplier field with the meaningful value not use NOASSERTION because this is the NTIA SBOM minimum element?

**Comment by rnjudge** [comment]
This is an interesting question. I'm not sure about the official guidance from NTIA. cc-ing @jspeed-meyers from https://github.com/spdx/ntia-conformance-checker since the tool counts `NOASSERTION` values for the package supplier field as invalid.

**Comment by jspeed-meyers** [comment]
The only official guidance from SPDX (not NTIA) and NTIA minimum elements I know is this mapping:

https://spdx.github.io/spdx-spec/v2.3/how-to-use/#k22-mapping-ntia-minimum-elements-to-spdx-fields

But it doesn't weigh in on the issue raised by @HyuckjunChoi, IIUC.

I'd be curious if anyone knows of official NTIA or DHS/CISA documentation on this topic.

More broadly, I'd be curious if there is an SPDX definition of "NOASSERTION".

**Comment by rnjudge** [comment]
According to the 2.3 [spec](https://spdx.github.io/spdx-spec/v2-draft/package-information/#75-package-supplier-field), `NOASSERTION` implies:
```
- the SPDX document creator has attempted to but cannot reach a reasonable objective determination;
- the SPDX document creator has made no attempt to determine this field; or
- the SPDX document creator has intentionally provided no information (no meaning should be implied by doing so).
```

**Comment by HyuckjunChoi** [comment]
Thank you for the answers. It is helpful for me.
