### ISSUE TITLE
FileName: question about expected behavior

### ISSUE THREAD

**Issue by surendrapathak** [spdx/spdx-spec#848]
The [2.3 spec for File Information](https://spdx.github.io/spdx-spec/v2.3/file-information/) clearly asks for following format:

```
A relative filename with the root of the package archive or directory.

In general, every filename is preceded with a ./, see http://www.ietf.org/rfc/rfc3986.txt for syntax.
```
However, some tools (including trivy) produce absolute paths for containers. e.g.

```
FileName: /usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V60.pl
```

Would this be considered an invalid value for the Filename?

**Comment by goneall** [comment]
> Would this be considered an invalid value for the Filename?

Yes.  

This is a very common issue.  We have "Docfests" somewhat regularly where tools builders compare SPDX output for the same target.  We find inconsistencies in the the filename is relatively common.  I would suggest reporting the issue to the tool provider and reference the spec. and this issue.

**Comment by surendrapathak** [comment]
Perfect. That's what I was guessing as well. Thanks for confirming @goneall !

**Comment by goneall** [comment]
Closing this as resolved
