### ISSUE TITLE
Invalid references in matching guidelines

### ISSUE THREAD

**Issue by stefan6419846** [spdx/spdx-spec#853]
Looking at the matching guidelines (https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/), there seem to be some outdated references in section B.15:

* In B.15.1, we can read:

  > The license XML can be accessed in the license-list-data repository under the license-list-XML directory.

  There is no such directory at https://github.com/spdx/license-list-data/tree/v3.20 Considering the `rdfxml` directory does not seem to be a valid choice as well, as it uses the legacy template syntax (as we find in `template` as well): https://github.com/spdx/license-list-data/blob/v3.20/rdfxml/0BSD.rdf

* In B.15.2, we can read:

  > A full schema for the License List XML can be found at https://github.com/spdx/license-list-XML/blob/master/schema/ListedLicense.xsd.

  The schema URL is no link in this case, just plain text.

**Comment by goneall** [comment]
@stefan6419846 Thanks for pointing this out.

> The license XML can be accessed in the license-list-data repository under the license-list-XML directory.

A recent decision was made to support the license XML.  It looks like the tooling hasn't kept up.  There is an [open issue in the LicenseListPublisher](https://github.com/spdx/LicenseListPublisher/issues/164) awaiting confirmation from @swinslow and/or @jlovejoy.  Based on this information, it looks like I should just go ahead and make the change to be consistent with the spec.  I should have this updated before the next license list release.

> Considering the rdfxml directory does not seem to be a valid choice as well, as it uses the legacy template syntax (as we find in template as well)

Agree this is an issue, but adding a field to the license RDF XML would be a change to the spec - it would need to wait for a new version of the spec.

I added https://github.com/spdx/spdx-3-model/issues/359 to track adding this to SPDX 3.0.

**Comment by goneall** [comment]
This is now implemented in the license-list-data repo - closing as resolved.
