### ISSUE TITLE
Using SPDX short-form identifiers in JSON file

### ISSUE THREAD

**Issue by MarkTiedemann** [spdx/spdx-spec#854]
Any advice on how to do this since JSON doesn't have comments?

**Comment by zvr** [comment]
Is the question about using identifiers as described in [Annex E](https://spdx.github.io/spdx-spec/v2.3/using-SPDX-short-identifiers-in-source-files/) to identify the license of a file with JSON data?

If yes, adding an extra key-value pair seems easy enough:

    "SPDX-License-Identifier": "MIT"

Maybe I'm misunderstanding something....

**Comment by alilleybrinker** [comment]
I _think_ they're asking about annotating the license of the JSON file itself.

**Comment by swinslow** [comment]
It's external guidance to SPDX (and I won't endorse it or opine on usability here), but the REUSE Software initiative [recommends](https://reuse.software/spec/#comment-headers) using a separate out-of-band file to denote this where comments can't be used:

> If a file is not a plain text file or does not permit the inclusion of comments, the comment header that declares the file’s Copyright and Licensing Information SHOULD be in an adjacent file of the same name with the additional extension .license (example: cat.jpg.license if the original file is cat.jpg).

**Comment by zvr** [comment]
My comment above about adding a new key-value pair adds the license in-band.

Taking a small example from https://json.org/example.html, instead of 
```json
{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
````

you have 
```json
{"SPDX-License-Identifier": "MIT",
"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
````

So, JSON does not allow comments, but it allows new key-value pairs.
This obviously cannot be used in the case you follow a restrictive schema that does not allow you to add new keys.

**Comment by MarkTiedemann** [comment]
The schema is restrictive plus, at the root of the JSON file, there's an array, not a an object, so I cannot add a new key-value pair.

The out-of-band solution with a `.license` file seems to fit best. Too bad it's not official guidance.

Thank you all for the input and suggestions!
