### ISSUE TITLE
How to practically use an external license?

### ISSUE THREAD

**Issue by hoijui** [spdx/spdx-spec#858]
I read the spec, e.g.:
https://github.com/spdx/spdx-spec/blob/development/v2.3.1/chapters/SPDX-license-expressions.md#d3-simple-license-expressions-
but I do not understand how to use a non SPDX incorporated license.
I use the REUSE standard/format and tool, so my source-code headers usually look like this:

```
# SPDX-FileCopyrightText: 2020-2022 First Last <something@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
```

Now let's say, I have my own license, which only my project uses,
and I do not want to register it with SPDX, or it simply is not yet registered with it.
I call it the ABCD-1.0 license, and I have it specified in a text file (`LICENSE-ABCD-1.0.txt`).

How could I use this license in practice, in an SPDX/REUSE compliant way?

My attempt would be:

1. Have my license text in the repo under `LICENSES/ABCD-1.0.txt` (would this be a problem already with the REUSE-tool? would it have to be in an other location?)
2. Use the license in my file like so:

    ```
    # SPDX-License-Identifier: DocumentRef-LICENSES/ABCD-1.0.txt:LicenseRef-ABCD-1.0
    ```

I am asking to know myself, but also to have this documented in the spec, as it is too abstract for me as it is now.

**Comment by hoijui** [comment]
In an other issue, @jlovejoy linked me to this:
https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/

For me, that does not help in getting me there, though.
what does "locally unique" mean, for example. is the "licality" a project, or a file, or ...
Also: Let's say, I would use "LicenseRef-BliBlaBlub" in an SPDX header comment. Then: where else would this BliBlaBlub have to turn up?

**Comment by brlin-tw** [comment]
To use non SPDX licenses in a fashion that is compatible with the REUSE standard, simply:

1. Name your custom license identifier in a way that people won't generally confuse it with another, e.g. `ABC-License`.
2. In the source files that are under this custom license: use the `SPDX-License-Identifier: LicenseRef-ABC-License` tag.
3. In the LICENSES directory in the root of your source tree, add a `LicenseRef-ABC-License.txt` file that details the terms of conditions of your custom license.

**Comment by hoijui** [comment]
Thanks a lot, @brlin-tw !
I just read <https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/> again, and ... this info is completely missing there.
Can we include it somehow?
Tho me, this is the most important info, or say, what most people will be looking for. All that info about meta-data of an additional language in there.. I would not know where to put it either.

**Comment by zvr** [comment]
@hoijui you are looking to combine different pieces of information:

a) Using SPDX to name a custom license: SPDX specifies the short identifier has to start with `LicenseRef-`; other than that, it only specifies how to express the information about this license in a SPDX Document (like an SBOM)
b) Using REUSE to include this information in a source repository: REUSE specifies about having a top-level directory named `LICENSES` and you should put each license as a file therein, named as the license identifier (from a, above).

But SPDX does not specify anything about source directories, so asking for this information to be added in the SPDX spec is not relevant.

**Comment by hoijui** [comment]
Ahh.. you have a point.
... aand there it is already! :D
<https://reuse.software/faq/#custom-license>
right where it should be.

Thanks you two, and sorry for the trouble!
