### ISSUE TITLE
AI BOM Elements into SPDX AI

### ISSUE THREAD

**Issue by santosomar** [spdx/spdx-spec#863]
Hello SPDX maintainers and community members,

With the growing adoption of artificial intelligence (AI) and machine learning (ML) technologies, the demand for transparency, traceability, and security in AI development is very important. In light of this, this is why [SPDX AI](https://spdx.dev/learn/areas-of-interest/ai/). It provides a reference to the great work [Ezi Ozoani](https://huggingface.co/Ezi), [Marissa Gerchick](https://huggingface.co/Marissa), and [Margaret Mitchell](https://huggingface.co/meg) introduced the concept of [AI Model Cards in a blog post in 2022](https://huggingface.co/blog/model-cards). Since then, AI BOMs continue to evolve. Manifest (a supply chain security company) also introduced [an AI BOM concept](https://github.com/manifest-cyber/ai-bom) that is also now being suggested to be included in CDX. It has additional elements that were not captured in the [AI Model Cards](https://huggingface.co/blog/model-cards). 

I'd like to propose the introduction of AI Bill of Materials (AI BOM) elements that were expanded in the [AI BOM concept here](https://github.com/manifest-cyber/ai-bom) into the SPDX standard. Of course, after community consideration and input/modifications.

I also created [a visualization tool](https://github.com/santosomar/AI-BOM-Visualizer) that can help illustrate the concept [here](https://aibomviz.aisecurityresearch.org/) and the source code [here](https://github.com/santosomar/AI-BOM-Visualizer). I added some additional notes [here](https://becomingahacker.org/artificial-intelligence-bill-of-materials-ai-boms-ensuring-ai-transparency-and-traceability-82322643bd2a).

I kindly request the SPDX AI community to consider this proposal and provide feedback. I am preaching to the choir. Incorporating AI BOM elements into the SPDX standard can be a pivotal move in promoting transparency, supply chain security, and collaboration in the evolving (and super fast) AI landscape.

Thank you for your time and consideration.

**Comment by goneall** [comment]
This has been added to 3.0 as an AI profile.

Closing as resolved.

**Comment by santosomar** [comment]
Thank you @goneall and team! This is great. QQ: I was trying to search in the closed and open [pull requests](https://github.com/spdx/spdx-spec/pulls) for the addition of the AI profile and was not able to find it. Do you have a reference to the PR or draft documentation of the AI profile?

**Comment by goneall** [comment]
@santosomar - here's the AI profile part of the spec: https://spdx.github.io/spdx-spec/v3.0/model/AI/AI/

Here's the meeting minutes from the profile team: https://github.com/spdx/meetings/tree/main/ai

Feel free to join the meetings - it is a very active group: https://github.com/spdx/meetings?tab=readme-ov-file#ai-and-data-profiles-group-meetings

**Comment by santosomar** [comment]
This is amazing! Thank you so much! I will definitely join the meetings. Thank you again!!
