### ISSUE TITLE
efitools: exchangable license exception GPL <-> LGPL

### ISSUE THREAD

**Issue by sertonix** [spdx/spdx-spec#890]
The `COPYING` file of `efitools` states the following text:

> Contributing Authors agree that their code is submitted under the licence appropriate for its location within the source tree (GPL except for LGPL in lib/) and agree that any future patches, provided they are accepted into the project, may change the licence of their code from GPL to LGPL by moving pieces of it into lib/ or LGPL to GPL by moving pieces of it out of lib/

https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git/tree/COPYING

This sounds like `GPL-2.0-only OR LGPL-2.1-or-later` but I would like to know if an exception would be the correct thing for this.

**Comment by goneall** [comment]
Interesting question - since this is more legal related, I would suggest posting this to the legal mailing list: https://lists.spdx.org/g/spdx-legal

cc: @jlovejoy @swinslow

**Comment by goneall** [comment]
Closing this issue as not spec related.
