### ISSUE TITLE
`RelationshipComment` value should be free form text in the example

### ISSUE THREAD

**Issue by yash-nisar** [spdx/spdx-spec#90]
In the SPDX 2.1 specification, on [page 67](https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf#page=67), the value of the `RelationshipComment` tag under section `7.1.5` should be free form text.

**Comment by zvr** [comment]
The `RelationshipComment` instance mentioned is simply an example.

Its definition is in `7.2`, where it's clearly stated that its format is free form text.

**Comment by kestewart** [comment]
Text delimiter is only required if over multiple lines. 
In rendered version on we site,  looks like this is a bug with web rendering.   See .pdf version.
