### ISSUE TITLE
Fingerprint of data curation status as optional attribute on document level

### ISSUE THREAD

**Issue by mcjaeger** [spdx/spdx-spec#91]
Normally, generating SPDX document from scanners will (should) result always in the same SPDX document if generated repeatedly - if the scanner implementation does not change.

When an expert uses fossology to generate an SPDX file, it represents a snapshot of the database - because the SPDX also covers the concluded license fields (and cleaned text formatting garbage from the copyright statements maybe).

Usually, the expert then looks at the SPDX file and finds an error or maybe a correction to apply, she applies this in fossology and then regenerates the SPDX document. Right now, the two different resulting documents are distinguished by creation date.

However, for data curation w.r.t. the licenses concluded, it would be helpful to have a fingerprint, similar to a git commit hash, covering the state / set of concluded licenses to distinguish SPDX documents with curated data.

A similar need for fingerprinting the found / scanned licenses could be also helpful: But as I understood this is covered by the attribute about the scanner information and version.

**Comment by kestewart** [comment]
Manual corrections on top of scanned data can be represented with review under annotation  - will this work?   see: https://spdx.github.io/spdx-spec/8-annotations/

**Comment by kestewart** [comment]
Will close this for now,  please reopen if you disagree with way proposed (via annotation)
