### ISSUE TITLE
Automate the mkdocs table of contents

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#916]
See https://github.com/spdx/spdx-spec/issues/902#issuecomment-2045937208 for a suggestion on how to automate this.

**Comment by goneall** [comment]
cc: @rnjudge @zvr

**Comment by bact** [comment]
- For the generation part, it is now implemented in the spec-parser by https://github.com/spdx/spec-parser/pull/130
- https://github.com/spdx/spdx-spec/issues/978 is open as a reminder for the inclusion of the generated list in the publishing pipeline.

We can probably close this issue to clean up the 3.0 milestone.

**Comment by zvr** [comment]
Yup, closing this, let's follow on the latest opened one.
