### ISSUE TITLE
SPDX 3.0 CHANGELOG is empty

### ISSUE THREAD

**Issue by kartben** [spdx/spdx-spec#919]
Was trying to see at a glance what are the main changes/additions to the recently released SPDX 3.0 and checked out the CHANGELOG, but it doesn't seem to have been updated ahead of the release: https://github.com/spdx/spdx-spec/blob/v3.0/CHANGELOG.md
cc @kestewart

**Comment by kartben** [comment]
FWIW CHANGELOG on master still has a "TBD" for 3.0, which doesn't seem right?

**Comment by goneall** [comment]
@kartben the master branch is the last release, we use the development/vXX branches for the current in development work.  Once we release 3.0.1, the master branch will be updated.
