### ISSUE TITLE
Current Version on spdx.dev is still 2.3

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#925]
- 3.0 is not listed yet in https://spdx.dev/use/specifications/
- Also, https://spdx.github.io/spdx-spec/ is still redirects to https://spdx.github.io/spdx-spec/v2.3/

**Comment by goneall** [comment]
@licquia - can you help with this one?

**Comment by licquia** [comment]
The redirect for spdx.github.io should now go to 3.0.

**Comment by bact** [comment]
Confirmed. https://spdx.github.io/spdx-spec/ is now redirected to https://spdx.github.io/spdx-spec/v3.0/

**Comment by goneall** [comment]
> 3.0 is not listed yet in https://spdx.dev/use/specifications/

Interestingly, neither is 2.3

**Comment by goneall** [comment]
I just updated https://spdx.dev/use/specifications/

I'll go ahead and closed this as resolved - if anyone see any issues with the update, please open a new issue
