### ISSUE TITLE
List not displayed correctly in 4.2 RDF Serialization

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#928]
File serializations.md

https://spdx.github.io/spdx-spec/v3.0/serializations/

Text is rendered as:

Since the data model is based on RDF, any SPDX data can be serialized in any of the multiple RDF serialization formats, including but not limited to: - JSON-LD format as defined in [JSON-LD 1.1](https://www.w3.org/TR/json-ld11/); - Turtle (Terse RDF Triple Language) format as defined in [RDF 1.1 Turtle](https://www.w3.org/TR/turtle/); - N-Triples format as defined in [RDF 1.1 N-Triples](https://www.w3.org/TR/n-triples/); and - RDF/XML format as defined in [RDF 1.1 XML Syntax](https://www.w3.org/TR/rdf-syntax-grammar/).

It should be a list:

Since the data model is based on RDF, any SPDX data can be serialized in any of the multiple RDF serialization formats, including but not limited to:

- JSON-LD format as defined in [JSON-LD 1.1](https://www.w3.org/TR/json-ld11/);
- Turtle (Terse RDF Triple Language) format as defined in [RDF 1.1 Turtle](https://www.w3.org/TR/turtle/);
- N-Triples format as defined in [RDF 1.1 N-Triples](https://www.w3.org/TR/n-triples/); and
- RDF/XML format as defined in [RDF 1.1 XML Syntax](https://www.w3.org/TR/rdf-syntax-grammar/).

**Comment by bact** [comment]
Will be fixed by #927
