### ISSUE TITLE
Wrong display for strikethrough text

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#929]
https://spdx.github.io/spdx-spec/v3.0/annexes/diffs-from-previous-editions/

File diffs-from-previous-editions.md

In the relationship table, there should be strikethrough text for removed relationships.

But it is displayed as:
```
~~DEPENDENCY_OF~~
```
instead of
~~DEPENDENCY_OF~~

**Comment by bact** [comment]
Confirmed.

MkDocs (a tool that use to generate HTML for spec website) does not support strikethrough.
https://www.markdownguide.org/tools/mkdocs/

**Comment by bact** [comment]
Add support of strikethrough text in PR #997

**Comment by zvr** [comment]
Text should be changed to not make use of strikethrough.

**Comment by goneall** [comment]
The strikethroughs have been removed - closing this issue as resolved.
