### ISSUE TITLE
The SPDX 3.0 HTML page does not have the version selection dropdown

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#939]
See: https://spdx.github.io/spdx-spec/v3.0/

**Comment by bact** [comment]
It does have the version selection dropdown on the left pane, but somehow the default position of the left pane move a little bit down - so the dropdown is out of the view. A user has to scroll up the left pane in order to see the dropdown.

So yes this has to be fixed.

**Comment by bact** [comment]
Inspecting the HTML:

- The `ul` element for the entire model always got `current` value in its `class` property.

- Also, the `a` element for the "Core" always got `current` value in its `class` property.

**Comment by licquia** [comment]
Filed #958 to cover the Core expansion issue.

**Comment by bact** [comment]
This will be fixed once we upgrade mkdocs to 1.6

Open PR to upgrade mkdocs #986

**Comment by goneall** [comment]
User error - you just have to scroll up

**Comment by bact** [comment]
Would be great anyway if we can fix the UI to have the dropdown immediately visible.
