### ISSUE TITLE
capitalization issue 3.21.6

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#94]
3.21.6 RDF: property target in class spdx:ExternalRef in class spdx:Package

should be spdx:externalRef.

**Comment by salicodes** [comment]
I have spotted same issue at **3.22.6** RDF: Property `rdfs:comment` in class `spdx:externalRef` in class `spdx:Package`

Opening a PR

**Comment by kestewart** [comment]
Its consistent with what is in 2.1,  and I agree both are bugs, and need to be fixed for 2.2

**Comment by iamwillbar** [comment]
@kestewart this would technical be a breaking change, are we comfortable fixing this in 2.2?

**Comment by goneall** [comment]
I think this is just somewhat confusing documentation and not a breaking change.

I just created a pull request #186 to address.
