### ISSUE TITLE
The PDF version of the 3.0 specification is broken

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#942]
I just noticed that in page https://spdx.dev/use/specifications/ there is now a PDF version of the 3.0 specification.

This is not a good idea as the PDF version is broken.

It seems that the tool that creates the PDF only prints the first page of the source file. This means that all annexes are incomplete, but also several long pages.

**Comment by goneall** [comment]
@vargenau Thanks for pointing this out - I'll remove the PDF link from the website.

I'll leave this issue open to track generating the PDF.

**Comment by kestewart** [comment]
Need to make sure we put up the 3.0 .pdf when adding in the 3.0.1 to the website, and making it findable

**Comment by goneall** [comment]
@zvr - Do we have a suitable PDF for upload?

**Comment by goneall** [comment]
PDF is now loaded on the site - closing

**Comment by bact** [comment]
Just for reference, SPDX 3.0 PDF URL on https://spdx.dev/use/specifications/ page as of 22 Dec 2024: https://spdx.dev/wp-content/uploads/sites/31/2024/12/SPDX-3.0.1-1.pdf
