### ISSUE TITLE
Several TODOs in specification version 3.0.0

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#944]
The following sections have a TODO:
* Terms and definitions
* NamespaceMap
* Annex B: Getting started writing SPDX 3 (Informative)
* Annex C: RDF object model and identifier syntax (Normative)
* Annex E: Using SPDX license list short identifiers in source files (Informative)

**Comment by goneall** [comment]
Hmmm - I ran a grep on TODO's a couple months ago and I thought we took care of all of them.  It looks like most of these are in Annexes we added.

Definitely something we need to fix for 3.0.5.

**Comment by bact** [comment]
Few of them are in the form of `TBD`:

https://github.com/spdx/spdx-3-model/blob/802137f6a3156d831cffe0f51b62e11c0de0eb50/serialization/lite.md?plain=1#L25

Not sure if this one is also relevant or not:

https://github.com/spdx/spdx-3-model/blob/802137f6a3156d831cffe0f51b62e11c0de0eb50/serialization/json_ld/examples/sbom1.json#L13

**Comment by bact** [comment]
- Update on a TODO in Annex B: Getting started writing SPDX 3 - https://github.com/spdx/spdx-spec/issues/975

**Comment by kestewart** [comment]
@zvr to comment after he finishes his PR.

**Comment by goneall** [comment]
All TODO's have been resolved
