### ISSUE TITLE
Address gaps in documentation of VEX implementation in SPDX 3.0

### ISSUE THREAD

**Issue by VenkatTechnologist** [spdx/spdx-spec#948]
While going through SPDX 3.0 model VEX implementation, Venkat observed that there were gaps in documentation of the implementation. Specifically, the following were observed:

1. There is no documentation for the how VEX objects are implemented in SPDX and its structure
2. There is no mapping of VEX objects to the SPDX. The team felt that it would be better to have a mapping
3. There are no examples of various scenarios of how the VEX would be implemented in SPDX format

In the SPDX security meeting that happened on March 20th, 2024, which @goneall , @kestewart , Jeff Schutt, and @VenkatTechnologist attended, it was decided to have a document in the Annexure directory for the mapping and the examples. 

In another email thread between Venkat, @goneall, @puerco , @kestewart, and Jeff Schutt, Venkat pointed out that there is no formal documentation for how VEX objects are implemented in SPDX and its structure. This email was also forwarded to @rnjudge by Venkat.

This issue is to track and resolve these gaps.

**Comment by kestewart** [comment]
Annex about VEX has moved to https://github.com/spdx/using.   Please review content there, and if still concern open issue there.
