### ISSUE TITLE
Upper Camel Case or lower camel case

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#95]
The current specification has the tag/value properties specified to be in UpperCamelCase format while the RDF properties are specified to be in lowerCamelCase.  This was debated and decided some time ago.

We are now considering adding the following formats:

- YAML
- JSON
- XML

For these formats, do we want to follow the UpperCamelCase naming convention for properties/element or lowerCamelCase format for properties/element?  

Do we want to allow different standards for the different formats (similar to the current spec for tag/value and RDF)?

**Comment by goneall** [comment]
From an SPDX tools perspective, we plan on re-writing the tools to generate the Java classes from an XSD schema representing the specification then generate all of the formats from the mostly generated code.

It would be far easier to write if all of the generated formats used exactly the same names for properties including case.

We would still have to "hand-parse" the tag/value since there are no existing code generators for this format.

For this reason, I would propose lowerCamelCase for all supported formats with the exception of tag/value which we would leave as.

**Comment by kestewart** [comment]
Note: if we break some things it may need to go to 3.0.  Try for maintaining current consistency.  Possibly solve requirements by post process pass?

**Comment by goneall** [comment]
Consensus on 15 Oct call: consistency across new formats with lower Camel case.  For example, issue #143

**Comment by kestewart** [comment]
From discussion on call,  we're going to close this and revisit this in 3.0 as part of #198
