### ISSUE TITLE
publish_common.yml made a reference to non-existing mike version (1.2.0)

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#951]
publish_common.yml made a reference to `mike==1.2.0`

https://github.com/spdx/spdx-spec/blob/a9c2e6fbcca28ca31380f4c9035215b1e782d5a2/.github/workflows/publish_common.yml#L27

But that version does not existed.

mike has version 1.1.2 and then 2.0.0.
Ref: https://pypi.org/project/mike/#history

```shell
% pip install mike==1.2.0
ERROR: Ignored the following yanked versions: 0.6.0
ERROR: Could not find a version that satisfies the requirement mike==1.2.0 (from versions: 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 2.0.0)
ERROR: No matching distribution found for mike==1.2.0
% 
```

**Comment by kestewart** [comment]
Talked to Art, and this has been resolved.  Closing.
