### ISSUE TITLE
Inclusion of Glossary in the spec document?

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#956]
Currently the Glossary of Terms is available at the model development repo
- https://github.com/spdx/spdx-3-model/blob/main/Glossary.md

Should we consider to include this into a more visible place to the general audience?

For example, as an annex of the spec doc published on https://spdx.github.io/spdx-spec/v3.0/

There can be at least two ways to do this:

1. Permanently move the `Glossary.md` from `spec-3-model` repo to somewhere inside the `docs/` directory of `spdx-spec` repo (and renamed it to `glossary.md` to be consistent with other files)
    - Future edits of the Glossary will happen in `spdx-spec` repo (change from now)
2. Dynamically copy the `Glossary.md` from `spec-3-model` repo to somewhere inside the `docs/` directory of `spdx-spec` repo everytime there's a doc generation (and renamed it to `glossary.md` to be consistent with other files)
    - Future edits of the Glossary will happen in `spdx-3-model` repo (same as now)
    - Need modification in `.github/workflows/publish_v3.yml` and probably a script for local test

**Comment by zvr** [comment]
I think the glossary is more about the model and I'm not sure it belongs in the spec.

**Comment by kestewart** [comment]
Closing this based on discussion.   Please reopen if you disagree.
