### ISSUE TITLE
The software Profile contains the property `None`

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-spec#957]
The software Profile contains the property `None`, this is probably a bug in the https://github.com/spdx/spec-parser/

![image](https://github.com/spdx/spdx-spec/assets/1187050/d13ac51c-3dfc-42be-ba5e-fbf52189df47)

CC @zvr

**Comment by zvr** [comment]
No, not related to spec-parser.

The current mkdocs.yml file includes an entry for `model/Software/Properties/isDirectory.md` which is not there any more. 

This is due to #916.

**Comment by bact** [comment]
Fixed one-off by https://github.com/spdx/spdx-spec/pull/955 and will be systematically be prevented by https://github.com/spdx/spec-parser/pull/130

See: https://github.com/spdx/spdx-spec/issues/978 

I think this can be close.

**Comment by zvr** [comment]
Closing this
