### ISSUE TITLE
The 3.0 spec really want you have the Core tree expanded

### ISSUE THREAD

**Issue by licquia** [spdx/spdx-spec#958]
From the 2024-05-07 tech call (ref @kestewart ):

When the 3.0 spec is opened, it centers the sidebar on the Core portion of the model, and expands the tree.  You can collapse the tree, but under a number of circumstances, something feels it's important to re-expand the Core tree.

This makes the sidebar more difficult to use, as the Core tree is large, and it tends to make the actual current context scroll off the bottom.

**Comment by bact** [comment]
It could be something to do with the focus or "highlighted" position as well.

See some investigations here https://github.com/spdx/spdx-spec/issues/939#issuecomment-2081586866

**Comment by bact** [comment]
We may need to set `collapse_navigation: true` in `mkdocs.yml`.
But from the [documentation](https://walle.readthedocs.io/en/latest/user-guide/styling-your-docs/), this value is already `true` by default.

**Comment by bact** [comment]
A "work around" for now, until we can fix the expansion issue, is maybe move the Annex section up before the Model. So at least people can still notice the existence of the Annex.

**Comment by bact** [comment]
May related to this https://github.com/mkdocs/mkdocs/issues/3292

Fix purposed here https://github.com/mkdocs/mkdocs/pull/3464

**Comment by bact** [comment]
Looks like fixed in mkdocs 1.6.0

**Comment by bact** [comment]
A PR #986 opened to upgrade to 1.6

**Comment by bact** [comment]
@licquia  PR #995 (merged) should fixed this. Please see https://spdx.github.io/spdx-spec/v3.0.1-draft/

**Comment by bact** [comment]
This one can be closed.

**Comment by goneall** [comment]
Resolved - closing
