### ISSUE TITLE
Sidebar fixed to where it was clicked on.

### ISSUE THREAD

**Issue by gmscofield** [spdx/spdx-spec#965]
I visited the SPDX spec 3.0 website and clicked on the data field in sidebar to jump to where I wanna see. Whenever I clicked on any data field, the sidebar would roll back to "Core" after refreshing. Could the sidebar be fixed on where it was clicked on the last time?

**Comment by bact** [comment]
See the discussion here https://github.com/spdx/spdx-spec/issues/939#issuecomment-2081586866

**Comment by gmscofield** [comment]
Oh I see. Wish for the solutions.

**Comment by bact** [comment]
Should be fixed once we upgraded to mkdocs 1.6
https://github.com/spdx/spdx-spec/pull/986

**Comment by bact** [comment]
@gmscofield  Should be fixed now, please check: https://spdx.github.io/spdx-spec/v3.0.1-draft/

**Comment by gmscofield** [comment]
> @gmscofield Should be fixed now, please check: https://spdx.github.io/spdx-spec/v3.0.1-draft/

Oh I got that.
Thank you!
