### ISSUE TITLE
HTML: URLs should be clickable

### ISSUE THREAD

**Issue by stefan6419846** [spdx/spdx-spec#966]
When browsing the HTML version of the specification, quite a lot of external resources/URLs are not clickable.

Example: On https://spdx.github.io/spdx-spec/v3.0/model/Core/Vocabularies/HashAlgorithm/, none of the standards has actual links - they are currently rendered as plain text only. This makes it hard to actually use them as I have to manually copy/drag them over instead of just clicking on them.

**Comment by bact** [comment]
Some of the issues here are addressed by https://github.com/spdx/spdx-3-model/pull/751

**Comment by kestewart** [comment]
This should be fixed in the newly generated 3.0.1 - please close after this has been confirmed.

**Comment by stefan6419846** [comment]
Thanks. I just had a quick look at the linked page and it looked fine.
