### ISSUE TITLE
Add External Reference to "Identity of Digital Object"

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#97]
see discussion in:
https://annex.softwareheritage.org/public/talks/2018/2018-09-25-iPres2018.pdf

Would like to be able to refer to artifacts contained in Software Heritage.

**Comment by kestewart** [comment]
https://spdx.github.io/spdx-spec/appendix-VI-external-repository-identifiers/ will need to be enhanced to figure out "type" and then syntax of the reference.

For simplicity,  can we adopt type = "swh" and then follow
https://docs.softwareheritage.org/devel/swh-model/persistent-identifiers.html

Thoughts?

**Comment by zacchiro** [comment]
As author of the Software Heritage persistent identifiers (PIDs) spec, this sounds like the right approach to me. "swh" is a reasonable choice of prefix, as we have registered it for Software Heritage in various registries.

I'm guessing that contextual information (line number, software origin) are probably redundant for SPDX so you can probably ignore that part of our spec. That is, you should focus on the `<identifier>` entry point of the grammar, and ignore `<identifier_with_context>`.

**Comment by zvr** [comment]
I really support the idea to use swh: identifiers for external references!

**Comment by swinslow** [comment]
Agree, I think this is a good addition.

**Comment by zvr** [comment]
Should it be in the <category> = "OTHER" ?
The rule we have for this category already covers any possible reference...

**Comment by kestewart** [comment]
@zvr - thinking is we create a new category for it using "swh" as prefix per Zach's preference.
Recommendation is to focus on the <identifier> entry point of the grammar, and ignore <identifier_with_context>

**Comment by kestewart** [comment]
Possibly we should have a category of "REPOSITORY"?

**Comment by kestewart** [comment]
From call,  decision to make this "PERSISTENT-ID" category (after checking spelling)  - Mirror what's in package manager.

**Comment by kestewart** [comment]
Note:  need to reach out to Philippe and ask if he wants to move PURL to this class or leave under package manager.

**Comment by zacchiro** [comment]
On Tue, Apr 07, 2020 at 05:36:48PM +0000, Kate Stewart wrote:
> Closed #97 via #226.

Thanks Kate !
