### ISSUE TITLE
Open Source Hardware - in scope?

### ISSUE THREAD

**Issue by hoijui** [spdx/spdx-spec#976]
Is it purposefully out of scope, or would it be an option to include it at some time?

In OSH - in the best case - we also have source files in git repos, that need to be licensed thoroughly. In our group (developing standards for OSH meta-data), we currently do this using SPDX. Reading the spec though, it is clear that it is meant for Software; for example, the description of `spdx:Package` reads:

> A Package represents a collection of **software** files that are delivered as a single functional component.

In this specific case, we can just as well adapt it to include the design files and manual of an OSH project, or parts of it.
When it comes to other things like "binary files" and "linking" though, the equivalent in hardware projects is not as easy, or simply not given.
Is there a stance on this subject?

In general, it would be sad/a big waste in my eyes, if we can not find some good way to solve this, sharing a big junk of SPDX with the hardware world, without simply duplicating everything.

**Comment by goneall** [comment]
@hoijui - There is a hardware profile team discussing how to add hardware to the SPDX specification.

They meet weekly - the meeting information can be found [here](https://github.com/spdx/meetings?tab=readme-ov-file#hardware-profile-group-meetings).

Minutes of past meetings can be found here: https://github.com/spdx/meetings/tree/main/hardware

I am hopeful that this will be part of an upcoming SPDX 3.1 release.

**Comment by hoijui** [comment]
oh WOW! :O
that is very surprising, great news!
thank you for the info!!

**Comment by kestewart** [comment]
Closing this as question has been answered.
