### ISSUE TITLE
Is there code/a software that converts an SPDX license expression into valid OWL/RDF?

### ISSUE THREAD

**Issue by hoijui** [spdx/spdx-spec#977]
[SPDX license expressions](https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/) are strings that might look like "MIT OR LicenseRef-MyOwnLicense". As much as I figured, this would have to be represented differently in RDF, using multiple triples, including at least one [disjunctive license set](https://spdx.org/rdf/terms/#d4e2336) individual.

Is there already open source code/a tool that can do this conversion?

**Comment by goneall** [comment]
> Is there already open source code/a tool that can do this conversion?

Somewhat - the [SPDX Java tools](https://github.com/spdx/tools-java) and the [SPDX Online tools](https://tools.spdx.org/app/convert/) can convert from a JSON, Tag/Value or spreadsheet containing the string representation of a license expression to RDF format (RDF/XML or RDF/TTL).

The tools won't translate just the license expression string, but that would not be too difficult to add.

**Comment by hoijui** [comment]
Ahh nice, thank you! :-)
I'll have a look at the CLI tool and converting from JSON to RDF ...

**Comment by hoijui** [comment]
I got the tool running .. do you maybe have an example JSON file?

**Comment by goneall** [comment]
> I got the tool running .. do you maybe have an example JSON file?

The official examples are in the spec repo - since we're working with SPDX version 2.3, you should use [these examples](https://github.com/spdx/spdx-spec/tree/development/v2.3.1/examples).

**Comment by kestewart** [comment]
Cloasing this as I think the answers have resolved.   Please reopen if I've missed something.
