### ISSUE TITLE
Use the actual list of model entries

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-spec#978]
The current publishing setup uses a static list of pages in https://github.com/spdx/spdx-spec/blob/aac3e38b0b01b2ccb129367617a07598cf0ccdd8/mkdocs.yml#L22-L327

This might not correspond to the actual contents of the model.

The generation of mkdocs input (all the .md files) also generates a list, ready to be included in the file.

The publishing setup should be updated to include and use this, every time the web content is being generated.

**Comment by bact** [comment]
#995 merged, our mkdocs.yml now using the actual list of model entries generated from the spec-parser.

**Comment by kestewart** [comment]
This appears to now be fixed.  Closing.
