### ISSUE TITLE
Be more explicit about the case sensitivity of license identifiers

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-spec#981]
Spec says:

> License identifiers (including license exception identifiers) used in SPDX documents or source code files should be matched in a case-insensitive manner. In other words, MIT, Mit and mIt should all be treated as the same identifier and referring to the same license.

On the tech mailing list, the following was asked:

> I was just dealing with a corner case in my code concerning LicenseRefs (and the same question also applies to SPDX 3.0 AdditionRefs), and Annex D of the specification [1] didn't clarify it for me (and perhaps could be clarified to do so, once we know the answer).
>  
> Basically my question boils down to: are LicenseRefs / AdditionRefs that only differ by case identical?
>  
> For example, are these two LicenseRefs identical or different?
> - ```LicenseRef-my-tool-some-identifier```
> - ```LicenseRef-My-Tool-Some-Identifier```

I add the following question: is ```licenseref-my-tool-some-identifier``` a legal license identifier?

The answers to these questions should be added to the spec.

I did some tests with:
- Java tools 1.1.8
- Python tools 0.8.2

The tests were done with SPDX 2, but as the text about case-sensitivity is the same in SPDX 2 and 3, the ambiguity is the same in both versions.

**Case 1**

```
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: case-sensitive
DocumentNamespace: https://example.net/spdx/case-sensitive
Creator: Person: Marc-Etienne Vargenau
Created: 2024-07-02T01:55:00Z

##### Package A

PackageName: A
SPDXID: SPDXRef-A
PackageDownloadLocation: NOASSERTION
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: licenseref-case-sensitive
PackageCopyrightText: NOASSERTION

Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-A

##### Non-standard license

LicenseID: licenseref-case-sensitive
ExtractedText: <text>Copyright</text>
LicenseName: case-sensitive
```

Both Python and Java say this is invalid. So ```licenseref-case-sensitive``` is invalid.

**Case 2**

```
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: case-sensitive
DocumentNamespace: https://example.net/spdx/case-sensitive
Creator: Person: Marc-Etienne Vargenau
Created: 2024-07-02T01:55:00Z

##### Package A

PackageName: A
SPDXID: SPDXRef-A
PackageDownloadLocation: NOASSERTION
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: LicenseRef-Case-Sensitive
PackageCopyrightText: NOASSERTION

Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-A

##### Package B

PackageName: B
SPDXID: SPDXRef-B
PackageDownloadLocation: NOASSERTION
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: LicenseRef-case-sensitive
PackageCopyrightText: NOASSERTION

Relationship: SPDXRef-A CONTAINS SPDXRef-B

##### Non-standard license

LicenseID: LicenseRef-Case-Sensitive
ExtractedText: <text>Copyright</text>
LicenseName: Case-Sensitive
```

- Python says it is invalid. So it considers it is case-sensitive.
- Java says it is valid. So it considers it is case-insensitive.

**Case 3**

```
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: case-sensitive
DocumentNamespace: https://example.net/spdx/case-sensitive
Creator: Person: Marc-Etienne Vargenau
Created: 2024-07-02T01:55:00Z

##### Package A

PackageName: A
SPDXID: SPDXRef-A
PackageDownloadLocation: NOASSERTION
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: LicenseRef-Case-Sensitive
PackageCopyrightText: NOASSERTION

Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-A

##### Package B

PackageName: B
SPDXID: SPDXRef-B
PackageDownloadLocation: NOASSERTION
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: LicenseRef-case-sensitive
PackageCopyrightText: NOASSERTION

Relationship: SPDXRef-A CONTAINS SPDXRef-B

##### Non-standard license

LicenseID: LicenseRef-Case-Sensitive
ExtractedText: <text>Copyright</text>
LicenseName: Case-Sensitive

LicenseID: LicenseRef-case-sensitive
ExtractedText: <text>Copyright2</text>
LicenseName: case-sensitive
```

Both Python and Java say this is valid. So they consider it is case-sensitive.

**Case 4**

```
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: case-sensitive
DocumentNamespace: https://example.net/spdx/case-sensitive
Creator: Person: Marc-Etienne Vargenau
Created: 2024-07-02T01:55:00Z

##### Package A

PackageName: A
SPDXID: SPDXRef-A
PackageDownloadLocation: NOASSERTION
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: LicenseRef-Case-Sensitive
PackageCopyrightText: NOASSERTION

Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-A

##### Package B

PackageName: B
SPDXID: SPDXRef-B
PackageDownloadLocation: NOASSERTION
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: licenseref-case-sensitive
PackageCopyrightText: NOASSERTION

Relationship: SPDXRef-A CONTAINS SPDXRef-B

##### Non-standard license

LicenseID: LicenseRef-Case-Sensitive
ExtractedText: <text>Copyright</text>
LicenseName: Case-Sensitive
```

- Python says it is invalid.
- Java says it is valid

Here we have a contradiction with case 1 , ```licenseref-case-sensitive```is valid (for Java).

[case-sensitive1.spdx.txt](https://github.com/user-attachments/files/16088487/case-sensitive1.spdx.txt)
[case-sensitive2.spdx.txt](https://github.com/user-attachments/files/16088486/case-sensitive2.spdx.txt)
[case-sensitive3.spdx.txt](https://github.com/user-attachments/files/16088485/case-sensitive3.spdx.txt)
[case-sensitive4.spdx.txt](https://github.com/user-attachments/files/16088484/case-sensitive4.spdx.txt)

**Comment by lpanni** [comment]
I'm pretty sure `licenseref-*` should never be valid considering the ABNF syntax for license expressions in [SPDX 2.2.2](https://spdx.github.io/spdx-spec/v2.2.2/SPDX-license-expressions/), [2.3](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/) and [3.0](https://spdx.github.io/spdx-spec/v3.0/annexes/SPDX-license-expressions/).

But the specification also clearly states that the license identifiers should be matched case-insensitively. So your second case should be valid.

However, from my understanding this would also mean that your third case should be considered invalid, because you'd have duplicate, conflicting entries for the case-insensitive license identifier. The exception for matching the casing of canonical identifiers isn't important here as we're dealing with a user-defined reference.

**Comment by vargenau** [comment]
Yes, I agree that the spec meant to say that ```licenseref-*``` is not valid.
But as it written now, there is a contradiction between the section about case sensitivity and the ABNF.
I will create a pull request to clarify.

**Comment by zvr** [comment]
@vargenau I think I have fixed that in https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/annexes/SPDX-license-expressions.md with https://github.com/spdx/spdx-spec/commit/151cd0fff87eb9ca966235d9a56af71d2b20c350.

We do not plan to publish updated versions of SPDXv2 specs.

**Comment by vargenau** [comment]
Hi @zvr,
Yes, no need to update SPDX 2. I just created a pull request for 3.0.1 to clarify.

**Comment by bact** [comment]
- #984 - merged
