### ISSUE TITLE
Add date and timeline related information in SPDX

### ISSUE THREAD

**Issue by chandanbn** [spdx/spdx-spec#99]
From the discussion on Nov 30, 2018 NTIA Formats WG call:

SPDX does not have a way to encode timelines and events related the SPDX entities
These events may be:

0. last commit or change date
1. compile/build time aka **date of manufacture**
2. date and time of publication aka **release date**
3. end of life time aka **expiry date** or **best before**

These should be optional.

Use cases: 

1) An open source software may set end-of-life dates to indicate it will stop maintaining that version/branch after some date, or not evaluate it for security vulnerabilities. Consumers of that software ideally should stop using it after that date. Presence of this field will facilitate better supply chain management and reduce usage of risky out-dated components.

2) A build machine or service may have been compromised for a certain time period. All packages built on that machine or service during that period would need to be flagged.

**Comment by kestewart** [comment]
These probably make the most sense in the Package section (which can reflects package builds, product builds, aggregations, etc.).     Optional fields, using standard formats for date,  should be simple enough to add.   Flagging this for tech team discussion to be included in 2.2.

**Comment by kestewart** [comment]
Just finished talking to Lisa Bradley and she was requesting EOL indicators as well.   Showed her this request, and she +1'd it.    Now that 2.2 contribution window is unblocked will work up a pull request and link.

**Comment by kestewart** [comment]
This is going towards the provenence information.

**Comment by kestewart** [comment]
From discussion on call,  we're looking at adding this a part of provenance profile.   Moving this to 3.0 so we can explore this better.

**Comment by juliusmusseau** [comment]
Hiya !  We're an SCA startup (mergebase.com) and we produce SPDX SBOM for our customers.  Would love to put release dates in the SBOM.  We have the data!  Helps customers self-assess for staleness (e.g., using really old libraries is becoming a bit of a code smell, even if the library has no known security bugs).

`                 pkg                 |     v     |      release_date      
-------------------------------------+-----------+------------------------
 org.apache.logging.log4j/log4j-core | 2.17.2    | 2022-02-23 13:29:00+00
 org.apache.logging.log4j/log4j-core | 2.3.2     | 2021-12-28 19:27:04+00
 org.apache.logging.log4j/log4j-core | 2.12.4    | 2021-12-28 14:17:50+00
 org.apache.logging.log4j/log4j-core | 2.17.1    | 2021-12-27 17:30:42+00
 org.apache.logging.log4j/log4j-core | 2.3.1     | 2021-12-20 21:42:20+00
 org.apache.logging.log4j/log4j-core | 2.12.3    | 2021-12-20 16:14:22+00
 org.apache.logging.log4j/log4j-core | 2.17.0    | 2021-12-17 18:57:50+00
 org.apache.logging.log4j/log4j-core | 2.12.2    | 2021-12-13 22:35:38+00
 org.apache.logging.log4j/log4j-core | 2.16.0    | 2021-12-12 23:41:20+00
 org.apache.logging.log4j/log4j-core | 2.15.0    | 2021-12-09 11:25:54+00
 org.apache.logging.log4j/log4j-core | 2.14.1    | 2021-03-06 22:12:16+00
 org.apache.logging.log4j/log4j-core | 2.14.0    | 2020-11-06 14:03:18+00
 org.apache.logging.log4j/log4j-core | 2.13.3    | 2020-05-10 12:09:06+00
 org.apache.logging.log4j/log4j-core | 2.13.2    | 2020-04-20 21:37:58+00
 org.apache.logging.log4j/log4j-core | 2.13.1    | 2020-02-25 19:53:38+00
 org.apache.logging.log4j/log4j-core | 2.13.0    | 2019-12-11 19:42:10+00
 org.apache.logging.log4j/log4j-core | 2.12.1    | 2019-08-06 20:45:42+00
 org.apache.logging.log4j/log4j-core | 2.12.0    | 2019-06-25 20:37:22+00
 org.apache.logging.log4j/log4j-core | 2.11.2    | 2019-02-05 18:12:30+00
 org.apache.logging.log4j/log4j-core | 2.11.1    | 2018-07-22 20:45:52+00
 org.apache.logging.log4j/log4j-core | 2.11.0    | 2018-03-11 15:44:10+00
 org.apache.logging.log4j/log4j-core | 2.10.0    | 2017-11-19 01:03:28+00
 org.apache.logging.log4j/log4j-core | 2.9.1     | 2017-09-17 23:05:36+00
 org.apache.logging.log4j/log4j-core | 2.9.0     | 2017-08-26 13:49:48+00
 org.apache.logging.log4j/log4j-core | 2.8.2     | 2017-04-02 15:36:28+00
 org.apache.logging.log4j/log4j-core | 2.8.1     | 2017-02-26 17:05:44+00
 org.apache.logging.log4j/log4j-core | 2.8       | 2017-01-21 22:19:08+00
 org.apache.logging.log4j/log4j-core | 2.7       | 2016-10-02 11:24:14+00
`

**Comment by zvr** [comment]
Nice data, @juliusmusseau, although you have to define what the "release date" actually mean.

For example, I can think of:
- when the source was last modified
- when the .jar file was created
- when it was pushed to maven
- when it was made available via maven
- etc. etc.

As @kestewart noted above, such pieces of information (probably more than one) will most probably be included in the provenance profile of SPDX 3.0.

**Comment by juliusmusseau** [comment]
Very good point!

In that example we're using "youngest timestamp among all files inside the jar file downloaded from maven-central" which generally correlates to within 72 hours of the Apache release vote, the release tag, the release build, etc.  Since staleness questions concern "is this library months or years out of date?" a bit of fuzziness around the exact moment-of-release is not that important for our usage of this data, as long as that fuzziness is limited to a couple weeks at most.

**Comment by goneall** [comment]
Ping @kestewart @puerco

**Comment by kestewart** [comment]
We can close this as the fields requested are implemented and available in 3.0.

https://spdx.github.io/spdx-spec/v3.0/model/Core/Properties/builtTime/
https://spdx.github.io/spdx-spec/v3.0/model/Core/Properties/releaseTime/
https://spdx.github.io/spdx-spec/v3.0/model/Core/Properties/validUntilTime/
which can be combined with https://spdx.github.io/spdx-spec/v3.0/model/Core/Properties/supportLevel/

To describe the End of Life support.
