### ISSUE TITLE
Annex A (diffs from previous) should be about the previous ISO version

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-spec#999]
Annex A (as it will appear in the updated ISO standard) should contain the differences between this version (3.0.1) and the previous ISO version (2.2.1).

Content of differences between older versions (like the one currently there, in sections A.4 - A.7) is more like "release notes".

This probably would be better to be moved to spdx/using documentation repository.

@goneall @kestewart do you agree?

**Comment by kestewart** [comment]
Agreed in meeting today to generate text for Annex relative to prior ISO submission, and to submit PR, after Alexios sorts out the numbering.

**Comment by zvr** [comment]
In #1044 I add an almost empty file `docs/annexes/changes-from-previous-iso.md` to be filled in...

**Comment by zvr** [comment]
@kestewart @goneall @bact 
Any update on content for https://github.com/spdx/spdx-spec/blob/development/v3.0.1/submissions/ISO/annexes/changes-from-previous-iso.md ? 

ISO PDF has to be produced on Friday, AFAIK...
